### ISSUE TITLE
hyberKube & client of rbd&nfs&glusterfs

### ISSUE THREAD

**Issue by min-zh** [kubesphere/kubekey#10]
Could hyberKube & client of rbd&nfs&glusterfs be supported by KK in the future ?

**Comment by pixiake** [comment]
1. The hyperkube has been deprecated and removed，so no more support for it.
2. To avoid dependency issues, it is recommended to [install storage client](https://github.com/kubesphere/kubekey/blob/master/docs/storage-client.md) yourself.
3. The clients of controller-manager may need to build into the image.

**Comment by min-zh** [comment]
Nice~
