### ISSUE TITLE
Install failed about binary sha256 not match

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubekey#101]
```
[root@ip-172-31-2-146 centos]# ./kk create cluster -f config-sample.yaml
+-------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
| name  | sudo | curl | openssl | ebtables | socat | ipset | conntrack | docker | nfs client | ceph client | glusterfs client | time         |
+-------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
| node1 | y    | y    | y       | y        | y     | y     | y         | y      | y          | y           | y                | UTC 02:12:18 |
+-------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+

This is a simple check of your environment.
Before installation, you should ensure that your machines meet all requirements specified at
https://github.com/kubesphere/kubekey#requirements-and-recommendations

Continue this installation? [yes/no]: yes
INFO[02:12:21 UTC] Downloading Installation Files
INFO[02:12:21 UTC] Downloading kubeadm ...
WARN[02:12:22 UTC] Task failed ...
WARN[02:12:22 UTC] error: Failed to load kube binaries: SHA256 no match. d4cfc9a0a734ba015594974ee4253b8965b95cdb6e83d8a6a946675aad418b40 not in d2149f7261e055efcbcf34fc803a1549e1262054afe2ff88f0e0c2602b972fcb  /home/centos/kubekey/v1.17.6/amd64/kubeadm
Error: Failed to download kube binaries: Failed to load kube binaries: SHA256 no match. d4cfc9a0a734ba015594974ee4253b8965b95cdb6e83d8a6a946675aad418b40 not in d2149f7261e055efcbcf34fc803a1549e1262054afe2ff88f0e0c2602b972fcb  /home/centos/kubekey/v1.17.6/amd64/kubeadm
Usage:
  kk create cluster [flags]

Flags:
  -f, --file string              Path to a configuration file
  -h, --help                     help for cluster
      --with-kubernetes string   Specify a supported version of kubernetes (default "v1.17.6")
      --with-kubesphere          Deploy a specific version of kubesphere (default v3.0.0)

Global Flags:
      --debug   Print detailed information (default true)

Failed to download kube binaries: Failed to load kube binaries: SHA256 no match. d4cfc9a0a734ba015594974ee4253b8965b95cdb6e83d8a6a946675aad418b40 not in d2149f7261e055efcbcf34fc803a1549e1262054afe2ff88f0e0c2602b972fcb  /home/centos/kubekey/v1.17.6/amd64/kubeadm
```

**Comment by pixiake** [comment]
`SHA256 no match`
Remove  the directory which named `kubekey`, and try it again.

**Comment by zackzhangkai** [comment]
It do works.

**Comment by sgyt1993** [comment]
Remove the kubekey directory,and try it again agin,but not success,how to solve the question
 
debug
root@wht-cyjtpt06:~# ./kk create cluster -f config-sample.yaml
+-------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
| name  | sudo | curl | openssl | ebtables | socat | ipset | conntrack | docker | nfs client | ceph client | glusterfs client | time         |
+-------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
| node6 | y    | y    | y       | y        | y     | y     | y         |        | y          |             |                  | CST 16:04:16 |
| node3 | y    | y    | y       | y        | y     | y     | y         |        | y          |             |                  | CST 16:04:16 |
| node1 | y    | y    | y       | y        | y     | y     | y         |        | y          |             |                  | CST 16:04:16 |
| node2 | y    | y    | y       | y        | y     | y     | y         |        | y          |             |                  | CST 16:04:16 |
| node5 | y    | y    | y       | y        | y     | y     | y         |        | y          |             |                  | CST 16:04:16 |
| node4 | y    | y    | y       | y        | y     | y     | y         |        | y          |             |                  | CST 16:04:16 |
+-------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+

This is a simple check of your environment.
Before installation, you should ensure that your machines meet all requirements specified at
https://github.com/kubesphere/kubekey#requirements-and-recommendations

Continue this installation? [yes/no]: yes
INFO[16:04:18 CST] Downloading Installation Files               
INFO[16:04:18 CST] Downloading kubeadm ...                      
INFO[16:04:18 CST] Downloading kubelet ...                      
INFO[16:04:19 CST] Downloading kubectl ...                      
INFO[16:04:19 CST] Downloading helm ...                         
INFO[16:04:19 CST] Downloading kubecni ...                      
INFO[16:04:20 CST] Downloading etcd ...                         
INFO[16:04:20 CST] Downloading docker ...                       
WARN[16:04:20 CST] Task failed ...                              
WARN[16:04:20 CST] error: SHA256 no match. 7ea11ecb100fdc085dbfd9ab1ff380e7f99733c890ed815510a5952e5d6dd7e0 not equal 4bf4e1ad4146d1229e16c6559289debb152f4f290477bd227970379d582abd60 
Error: Failed to download kube binaries: SHA256 no match. 7ea11ecb100fdc085dbfd9ab1ff380e7f99733c890ed815510a5952e5d6dd7e0 not equal 4bf4e1ad4146d1229e16c6559289debb152f4f290477bd227970379d582abd60
Usage:
  kk create cluster [flags]

Flags:
      --container-manager string   Container runtime: docker, crio, containerd and isula. (default "docker")
      --download-cmd string        The user defined command to download the necessary binary files. The first param '%s' is output path, the second param '%s', is the URL (default "curl -L -o %s %s")
  -f, --filename string            Path to a configuration file
  -h, --help                       help for cluster
      --skip-pull-images           Skip pre pull images
      --with-kubernetes string     Specify a supported version of kubernetes (default "v1.21.5")
      --with-kubesphere            Deploy a specific version of kubesphere (default v3.2.0)
      --with-local-storage         Deploy a local PV provisioner
  -y, --yes                        Skip pre-check of the installation

Global Flags:
      --debug        Print detailed information (default true)
      --in-cluster   Running inside the cluster

Failed to download kube binaries: SHA256 no match. 7ea11ecb100fdc085dbfd9ab1ff380e7f99733c890ed815510a5952e5d6dd7e0 not equal 4bf4e1ad4146d1229e16c6559289debb152f4f290477bd227970379d582abd60
