### ISSUE TITLE
failed to deploy on ubuntu 18.04

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubekey#104]
W0701 10:55:19.069649   17684 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
kubeadm join lb.kubesphere.local:6443 --token ays4v3.9exhj40g2ljmvg0d     --discovery-token-ca-cert-hash sha256:1472bc2f7147084b12a3e0aed32483187ac302d9e7ae82f1c1fc23ac284d7b2e
[ks-node1 68.79.24.116] MSG:
NAME       STATUS     ROLES           AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
ks-node1   NotReady   master,worker   2m44s   v1.18.3   172.31.2.153   <none>        Ubuntu 18.04.4 LTS   4.15.0-1063-aws   docker://19.3.8
INFO[18:55:19 CST] Synchronizing kube binaries                  
Push /Users/luxingmin/Documents/dev/pkgs/kubekey/output/kubekey/v1.18.3/amd64/kubeadm to 52.82.70.125:/tmp/kubekey/kubeadm   Done
Push /Users/luxingmin/Documents/dev/pkgs/kubekey/output/kubekey/v1.18.3/amd64/kubeadm to 52.82.27.246:/tmp/kubekey/kubeadm   Done
Push /Users/luxingmin/Documents/dev/pkgs/kubekey/output/kubekey/v1.18.3/amd64/kubelet to 52.82.70.125:/tmp/kubekey/kubelet   Done
Push /Users/luxingmin/Documents/dev/pkgs/kubekey/output/kubekey/v1.18.3/amd64/kubectl to 52.82.70.125:/tmp/kubekey/kubectl   Done
Push /Users/luxingmin/Documents/dev/pkgs/kubekey/output/kubekey/v1.18.3/amd64/kubelet to 52.82.27.246:/tmp/kubekey/kubelet   Done
Push /Users/luxingmin/Documents/dev/pkgs/kubekey/output/kubekey/v1.18.3/amd64/helm to 52.82.70.125:/tmp/kubekey/helm   Done
Push /Users/luxingmin/Documents/dev/pkgs/kubekey/output/kubekey/v1.18.3/amd64/cni-plugins-linux-amd64-v0.8.6.tgz to 52.82.70.125:/tmp/kubekey/cni-plugins-linux-amd64-v0.8.6.tgz   Done
Push /Users/luxingmin/Documents/dev/pkgs/kubekey/output/kubekey/v1.18.3/amd64/kubectl to 52.82.27.246:/tmp/kubekey/kubectl   Done
Push /Users/luxingmin/Documents/dev/pkgs/kubekey/output/kubekey/v1.18.3/amd64/helm to 52.82.27.246:/tmp/kubekey/helm   Done
Push /Users/luxingmin/Documents/dev/pkgs/kubekey/output/kubekey/v1.18.3/amd64/cni-plugins-linux-amd64-v0.8.6.tgz to 52.82.27.246:/tmp/kubekey/cni-plugins-linux-amd64-v0.8.6.tgz   Done
INFO[18:57:57 CST] Initializing kubernetes cluster              
INFO[18:57:57 CST] Deploying network plugin ...                 
ERRO[18:57:57 CST] Failed to read calico manifests: exit status 64  node=68.79.24.116
WARN[18:57:57 CST] Task failed ...                              
WARN[18:57:57 CST] error: interrupted by error                  
Error: Failed to deploy network plugin: interrupted by error

**Comment by pixiake** [comment]
`Failed to read calico manifests: exit status 64 node=68.79.24.116`

Does `./kubekey/calico.yaml` exist?

**Comment by lxm** [comment]
file exists

**Comment by lxm** [comment]
```
exec.Command("/bin/bash", "-c", fmt.Sprintf("tar cfz - -C %s -T /dev/stdin <<< calico.yaml | base64 --wrap=0", mgr.WorkDir)).CombinedOutput()
```

code above cannot run under macos 
i'll try anthoer system

**Comment by pixiake** [comment]
It could be a file permissions issue.
What‘s the user in config? 
What’s the user for executing？

**Comment by lxm** [comment]
seems like `tar` and `base64` commands were ran locally
and my local os is macos
args may different from linux
I have moved kk to linux system and redo the install with the same config file , it works well

**Comment by pixiake** [comment]
Yes，this command was ran locally.
MAC is not currently supported.
