### ISSUE TITLE
Can not install QKCP with k8s v1.19.8 

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubekey#1073]
### What is version of KubeKey has the issue?

v2.0.0-alpha.4

### What is your os environment?

centos 7.9 64bit

### A clear and concise description of what happend.

k8s version: `1.19.8`

**After install QKCP, the status of pods are pending**

<img width="835" alt="image" src="https://user-images.githubusercontent.com/68640256/154625230-a30aebed-f20f-488d-9255-6b4b09250e86.png">

**Comment by 24sama** [comment]
Can you use the `kubectl describe po` to show more information?

**Comment by wenxin-01** [comment]
> Can you use the `kubectl describe po` to show more information?

Do not have events.
![image](https://user-images.githubusercontent.com/68640256/154626410-a7e236c4-4c1e-402a-b49d-675430e8857e.png)

**Comment by pixiake** [comment]
This should be caused by the fact that the feature gate `CSIStorageCapacity` does not support v1.19.
