### ISSUE TITLE
More K8s versions support

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#109]
I tried 1.18.5, 1.17.8, 1.16.12. All threw the following error.
<img width="907" alt="Screen Shot 2020-07-02 at 12 53 33 PM" src="https://user-images.githubusercontent.com/28859385/86317903-2b274700-bc63-11ea-9982-c8df4e7ebb2d.png">

**Comment by rayzhou2017** [comment]
also got 1.15.10 not supported. What is the list of supported versions? I thought it would be 1.15.x ~ 1.18.x including the future versions among 1.15 ~ 1.18.

**Comment by pixiake** [comment]
To avoid installation failures due to problems downloading binaries, sha256 checksums need to be added to the supported versions.

https://github.com/kubesphere/kubekey/blob/3ea8c4103d30efddded3a51bd1d2172bcfdbfb95/pkg/files/file.go#L38
