### ISSUE TITLE
NodeLocalDNS

### ISSUE THREAD

**Issue by mirisu2** [kubesphere/kubekey#1091]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"latest+unreleased", GitCommit:"06029ec2c985c5c73bfa21869b63404a0bbd7709", GitTreeState:"clean", GoVersion:"go1.17.7"}

### What is your os environment?

Ubuntu Server 20.04 LTS

### A clear and concise description of what happend.

Is exist the solution to disable NodeLocalDNS feature? 
I tried to find options for cluster-config.yaml but I didn't.

**Comment by 24sama** [comment]
Hello @mirisu2 
You can set up the `config.yaml` like this:
```
## Omit other unrelated fields
spec：
  kubernetes:
    nodelocaldns: false
```

**Comment by mirisu2** [comment]
@24sama Thank you very much!
Could you please specify link where I can find all possible params I can use in cluster-config.yaml
I saw [config-example](https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md) and [docs](https://github.com/kubesphere/kubekey/tree/master/docs), but this param `nodelocaldns` didn't find

**Comment by 24sama** [comment]
There is missing this field in the [config-example](https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md).
Could you please help us to fix this issue?  Just add this field and the description in the doc.

/kind good-first-issue

**Comment by mirisu2** [comment]
```
## Omit other unrelated fields
spec：
  kubernetes:
    nodelocaldns: false
```
This works for me. Thanks
