### ISSUE TITLE
node labels

### ISSUE THREAD

**Issue by mirisu2** [kubesphere/kubekey#1093]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"latest+unreleased", GitCommit:"06029ec2c985c5c73bfa21869b63404a0bbd7709", GitTreeState:"clean", GoVersion:"go1.17.7"}

### What is your os environment?

Ubuntu Server 20.04 LTS

### A clear and concise description of what happend.

Hi,

is it possible to set `labels` or `taints` for nodes in the `config.yaml`?

**Comment by 24sama** [comment]
I found this is a bug in the master branch. I will fix it soon.

**Comment by 24sama** [comment]
The latest master branch code has been solved the issue. Feel free to reopen this issue if you have any questions.
