### ISSUE TITLE
修改IP后,重装集群启动etcd失败 etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by mafeifan** [kubesphere/kubekey#1096]
### What is version of KubeKey has the issue?

2.0.0-rc.3

### What is your os environment?

Ubuntu 20.04

### A clear and concise description of what happend.

我是在虚拟机里使用kk安装k8s集群。某种原因 我修改了虚拟机网络模式，由桥接改为了NAT，所以IP也发生了变化，由原来的 192.168.50.111 改为了 10.0.2.4

我打算重新安装集群

命令如下
```
rm .kube/* -rf
rm -rf /var/lib/etcd
rm -rf /etc/ssl/etcd
sudo kk delete cluster -f sample.yaml
sudo kk install cluster -f sample.yaml
```

依然报etcd启动失败，错误信息里出现原来了IP，我不知道是在哪配置

### Relevant log output

```shell
etcd health check failed: Failed to exec command: sudo -E /bin/bash -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-master.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-master-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://10.0.2.4:2379 cluster-health | grep -q 'cluster is healthy'"
Error:  client: etcd cluster is unavailable or misconfigured; error #0: x509: certificate is valid for 127.0.0.1, ::1, 192.168.50.111, not 10.0.2.4
```
```


### Additional information

_No response_

**Comment by mafeifan** [comment]
牛逼，解决了

**Comment by attila123** [comment]
Bumped into this problem with kk v3.0.7 (did not try the latest stable version) after changing `address` and `internalAddress` in my config. Translated this page to see the solution. This helped:

```
kk delete cluster -f my-kubekey-config.yaml

rm -rf /etc/ssl/etcd
rm -rf kubekey/<use the host name here>
rm -rf kubekey/pki/etcd

kk create cluster -f my-kubekey-config.yaml --skip-pull-images
```

`rm -rf kubekey/pki/etcd` was definitely needed, not sure about the others.

BTW, I don't understand why the OP started deleting things before deleting the cluster with kk, does not feel like a logical order. If you do 'kk delete cluster ...' first, then `/var/lib/etcd` will be removed as well.

I wonder, is there a reason why 'kk delete cluster ...' does not delete all the required directories, why does it leave a lot of junk on the filesystem.

**Comment by FrankJingHao** [comment]
kubekey这波操作是真蠢

**Comment by FrankJingHao** [comment]
./kk delete cluster -y -f config-sample.yaml，重置解决问题
