### ISSUE TITLE
Upgrade kubernetes manually

### ISSUE THREAD

**Issue by showjason** [kubesphere/kubekey#1107]
OS info:
```
  CentOS 7.9
  4C/8G
```

kubekey version:
```
[root@localhost kubekey]# ./kk version
version.BuildInfo{Version:"1.2.1", GitCommit:"94aa580", GitTreeState:"", GoVersion:"go1.16.12"}
```
kubernetes version: v1.21.5

only one node act as master node and work node

I only install kubernets by kubekey, now I want to upgrade kuberentes to version v1.22.7 follow the [official guide](https://v1-22.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/).
However,  after `yum install -y kubeadm-1.22.7-0 --disableexcludes=kubernetes`,  `kubeadm version` still shows v1.21.5
<img width="807" alt="image" src="https://user-images.githubusercontent.com/27723125/156725215-1b9daead-6f9a-4977-b287-02068f540b3b.png">

What I want to know:
Kubernetes version must follow kubekey version if k8s was installed by kubekey or is there some wrong way I run caused this case? 

Wait for experts！

**Comment by 24sama** [comment]
The kubeadm installed by `yum` will be installed in the `/usr/bin/` and the kubeadm installed by kk will be installed in the `/usr/local/bin`.
You can use the absolute path to specify the kubeadm.
```
[root@node1 ~]# /usr/bin/kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:49:09Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by showjason** [comment]
@24sama Thanks! Is this in official document? If not, is it necessary to add this difference into doc to remind users who want to upgrade kubernetes manually?
