### ISSUE TITLE
Ubuntu 20.04 and CentOS 8.x support

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubekey#1108]
### Your current KubeKey version

[root@Ops-repo ~]# kk version version.BuildInfo{Version:"2.0.0-rc.4", GitCommit:"a337b297", GitTreeState:"", GoVersion:"go1.17.7"} [root@Ops-repo ~]# 

### Describe this feature

here not show support Ubuntu 20.04, i want know:
https://kubesphere.io/zh/docs/installing-on-linux/introduction/multioverview/

### Describe the solution you'd like

support Ubuntu 20.04

**Comment by 24sama** [comment]
Ubuntu 20.04 is supported. Please see the README.
