### ISSUE TITLE
kk2.0 unable to init cluster

### ISSUE THREAD

**Issue by jesserwen** [kubesphere/kubekey#1129]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"2.0.0", GitCommit:"ff9d30b7", GitTreeState:"", GoVersion:"go1.17.7"}

### What is your os environment?

Centos7.9

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 10.190.198.244, internalAddress: 10.190.198.244, user: root, password: "pass1234"}
  - {name: node2, address: 10.190.198.245, internalAddress: 10.190.198.245, user: root, password: "pass1234"}
  roleGroups:
    etcd:
    - node1
    control-plane:
    - node1
    worker:
    - node1
    - node2
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.5
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    plainHTTP: false
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

### A clear and concise description of what happend.

run command :
./kk-v2.0.0 create cluster -f config-sample.yaml

error message:
scp etcd certs file failed: get file stat failed: stat /tmp/kubekey/pki/etcd/ca-key.pem: no such file or directory
14:38:14 CST failed: [node1]
error: Pipeline[CreateClusterPipeline] execute failed: Module[CertsModule] exec failed:
failed: [node1] [SyncCertsFile] exec failed after 1 retires: scp etcd certs file failed: get file stat failed: stat /tmp/kubekey/pki/etcd/ca-key.pem: no such file or directory

### Relevant log output

```shell
[root@node1 tmp]# ./kk-v2.0.0 create cluster -f config-sample.yaml


 _   __      _          _   __
| | / /     | |        | | / /
| |/ / _   _| |__   ___| |/ /  ___ _   _
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

14:31:49 CST [NodePreCheckModule] A pre-check on nodes
14:31:51 CST success: [node2]
14:31:51 CST success: [node1]
14:31:51 CST [ConfirmModule] Display confirmation form
+-------+------+------+---------+----------+-------+-------+-----------+--------+----------+------------+-------------+------------------+--------------+
| name  | sudo | curl | openssl | ebtables | socat | ipset | conntrack | chrony | docker   | nfs client | ceph client | glusterfs client | time         |
+-------+------+------+---------+----------+-------+-------+-----------+--------+----------+------------+-------------+------------------+--------------+
| node1 | y    | y    | y       | y        | y     | y     | y         |        | 20.10.12 |            |             |                  | CST 14:31:51 |
| node2 | y    | y    | y       | y        | y     | y     | y         |        | 20.10.12 |            |             |                  | CST 14:31:51 |
+-------+------+------+---------+----------+-------+-------+-----------+--------+----------+------------+-------------+------------------+--------------+

This is a simple check of your environment.
Before installation, you should ensure that your machines meet all requirements specified at
https://github.com/kubesphere/kubekey#requirements-and-recommendations

Continue this installation? [yes/no]: yes
14:31:58 CST success: [LocalHost]
14:31:58 CST [NodeBinariesModule] Download installation binaries
14:31:58 CST message: [localhost]
downloading amd64 kubeadm v1.21.5 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 42.7M  100 42.7M    0     0  2474k      0  0:00:17  0:00:17 --:--:-- 2422k
14:32:16 CST message: [localhost]
downloading amd64 kubelet v1.21.5 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  112M  100  112M    0     0  1296k      0  0:01:29  0:01:29 --:--:-- 1962k
14:33:46 CST message: [localhost]
downloading amd64 kubectl v1.21.5 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.4M  100 44.4M    0     0   325k      0  0:02:19  0:02:19 --:--:--  489k
14:36:06 CST message: [localhost]
downloading amd64 helm v3.6.3 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.0M  100 13.0M    0     0  1968k      0  0:00:06  0:00:06 --:--:-- 2885k
14:36:13 CST message: [localhost]
downloading amd64 kubecni v0.9.1 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   671  100   671    0     0    472      0  0:00:01  0:00:01 --:--:--   472
100 37.9M  100 37.9M    0     0  2269k      0  0:00:17  0:00:17 --:--:-- 2955k
14:36:30 CST message: [localhost]
downloading amd64 docker 20.10.8 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 58.1M  100 58.1M    0     0  2838k      0  0:00:20  0:00:20 --:--:-- 3236k
14:36:52 CST message: [localhost]
downloading amd64 crictl v1.22.0 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   670  100   670    0     0    480      0  0:00:01  0:00:01 --:--:--   480
100 17.8M  100 17.8M    0     0  1759k      0  0:00:10  0:00:10 --:--:-- 3301k
14:37:02 CST message: [localhost]
downloading amd64 etcd v3.4.13 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   155  100   155    0     0    112      0  0:00:01  0:00:01 --:--:--   112
100   668  100   668    0     0    389      0  0:00:01  0:00:01 --:--:--  652k
100 16.5M  100 16.5M    0     0  1044k      0  0:00:16  0:00:16 --:--:-- 3231k
14:37:19 CST success: [LocalHost]
14:37:19 CST [ConfigureOSModule] Prepare to init OS
14:37:20 CST success: [node2]
14:37:20 CST success: [node1]
14:37:20 CST [ConfigureOSModule] Generate init os script
14:37:20 CST success: [node1]
14:37:20 CST success: [node2]
14:37:20 CST [ConfigureOSModule] Exec init os script
14:37:20 CST stdout: [node2]
Permissive
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
vm.swappiness = 1
fs.inotify.max_user_instances = 524288
kernel.pid_max = 65535
14:37:21 CST stdout: [node1]
setenforce: SELinux is disabled
Disabled
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
vm.swappiness = 1
fs.inotify.max_user_instances = 524288
kernel.pid_max = 65535
14:37:21 CST success: [node2]
14:37:21 CST success: [node1]
14:37:21 CST [ConfigureOSModule] configure the ntp server for each node
14:37:21 CST skipped: [node2]
14:37:21 CST skipped: [node1]
14:37:21 CST [KubernetesStatusModule] Get kubernetes cluster status
14:37:21 CST success: [node1]
14:37:21 CST [InstallContainerModule] Sync docker binaries
14:37:21 CST skipped: [node1]
14:37:21 CST skipped: [node2]
14:37:21 CST [InstallContainerModule] Generate containerd service
14:37:21 CST skipped: [node1]
14:37:21 CST skipped: [node2]
14:37:21 CST [InstallContainerModule] Enable containerd
14:37:21 CST skipped: [node1]
14:37:21 CST skipped: [node2]
14:37:21 CST [InstallContainerModule] Generate docker service
14:37:21 CST skipped: [node1]
14:37:21 CST skipped: [node2]
14:37:21 CST [InstallContainerModule] Generate docker config
14:37:21 CST skipped: [node1]
14:37:21 CST skipped: [node2]
14:37:21 CST [InstallContainerModule] Enable docker
14:37:21 CST skipped: [node1]
14:37:21 CST skipped: [node2]
14:37:21 CST [InstallContainerModule] Add auths to container runtime
14:37:21 CST skipped: [node1]
14:37:21 CST skipped: [node2]
14:37:21 CST [PullModule] Start to pull images on all nodes
14:37:21 CST message: [node2]
downloading image: kubesphere/pause:3.4.1
14:37:21 CST message: [node1]
downloading image: kubesphere/pause:3.4.1
14:37:26 CST message: [node2]
downloading image: kubesphere/kube-proxy:v1.21.5
14:37:26 CST message: [node1]
downloading image: kubesphere/kube-apiserver:v1.21.5
14:37:31 CST message: [node2]
downloading image: coredns/coredns:1.8.0
14:37:31 CST message: [node1]
downloading image: kubesphere/kube-controller-manager:v1.21.5
14:37:35 CST message: [node2]
downloading image: kubesphere/k8s-dns-node-cache:1.15.12
14:37:35 CST message: [node1]
downloading image: kubesphere/kube-scheduler:v1.21.5
14:37:40 CST message: [node2]
downloading image: calico/kube-controllers:v3.20.0
14:37:40 CST message: [node1]
downloading image: kubesphere/kube-proxy:v1.21.5
14:37:44 CST message: [node1]
downloading image: coredns/coredns:1.8.0
14:37:44 CST message: [node2]
downloading image: calico/cni:v3.20.0
14:37:49 CST message: [node1]
downloading image: kubesphere/k8s-dns-node-cache:1.15.12
14:37:49 CST message: [node2]
downloading image: calico/node:v3.20.0
14:37:54 CST message: [node1]
downloading image: calico/kube-controllers:v3.20.0
14:37:54 CST message: [node2]
downloading image: calico/pod2daemon-flexvol:v3.20.0
14:37:58 CST message: [node1]
downloading image: calico/cni:v3.20.0
14:38:03 CST message: [node1]
downloading image: calico/node:v3.20.0
14:38:08 CST message: [node1]
downloading image: calico/pod2daemon-flexvol:v3.20.0
14:38:12 CST success: [node2]
14:38:12 CST success: [node1]
14:38:12 CST [ETCDPreCheckModule] Get etcd status
14:38:12 CST success: [node1]
14:38:12 CST [CertsModule] Fetcd etcd certs
14:38:12 CST success: [node1]
14:38:12 CST [CertsModule] Generate etcd Certs
[certs] Generating "ca" certificate and key
[certs] admin-node1 serving cert is signed for DNS names [etcd etcd.kube-system etcd.kube-system.svc etcd.kube-system.svc.cluster.local lb.kubesphere.local localhost node1 node2] and IPs [127.0.0.1 ::1 10.190.198.244 10.190.198.245]
[certs] member-node1 serving cert is signed for DNS names [etcd etcd.kube-system etcd.kube-system.svc etcd.kube-system.svc.cluster.local lb.kubesphere.local localhost node1 node2] and IPs [127.0.0.1 ::1 10.190.198.244 10.190.198.245]
[certs] node-node1 serving cert is signed for DNS names [etcd etcd.kube-system etcd.kube-system.svc etcd.kube-system.svc.cluster.local lb.kubesphere.local localhost node1 node2] and IPs [127.0.0.1 ::1 10.190.198.244 10.190.198.245]
14:38:13 CST success: [LocalHost]
14:38:13 CST [CertsModule] Synchronize certs file
14:38:14 CST message: [node1]
scp etcd certs file failed: get file stat failed: stat /tmp/kubekey/pki/etcd/ca-key.pem: no such file or directory
14:38:14 CST failed: [node1]
error: Pipeline[CreateClusterPipeline] execute failed: Module[CertsModule] exec failed:
failed: [node1] [SyncCertsFile] exec failed after 1 retires: scp etcd certs file failed: get file stat failed: stat /tmp/kubekey/pki/etcd/ca-key.pem: no such file or directory
```

**Comment by 24sama** [comment]
You can use the command to check the result manually.
```
export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-node1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-node1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://10.190.198.244:2379/ cluster-health | grep -q 'cluster is healthy'
```
Or delete the cluster, then recreate it.
```
./kk-v2.0.0 delete cluster -f config-sample.yaml -y

./kk-v2.0.0 create cluster -f config-sample.yaml -y
```

**Comment by jesserwen** [comment]
@24sama  yes,  tried both ways, no luck still failed to create cluster.

same error:
18:41:17 CST message: [node1]
etcd health check failed: Failed to exec command: sudo -E /bin/bash -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-node1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-node1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://10.190.198.244:2379 cluster-health | grep -q 'cluster is healthy'"
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://10.190.198.244:2379 exceeded header timeout

error #0: client: endpoint https://10.190.198.244:2379 exceeded header timeout: Process exited with status 1
18:41:17 CST retry: [node1]
18:41:24 CST message: [node1]
etcd health check failed: Failed to exec command: sudo -E /bin/bash -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-node1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-node1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://10.190.198.244:2379 cluster-health | grep -q 'cluster is healthy'"
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://10.190.198.244:2379 exceeded header timeout

error #0: client: endpoint https://10.190.198.244:2379 exceeded header timeout: Process exited with status 1
18:41:24 CST retry: [node1]

**Comment by 24sama** [comment]
I found an issue that might be the same as your. Please see: https://github.com/kubesphere/kubekey/issues/1096

**Comment by jesserwen** [comment]
removed ./kubekey and tried to recreate cluster again, no luck, same above error.

21:10:59 CST success: [node1]
21:10:59 CST [ETCDPreCheckModule] Get etcd status
21:10:59 CST stdout: [node1]
ETCD_NAME=etcd-node1
21:10:59 CST success: [node1]
21:10:59 CST [CertsModule] Fetcd etcd certs
21:11:00 CST success: [node1]
21:11:00 CST [CertsModule] Generate etcd Certs
[certs] Using existing ca certificate authority
[certs] Using existing admin-node1 certificate and key on disk
[certs] Using existing member-node1 certificate and key on disk
[certs] Using existing node-node1 certificate and key on disk
21:11:00 CST success: [LocalHost]
21:11:00 CST [CertsModule] Synchronize certs file
21:11:02 CST success: [node1]
21:11:02 CST [CertsModule] Synchronize certs file to master
21:11:02 CST skipped: [node1]
21:11:02 CST [InstallETCDBinaryModule] Install etcd using binary
21:11:03 CST success: [node1]
21:11:03 CST [InstallETCDBinaryModule] Generate etcd service
21:11:03 CST success: [node1]
21:11:03 CST [InstallETCDBinaryModule] Generate access address
21:11:03 CST success: [node1]
21:11:03 CST [ETCDConfigureModule] Health check on exist etcd
21:11:05 CST message: [node1]
etcd health check failed: Failed to exec command: sudo -E /bin/bash -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-node1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-node1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://10.190.198.244:2379 cluster-health | grep -q 'cluster is healthy'"
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://10.190.198.244:2379 exceeded header timeout

error #0: client: endpoint https://10.190.198.244:2379 exceeded header timeout: Process exited with status 1
21:11:05 CST retry: [node1]
21:11:12 CST message: [node1]
etcd health check failed: Failed to exec command: sudo -E /bin/bash -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-node1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-node1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://10.190.198.244:2379 cluster-health | grep -q 'cluster is healthy'"
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://10.190.198.244:2379 exceeded header timeout

error #0: client: endpoint https://10.190.198.244:2379 exceeded header timeout: Process exited with status 1
21:11:12 CST retry: [node1]



[root@node1 kk-install]# systemctl status etcd
● etcd.service - etcd
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-03-14 18:41:15 CST; 2h 31min ago
 Main PID: 11952 (etcd)
   CGroup: /system.slice/etcd.service
           └─11952 /usr/local/bin/etcd

Mar 14 18:41:15 node1 etcd[11952]: raft2022/03/14 18:41:15 INFO: 52a10151f7b4904a became leader at term 2
Mar 14 18:41:15 node1 etcd[11952]: raft2022/03/14 18:41:15 INFO: raft.node: 52a10151f7b4904a elected leader 52a10151f7b4904a at term 2
Mar 14 18:41:15 node1 etcd[11952]: ready to serve client requests
Mar 14 18:41:15 node1 etcd[11952]: ready to serve client requests
Mar 14 18:41:15 node1 systemd[1]: Started etcd.
Mar 14 18:41:15 node1 etcd[11952]: setting up the initial cluster version to 3.4
Mar 14 18:41:15 node1 etcd[11952]: serving client requests on 10.190.198.244:2379
Mar 14 18:41:15 node1 etcd[11952]: set the initial cluster version to 3.4
Mar 14 18:41:15 node1 etcd[11952]: enabled capabilities for version 3.4
Mar 14 18:41:15 node1 etcd[11952]: serving client requests on 127.0.0.1:2379
Warning: etcd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
[root@node1 kk-install]#

**Comment by pixiake** [comment]
Are there firewalls or security groups between nodes?

**Comment by jesserwen** [comment]
I don't think so, node1 and node2 are in same LAN

[root@node1 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@node1 ~]# uname -a
Linux node1 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@node1 ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
[root@node1 ~]# firewall-cmd --state
not running
[root@node1 ~]#

**Comment by 24sama** [comment]
What does the following command report?

```
etcd health check failed: Failed to exec command: sudo -E /bin/bash -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-node1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-node1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://10.190.198.244:2379/ cluster-health
```

**Comment by jesserwen** [comment]
I have resolved this issue, it was caused proxy server was set.

The proxy server was required and used in packages downloading phase,  when all packages are there the proxy server could be unset for the rest of the kk installation phase, could you implement this feature to enhance the installation for the users who are in the office required to set proxy server for internet user case?

Thank you.

**Comment by 24sama** [comment]
At present, `kk` doesn't have a way to `phase run` steps, but maybe the kubekey artifact that is able to include binaries and images can help you. It is usually used to offline install a Kubernetes cluster.

See:
Chinese: https://github.com/kubesphere/kubekey/blob/master/docs/zh/manifest_and_artifact.md
English: https://github.com/kubesphere/kubekey/blob/master/docs/manifest_and_artifact.md

**Comment by jesserwen** [comment]
@24sama  thank you for the sharing, i will have a try for that, thank you.
