### ISSUE TITLE
kubekey use containerd show as UnknownVersion

### ISSUE THREAD

**Issue by vincenthe11** [kubesphere/kubekey#1130]
### What is version of KubeKey has the issue?

2.0

### What is your os environment?

Ubuntu 20.04

### A clear and concise description of what happend.

![image](https://user-images.githubusercontent.com/8400716/158540282-b42b22b8-6cff-4855-8e22-bc57148e7783.png)

**Comment by 24sama** [comment]
Fix: #1179
