### ISSUE TITLE
KK takes a long time to sync binaries and process exited with status 137 from signal KILL

### ISSUE THREAD

**Issue by javaXiaoHan** [kubesphere/kubekey#1140]
### What is version of KubeKey has the issue?

kubekey-v1.2.1-linux-amd64.tar

### What is your os environment?

CentOS 7.5 64位 8核 16 GiB

### KubeKey config file

```yaml
config is correct
```

### A clear and concise description of what happend.

when i excute ./kk create cluster -f config-sample.yaml
it shows
ERRO[15:58:53 CST] Failed to download image: dockerhub.kubekey.local/kubesphere/pause:3.4.1: Failed to exec command: sudo env PATH=$PATH docker pull dockerhub.kubekey.local/kubesphere/pause:3.4.1

### Relevant log output

```shell
[root@master1 kubesphere]# ./kk create cluster -f config-sample.yaml
+---------+------+------+---------+----------+-------+-------+-----------+----------+------------+-------------+------------------+--------------+
| name    | sudo | curl | openssl | ebtables | socat | ipset | conntrack | docker   | nfs client | ceph client | glusterfs client | time         |
+---------+------+------+---------+----------+-------+-------+-----------+----------+------------+-------------+------------------+--------------+
| node3   | y    | y    | y       | y        | y     | y     | y         | 20.10.8  |            |             |                  | CST 15:50:32 |
| master2 | y    | y    | y       | y        | y     | y     | y         | 20.10.8  |            |             |                  | CST 15:50:32 |
| master1 | y    | y    | y       | y        | y     | y     | y         |          |            |             |                  | CST 15:50:32 |
| node1   | y    | y    | y       | y        |       | y     | y         | 20.10.8  |            |             |                  | CST 15:50:32 |
| node2   | y    | y    | y       | y        | y     | y     | y         | 20.10.12 |            |             |                  | CST 15:50:31 |
| master3 | y    | y    | y       | y        |       | y     | y         | 20.10.8  |            |             |                  | CST 15:50:32 |
+---------+------+------+---------+----------+-------+-------+-----------+----------+------------+-------------+------------------+--------------+

This is a simple check of your environment.
Before installation, you should ensure that your machines meet all requirements specified at
https://github.com/kubesphere/kubekey#requirements-and-recommendations

Continue this installation? [yes/no]: yes
INFO[15:50:39 CST] Downloading Installation Files               
INFO[15:50:39 CST] Downloading kubeadm ...                      
INFO[15:50:39 CST] Downloading kubelet ...                      
INFO[15:50:39 CST] Downloading kubectl ...                      
INFO[15:50:39 CST] Downloading helm ...                         
INFO[15:50:40 CST] Downloading kubecni ...                      
INFO[15:50:40 CST] Downloading etcd ...                         
INFO[15:50:40 CST] Downloading docker ...                       
INFO[15:50:41 CST] Downloading crictl ...                       
INFO[15:50:41 CST] Configuring operating system ...             
[node3 116.12.17.12] MSG:
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
user.max_user_namespaces = 10000
[master1 101.51.126.37] MSG:
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
[node1 111.158.11.229] MSG:
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
user.max_user_namespaces = 10000
[node2 109.137.59.27] MSG:
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
user.max_user_namespaces = 10000
[master3 130.126.292.349] MSG:
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
user.max_user_namespaces = 10000
[master2 124.25.47.153] MSG:
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
user.max_user_namespaces = 10000
INFO[15:50:42 CST] Get cluster status                           
INFO[15:50:43 CST] Installing Container Runtime ...             
Push /mnt/kubesphere/kubekey/v1.21.5/amd64/docker-20.10.8.tgz to 21.71.256.137:/tmp/kubekey/docker-20.10.8.tgz   Done
INFO[15:58:22 CST] Start to download images on all nodes        
[node3] Downloading image: dockerhub.kubekey.local/kubesphere/pause:3.4.1
[master3] Downloading image: dockerhub.kubekey.local/kubesphere/pause:3.4.1
[master1] Downloading image: dockerhub.kubekey.local/kubesphere/pause:3.4.1
[node2] Downloading image: dockerhub.kubekey.local/kubesphere/pause:3.4.1
[master2] Downloading image: dockerhub.kubekey.local/kubesphere/pause:3.4.1
[node1] Downloading image: dockerhub.kubekey.local/kubesphere/pause:3.4.1
ERRO[15:58:53 CST] Failed to download image: dockerhub.kubekey.local/kubesphere/pause:3.4.1: Failed to exec command: sudo env PATH=$PATH docker pull dockerhub.kubekey.local/kubesphere/pause:3.4.1 
Error response from daemon: Get "https://dockerhub.kubekey.local/v2/": dial tcp: lookup dockerhub.kubekey.local on 100.100.2.138:53: no such host: Process exited with status 1  node=421.41.226.37
```

**Comment by 24sama** [comment]
Looks like node 121.41.226.37 doesn't know the domain "dockerhub.kubekey.local".

And I truly recommend you to use KubeKey v2.0.0 for offline installation.

Please see:
English: https://github.com/kubesphere/kubekey/blob/master/docs/manifest_and_artifact.md
Chinese: https://mp.weixin.qq.com/s/hjtNfSRVYH1O2o_dj6ET4A

**Comment by javaXiaoHan** [comment]
> Looks like node 121.41.226.37 doesn't know the domain "dockerhub.kubekey.local".
> 
> And I truly recommend you to use KubeKey v2.0.0 for offline installation.
> 
> Please see: English: https://github.com/kubesphere/kubekey/blob/master/docs/manifest_and_artifact.md Chinese: https://mp.weixin.qq.com/s/hjtNfSRVYH1O2o_dj6ET4A

172.16.121.102  master1.cluster.local master1
172.16.121.100  master2.cluster.local master2
172.16.121.98  master3.cluster.local master3
172.16.121.99  node1.cluster.local node1
172.16.121.101  node2.cluster.local node2
172.16.121.96  node3.cluster.local node3
114.55.100.64  lb.kubesphere.local
172.16.121.102  dockerhub.kubekey.local
here is the config
121.41.226.37  inner ip  is 172.16.121.102

**Comment by 24sama** [comment]
Is there a proxy server on the node?

**Comment by javaXiaoHan** [comment]
> Is there a proxy server on the node?

what do mean ？i don't understand

**Comment by javaXiaoHan** [comment]
> Is there a proxy server on the node?
 about 1 hour for
Installing Container Runtime ...

**Comment by 24sama** [comment]
> > Is there a proxy server on the node?
> > about 1 hour for
> > Installing Container Runtime ...

So, there are some problem about installing container runtime on the 121.41.226.37. Can you manualy install the docker and configure the docker? 
After that use the command for a test:
```
sudo env PATH=$PATH docker pull dockerhub.kubekey.local/kubesphere/pause:3.4.1
```

**Comment by javaXiaoHan** [comment]
i  have installed the docker just now ,
and now what  configuration i should config the docker

**Comment by javaXiaoHan** [comment]
> > > Is there a proxy server on the node?
> > > about 1 hour for
> > > Installing Container Runtime ...
> 
> So, there are some problem about installing container runtime on the 121.41.226.37. Can you manualy install the docker and configure the docker? After that use the command for a test:
> 
> ```
> sudo env PATH=$PATH docker pull dockerhub.kubekey.local/kubesphere/pause:3.4.1
> ```
> > > Is there a proxy server on the node?
> > > about 1 hour for
> > > Installing Container Runtime ...
> 
> So, there are some problem about installing container runtime on the 121.41.226.37. Can you manualy install the docker and configure the docker? After that use the command for a test:
> 
> ```
> sudo env PATH=$PATH docker pull dockerhub.kubekey.local/kubesphere/pause:3.4.1
> ```

https://kubesphere.io/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs/#%E8%8E%B7%E5%8F%96-installer
 
i follow this link to install the kubesphere . i take me one week, but it still not work

**Comment by javaXiaoHan** [comment]
Relevant log output
[root@master1 ks]# ./kk create cluster -f config-sample.yaml
+---------+------+------+---------+----------+-------+-------+-----------+----------+------------+-------------+------------------+--------------+
| name    | sudo | curl | openssl | ebtables | socat | ipset | conntrack | docker   | nfs client | ceph client | glusterfs client | time         |
+---------+------+------+---------+----------+-------+-------+-----------+----------+------------+-------------+------------------+--------------+
| master3 | y    | y    | y       | y        | y     | y     | y         |          |            |             |                  | CST 10:50:35 |
| node1   | y    | y    | y       | y        | y     | y     | y         |          |            |             |                  | CST 10:50:35 |
| node2   | y    | y    | y       | y        | y     | y     | y         |          |            |             |                  | CST 10:50:35 |
| master1 | y    | y    | y       | y        | y     | y     | y         | 20.10.13 |            |             |                  | CST 10:50:35 |
| node3   | y    | y    | y       | y        | y     | y     | y         |          |            |             |                  | CST 10:50:35 |
| master2 | y    | y    | y       | y        | y     | y     | y         |          |            |             |                  | CST 10:50:35 |
+---------+------+------+---------+----------+-------+-------+-----------+----------+------------+-------------+------------------+--------------+

This is a simple check of your environment.
Before installation, you should ensure that your machines meet all requirements specified at
https://github.com/kubesphere/kubekey#requirements-and-recommendations

Continue this installation? [yes/no]: yes
INFO[10:50:40 CST] Downloading Installation Files               
INFO[10:50:40 CST] Downloading kubeadm ...                      
INFO[10:50:40 CST] Downloading kubelet ...                      
INFO[10:50:41 CST] Downloading kubectl ...                      
INFO[10:50:41 CST] Downloading helm ...                         
INFO[10:50:41 CST] Downloading kubecni ...                      
INFO[10:50:41 CST] Downloading etcd ...                         
INFO[10:50:41 CST] Downloading docker ...                       
INFO[10:50:42 CST] Downloading crictl ...                       
INFO[10:50:42 CST] Configuring operating system ...             
[node3 116.62.177.162] MSG:
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
[master1 121.41.226.37] MSG:
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
[master2 114.55.247.153] MSG:
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
[master3 120.26.192.149] MSG:
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
[node2 101.37.89.27] MSG:
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
[node1 118.178.91.229] MSG:
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
INFO[10:50:43 CST] Get cluster status                           
INFO[10:50:43 CST] Installing Container Runtime ...

**Comment by 24sama** [comment]
Your problem is very strange. Can you use the KubeKey v2.0.0? That will show more logs.
This command can get the kk v2.0.0
```
curl -sfL https://get-kk.kubesphere.io | VERSION=v2.0.0 sh -
```

**Comment by javaXiaoHan** [comment]
> KubeKey v2.0.0

wo get the kk 2.0.0 
and now its
11:57:52 CST success: [node1]
11:57:52 CST success: [master2]
11:57:52 CST success: [node3]
11:57:52 CST success: [node2]
11:57:52 CST success: [master3]
11:57:52 CST success: [master1]
11:57:52 CST [ConfigureOSModule] configure the ntp server for each node
11:57:52 CST skipped: [node3]
11:57:52 CST skipped: [master1]
11:57:52 CST skipped: [master3]
11:57:52 CST skipped: [node1]
11:57:52 CST skipped: [master2]
11:57:52 CST skipped: [node2]
11:57:52 CST [KubernetesStatusModule] Get kubernetes cluster status
11:57:52 CST success: [master1]
11:57:52 CST success: [master2]
11:57:52 CST success: [master3]
11:57:52 CST [InstallContainerModule] Sync docker binaries
for a long time
does the kk config the docker automatic?

**Comment by 24sama** [comment]
kk will configure the docker automaticlly. That looks like there are something wrong about kk work node do a scp to other nodes. Or kk was hanged when kk checking other nodes' docker status.
Please use the command on other nodes:
```
which docker
systemctl status docker
```
You can uninstall the docker on these nodes if necessary.

**Comment by javaXiaoHan** [comment]
> kk will configure the docker automaticlly. That looks like there are something wrong about kk work node do a scp to other nodes. Or kk was hanged when kk checking other nodes' docker status. Please use the command on other nodes:
> 
> ```
> which docker
> systemctl status docker
> ```
> 
> You can uninstall the docker on these nodes if necessary.
 all nodes show 
[root@node2 ~]# which docker
/usr/bin/which: no docker in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
[root@node2 ~]# systemctl status docker
Unit docker.service could not be found.
[root@node2 ~]#

**Comment by javaXiaoHan** [comment]
all nodes and master are clean ecs
 just bought it  from alibaba

**Comment by 24sama** [comment]
That looks like there is no docker in your nodes? But the previous logs show all your nodes have a docker exist. It's strange. And i guess, If you are running kk outside this cluster (e.g. your local machine), then kk will copy the files over the Internet to the nodes in the cluster. That will take a long time.

**Comment by javaXiaoHan** [comment]
there are 6 ecs in a clster( 3 master 3 nodes)  they can ping from each other through inner net .
i  download kk in master1

**Comment by javaXiaoHan** [comment]
> That looks like there is no docker in your nodes? But the previous logs show all your nodes have a docker exist. It's strange. And i guess, If you are running kk outside this cluster (e.g. your local machine), then kk will copy the files over the Internet to the nodes in the cluster. That will take a long time.

there are 6 ecs in a clster( 3 master 3 nodes) they can ping from each other through inner net .
i download kk in master1

**Comment by 24sama** [comment]
Can you set the address and internalAddress of host in `kk config` to the internal network address (172.xxx.xxx.xx)?

**Comment by javaXiaoHan** [comment]
> 
you mean all address replace with its internalAddress？
hosts:
  - {name: master1, address: 121.51.236.37, internalAddress: 172.16.121.102, user: root, password: 123456}
  - {name: master2, address: 114.45.247.150, internalAddress: 172.16.121.100, user: root, password: 123456}
   like this?
  hosts:
  - {name: master1, address: 172.16.121.10, internalAddress: 172.16.121.102, user: root, password: 123456}
  - {name: master2, address: 172.16.121.100, internalAddress: 172.16.121.100, user: root, password: 123456}

**Comment by 24sama** [comment]
Yes, and put the `password` value in quotation marks
```
hosts:
    - {name: master, address: 172.16.121.102, internalAddress: 172.16.121.102, user: root, password: "123456"}
    - {name: master2, address: 172.16.121.100, internalAddress: 172.16.121.100, user: root, password: "123456"}
```

**Comment by javaXiaoHan** [comment]
> you mean all address replace with its internalAddress？ hosts:
> 
> * {name: master1, address: 121.51.236.37, internalAddress: 172.16.121.102, user: root, password: 123456}
> * {name: master2, address: 114.45.247.150, internalAddress: 172.16.121.100, user: root, password: 123456}
>   like this?
>   hosts:
> * {name: master1, address: 172.16.121.10, internalAddress: 172.16.121.102, user: root, password: 123456}
> * {name: master2, address: 172.16.121.100, internalAddress: 172.16.121.100, user: root, password: 123456}



> Can you set the `address` and `internalAddress` of host in `kk config` to the same internal network address (172.xxx.xxx.xx)? And to prevent additional problems, please put the `password` value in quotation marks Just like:
> 
> ```
> hosts:
>     - {name: master, address: 172.16.121.102, internalAddress: 172.16.121.102, user: root, password: "123456"}
>     - {name: master2, address: 172.16.121.100, internalAddress: 172.16.121.100, user: root, password: "123456"}
> you mean all address replace with its internalAddress？
hosts:

{name: master1, address: 121.51.236.37, internalAddress: 172.16.121.102, user: root, password: 123456}
{name: master2, address: 114.45.247.150, internalAddress: 172.16.121.100, user: root, password: 123456}
like this?
hosts:
{name: master1, address: 172.16.121.10, internalAddress: 172.16.121.102, user: root, password: 123456}
{name: master2, address: 172.16.121.100, internalAddress: 172.16.121.100, user: root, password: 123456}

**Comment by javaXiaoHan** [comment]
> Yes, and put the `password` value in quotation marks
> 
> ```
> hosts:
>     - {name: master, address: 172.16.121.102, internalAddress: 172.16.121.102, user: root, password: "123456"}
>     - {name: master2, address: 172.16.121.100, internalAddress: 172.16.121.100, user: root, password: "123456"}
> ```

you mean all address replace with its internalAddress？
hosts:

{name: master1, address: 121.51.236.37, internalAddress: 172.16.121.102, user: root, password: 123456}
{name: master2, address: 114.45.247.150, internalAddress: 172.16.121.100, user: root, password: 123456}
like this?
hosts:
{name: master1, address: 172.16.121.10, internalAddress: 172.16.121.102, user: root, password: 123456}
{name: master2, address: 172.16.121.100, internalAddress: 172.16.121.100, user: root, password: 123456}

**Comment by 24sama** [comment]
> > Yes, and put the `password` value in quotation marks
> > ```
> > hosts:
> >     - {name: master, address: 172.16.121.102, internalAddress: 172.16.121.102, user: root, password: "123456"}
> >     - {name: master2, address: 172.16.121.100, internalAddress: 172.16.121.100, user: root, password: "123456"}
> > ```
> 
> you mean all address replace with its internalAddress？ hosts:
> 
> {name: master1, address: 121.51.236.37, internalAddress: 172.16.121.102, user: root, password: 123456} {name: master2, address: 114.45.247.150, internalAddress: 172.16.121.100, user: root, password: 123456} like this? hosts: {name: master1, address: 172.16.121.10, internalAddress: 172.16.121.102, user: root, password: 123456} {name: master2, address: 172.16.121.100, internalAddress: 172.16.121.100, user: root, password: 123456}

yes

**Comment by javaXiaoHan** [comment]
> > > Yes, and put the `password` value in quotation marks
> > > ```
> > > hosts:
> > >     - {name: master, address: 172.16.121.102, internalAddress: 172.16.121.102, user: root, password: "123456"}
> > >     - {name: master2, address: 172.16.121.100, internalAddress: 172.16.121.100, user: root, password: "123456"}
> > > ```
> > 
> > 
> > you mean all address replace with its internalAddress？ hosts:
> > {name: master1, address: 121.51.236.37, internalAddress: 172.16.121.102, user: root, password: 123456} {name: master2, address: 114.45.247.150, internalAddress: 172.16.121.100, user: root, password: 123456} like this? hosts: {name: master1, address: 172.16.121.10, internalAddress: 172.16.121.102, user: root, password: 123456} {name: master2, address: 172.16.121.100, internalAddress: 172.16.121.100, user: root, password: 123456}
> 
> yes, and put the `password` value in quotation marks

ok thank you !!!!!!  i will try it now

**Comment by 24sama** [comment]
If there are some other problem, welcome to feedback.

**Comment by javaXiaoHan** [comment]
> If there are some other problems, welcome to feedback.

setenforce: SELinux is disabled
Disabled
vm.swappiness = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
kernel.sysrq = 1
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
vm.max_map_count = 262144
fs.inotify.max_user_instances = 524288
kernel.pid_max = 65535: Process exited with status 137 from signal KILL

do you know the reason?

**Comment by 24sama** [comment]
see https://stackoverflow.com/questions/43268156/process-finished-with-exit-code-137-in-pycharm

and make sure your linux kernel > 4.15

**Comment by javaXiaoHan** [comment]
> > see https://stackoverflow.com/questions/43268156/process-finished-with-exit-code-137-in-pycharm
> > Exit code 137 means that your process was killed by (signal 9) SIGKILL . In the case you manually stopped it.
> > If you didn't manually stop the script and still got this error code, then the script was killed by your OS. In most of the cases, it is caused by excessive memory usage.Q
> 
> Maybe you should disable `swap` and make sure your linux kernel version >= 4.15

**Comment by javaXiaoHan** [comment]
> > > see https://stackoverflow.com/questions/43268156/process-finished-with-exit-code-137-in-pycharm
> > > Exit code 137 means that your process was killed by (signal 9) SIGKILL . In the case you manually stopped it.
> > > If you didn't manually stop the script and still got this error code, then the script was killed by your OS. In most of the cases, it is caused by excessive memory usage.Q
> > 
> > 
> > Maybe you should disable `swap` and make sure your linux kernel version >= 4.15

you relly help me.thank you a lot!!!
i just disable swap, and i work.
i suggest the Official website should update the info about intall kubesphere (https://kubesphere.io/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs/#%E8%8E%B7%E5%8F%96-installer).
i think the reason is using kk v2.0.0  not 'curl -sfL https://get-kk.kubesphere.io | VERSION=v1.2.1 sh -'

**Comment by 24sama** [comment]
Yes, I already submit an issue to our official website project. We will fix it soon.
https://github.com/kubesphere/website/issues/2346

**Comment by javaXiaoHan** [comment]
@24sama i meet a starange problem.
my cluster is working now (3 master and 3 nodes)
now im going to add a new node(node4), i have disabled swap in node4 
but when i execute ./kk add nodes -f config-sample.yaml
it occurred a error 
kernel.pid_max = 65535: Process exited with status 137 from signal KILL
failed: [node3] [ExecScript] exec failed after 3 retires: Failed to configure operating system: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kube-scripts/initOS.sh" 
setenforce: SELinux is disabled

**Comment by javaXiaoHan** [comment]
i solve it 
firsttime  i just disable swap,and i build the cluater successly
but add another node is fail
then i try to update linux kernel version >= 4.15 ,and i work

**Comment by 24sama** [comment]
Good job! @javaXiaoHan 
This issue will be very helpful for future users who have the same problem.

**Comment by 24sama** [comment]
Feel free to reopen it.
/close
