### ISSUE TITLE
多集群节点haproxy模式怎么更改负载均衡ip

### ISSUE THREAD

**Issue by yuweni99** [kubesphere/kubekey#1143]
### Your current KubeKey version

v.1.2.1

### Describe this feature

请问一下，在已有的k8s集群，目前多节点是采用haproxy，怎么把haproxy更改成为负载均衡ip模式？

### Describe the solution you'd like

？

**Comment by pixiake** [comment]
If you have configured loadbalancer，you can try to modify the address corresponding to lb in `/etc/hosts`.
The apiserver addresse of all kubeconfig files in `/etc/kubernetes` on all master nodes also need to be checked.

**Comment by yuweni99** [comment]
这个我尝试过了，在现有集群上没有问题，如果是新添加集群节点后，我用kubekey添加节点并且采用负载均衡ip模式，发现网络插件calico无法安装，导致节点状态一直没有响应

**Comment by yuweni99** [comment]
> 如果你已经配置了负载均衡器，可以尝试修改 lb in 对应的地址`/etc/hosts`。还需要检查所有主节点上 所有 kubeconfig 文件的 apiserver 地址。`/etc/kubernetes`



> 如果你已经配置了负载均衡器，可以尝试修改 lb in 对应的地址`/etc/hosts`。还需要检查所有主节点上 所有 kubeconfig 文件的 apiserver 地址。`/etc/kubernetes`

这个我尝试过了，在现有集群上没有问题，如果是新添加集群节点后，我用kubekey添加节点并且采用负载均衡ip模式，发现网络插件calico无法安装，导致节点状态一直没有响应

**Comment by 24sama** [comment]
Can you paste some calico, kube-proxy, or kubelet logs on this website? I think these can help us to solve the problem.

**Comment by 24sama** [comment]
Yes, when the internal load balance is enabled, a haproxy will be deployed on the worker node and it will proxy all API servers which are on the master. And this node's kubelet, kube-proxy will listen to 127.0.0.1 and connect to the API server on master through the haproxy proxy.

**Comment by 24sama** [comment]
> 已经解决，发现使用kubekey通过haproxy的方式创建的话，kube-proxy的配置文件的api-server的地址为127.0.0.1，当我切换负载均衡ip的时候，把这里同步更改好就行了

I will close this issue. Feel free to reopen it.
