### ISSUE TITLE
kk2.0下载k8s文件存在重复下载

### ISSUE THREAD

**Issue by xrjk** [kubesphere/kubekey#1162]
### What is version of KubeKey has the issue?

v2.0.0

### What is your os environment?

centos

### A clear and concise description of what happend.

14:54:18 CST [NodeBinariesModule] Download installation binaries
14:54:18 CST message: [localhost]
downloading amd64 kubeadm v1.19.16 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 37.2M  100 37.2M    0     0   168k      0  0:03:45  0:03:45 --:--:--  159k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 37.2M  100 37.2M    0     0   119k      0  0:05:17  0:05:17 --:--:--  133k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 23 37.2M   23 8917k    0     0  19444      0  0:33:29  0:07:49  0:25:40  6811

**Comment by 24sama** [comment]
Hi @xrjk 
At present, kk doesn't support installing the k8s v1.19.16. Please see: https://github.com/kubesphere/kubekey/blob/master/docs/kubernetes-versions.md.

**Comment by 24sama** [comment]
This is not a bug, and I think this issue can be closed. Feel free to reopen it.
