### ISSUE TITLE
conntrack installed but still remind conntrack is required

### ISSUE THREAD

**Issue by Andyfeiyang** [kubesphere/kubekey#1167]
### What is version of KubeKey has the issue?

2.0.0

### What is your os environment?

centos7.9

### A clear and concise description of what happend.

i had installed **conntrack**  but pre-check on nodes still remind me **conntrack is required**

![1648790513(1)](https://user-images.githubusercontent.com/32694020/161199940-15f8ffce-eeec-45c2-b59f-c59589dc4915.png)

**Comment by 24sama** [comment]
`/usr/sbin` is for binaries with superuser (root) privileges required. The kk need the `conntrack` in the `/usr/bin` or `/usr/local/bin`.

**Comment by Andyfeiyang** [comment]
okay i see thank you very much! Recommend that you write the  **sudo tips** to the deployment document as most of the time, you don't have root permission，you know...

**Comment by 24sama** [comment]
To be honest, here is just a little mention in the README. And if you are interested in KubeKey, you are welcome to submit a PR to add some more detailed tips.

**Comment by Andyfeiyang** [comment]
okay,i will
