### ISSUE TITLE
Scaling member cluster removes the cluster configuration 

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#117]
I scale a member cluster from allinone to two-node cluster. The clusterRole becomes `none`. The host still shows the member but can't go into the cluster and keep logging the host console out.

**Comment by rayzhou2017** [comment]
Also the openebs seems crash.
<img width="904" alt="Screen Shot 2020-07-03 at 2 20 32 PM" src="https://user-images.githubusercontent.com/28859385/86438077-6cd5f180-bd38-11ea-8512-0f01b8e1056e.png">

**Comment by pixiake** [comment]
Install and scale had been separated，please try again.

**Comment by rayzhou2017** [comment]
verified
