### ISSUE TITLE
k3s artifact failed

### ISSUE THREAD

**Issue by hedongyouxia** [kubesphere/kubekey#1173]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"2.0.0", GitCommit:"ff9d30b7", GitTreeState:"", GoVersion:"go1.17.7"}

### What is your os environment?

Centos 7

### A clear and concise description of what happend.

when use export KKZONE=cn;some thing error:
downloading amd64 k3s v1.18.20 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   188  100   188    0     0    962      0 --:--:-- --:--:-- --:--:--   964
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   188  100   188    0     0    988      0 --:--:-- --:--:-- --:--:--   989
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   188  100   188    0     0   1119      0 --:--:-- --:--:-- --:--:--  1119
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   188  100   188    0     0    963      0 --:--:-- --:--:-- --:--:--   964
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   188  100   188    0     0   1155      0 --:--:-- --:--:-- --:--:--  1160
21:06:01 CST message: [LocalHost]
Failed to download k3s binary: curl -L -o /home/k3sup-install/kubekey/kube/v1.18.20/amd64/k3s https://kubernetes-release.pek3b.qingstor.com/k3s/releases/download/v1.18.20+k3s1/linux/amd64/k3s error: No SHA256 found for k3s. v1.18.20 is not supported. 
21:06:01 CST failed: [LocalHost]
error: Pipeline[K3sCreateClusterPipeline] execute failed: Module[K3sNodeBinariesModule] exec failed: 
failed: [LocalHost] [DownloadBinaries] exec failed after 1 retires: Failed to download k3s binary: curl -L -o /home/k3sup-install/kubekey/kube/v1.18.20/amd64/k3s https://kubernetes-release.pek3b.qingstor.com/k3s/releases/download/v1.18.20+k3s1/linux/amd64/k3s error: No SHA256 found for k3s. v1.18.20 is not supported.

but when not use export KKZONE=cn;it will download k3s all and don't continue to exec

I think it is necessary to detect whether the downloaded file has been included in the artifact. If it is included, it can be skipped to avoid repeated downloads all the time.

**Comment by 24sama** [comment]
I think this issue is duplicate https://github.com/kubesphere/kubekey/issues/1162

I will close this issue. Feel free to reopen it, if you have any other questions.
