### ISSUE TITLE
离线安装证书问题

### ISSUE THREAD

**Issue by ndkings3001** [kubesphere/kubekey#1214]
### What is version of KubeKey has the issue?

2.1.0

### What is your os environment?

centos7

### A clear and concise description of what happend.

![image](https://user-images.githubusercontent.com/103571380/163513988-99c9b69c-c1d3-49ed-96c7-74497a6d886c.png)
安装过程截图
![image](https://user-images.githubusercontent.com/103571380/163514011-da66f137-a4b9-4818-859f-db0b28c5c2e6.png)
报错截图！

正常在线安装没任何问题，离线安装就有问题

**Comment by 24sama** [comment]
Please ensure that all machines in the cluster are clocked synchronized.

You can use the KK to help you when installing the cluster:
```
system:
    ntpServers: #  The ntp servers of chrony, set the node name in `hosts` as ntp servers if no public ntp servers access.
      - node1 
```

See more: https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md

**Comment by ndkings3001** [comment]
![image](https://user-images.githubusercontent.com/103571380/163527671-ef6bc7c7-fd84-4dbb-9b76-4e7a95ba6fd7.png)
时间问题更正后，重新安装出现这个问题

**Comment by 24sama** [comment]
> ![image](https://user-images.githubusercontent.com/103571380/163527671-ef6bc7c7-fd84-4dbb-9b76-4e7a95ba6fd7.png)
> 时间问题更正后，重新安装出现这个问题

Please use the command to delete the cluster:
```
./kk delete cluster -f config.yaml
```
And then, recreate it.

**Comment by ndkings3001** [comment]
![image](https://user-images.githubusercontent.com/103571380/163528647-8d5b03a5-4cf4-4b35-8a53-1a6530300666.png)
![image](https://user-images.githubusercontent.com/103571380/163528658-aaeaa746-67e6-49d9-8b65-0b03071c55e3.png)
删除后重新创建问题依旧！

**Comment by 24sama** [comment]
> 

Try to remove this dir:
```
rm -rf ./kubekey/pki/
```

**Comment by ndkings3001** [comment]
找到问题了 因为前面装了一个 kubekey这个文件夹存在，我删除后，重新在创建他就执行过去了

**Comment by 24sama** [comment]
> 找到问题了 因为前面装了一个 kubekey这个文件夹存在，我删除后，重新在创建他就执行过去了

Good job!

**Comment by ndkings3001** [comment]
搞定了！ 谢谢！已经成功安装，想在咨询几个问题！
1. KK 自动安装docker的时候配置文件没有私服的地址，需要手动修改配置，把harbor的地址引用进去，这个没办法处理？ 
![image](https://user-images.githubusercontent.com/103571380/163531711-9251c316-1b1b-466a-a1a8-7692f335bd56.png)
2. KK 离线环境，我是自己安装的NTP服务器，KK会自动安装NTP服务么？

**Comment by 24sama** [comment]
1.
Configure the `insecureRegistries` field
```
  registry:
    registryMirrors: []
    insecureRegistries: []
    privateRegistry: ""
    namespaceOverride: ""
    auths: # if docker add by `docker login`, if containerd append to `/etc/containerd/config.toml`
      "dockerhub.kubekey.local":
        username: "xxx"
        password: "***"
```

2.
It requires `chrony` on each node. If your KubeKey artifact includes the operating system's ISO file, and then you create the cluster with `--with-packages` flag, the kk will install it automatically.
For example, there is a node named `master1` in the `hosts`, kk will set `master1` as the NTP server to allow other servers to synchronize their clocks.
```
system:
    ntpServers:
      - master1 
```

Please see: https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md
