### ISSUE TITLE
get-kk.kubesphere.io ssl cert has expired

### ISSUE THREAD

**Issue by polym** [kubesphere/kubekey#1221]
### What is version of KubeKey has the issue?

latest

### What is your os environment?

Centos7.2

### A clear and concise description of what happend.

I try kubesphere using kubekey to deploy it. But `curl -sfL https://get-kk.kubesphere.io | VERSION=v1.2.0 sh -` has not effect.  

`curl -sfL https://get-kk.kubesphere.io -v` returns the cert has expired.

### Relevant log output

```shell
curl -sfL https://get-kk.kubesphere.io -v
* About to connect() to get-kk.kubesphere.io port 443 (#0)
*   Trying 103.61.39.3...
* Connected to get-kk.kubesphere.io (103.61.39.3) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Server certificate:
*       subject: CN=get-kk.kubesphere.io
*       start date: Feb 28 07:14:14 2022 GMT
*       expire date: May 29 07:14:13 2022 GMT
*       common name: get-kk.kubesphere.io
*       issuer: CN=R3,O=Let's Encrypt,C=US
* NSS error -8162 (SEC_ERROR_EXPIRED_ISSUER_CERTIFICATE)
* The certificate issuer's certificate has expired.  Check your system date and time.
* Closing connection 0
```

**Comment by polym** [comment]
A tricky way, append -k to curl.

`curl -sfL https://get-kk.kubesphere.io -k | VERSION=v1.2.0 sh -`

**Comment by 24sama** [comment]
> The certificate issuer's certificate has expired.  Check your system date and time.

Maybe because of this?

It is useful for me to use this command.

**Comment by polym** [comment]
Sorry fo noise. `yum install ca-certificates` fix my problem.

/close
