### ISSUE TITLE
where is the rhel-7.6-amd64.iso? who can help me !

### ISSUE THREAD

**Issue by zyx19855** [kubesphere/kubekey#1227]
execute failed: Module[RepositoryModule] exec failed: 
failed: [node01] [SyncRepositoryISOFile] exec failed after 2 retires: scp /data/kk/kubekey/repository/amd64/rhel/7.6/rhel-7.6-amd64.iso to /tmp/kubekey/rhel-7.6-amd64.iso failed: get file stat failed: stat /data/kk/kubekey/repository/amd64/rhel/7.6/rhel-7.6-amd64.iso: no such file or directory
failed: [Master] [SyncRepositoryISOFile] exec failed after 2 retires: scp /data/kk/kubekey/repository/amd64/rhel/7.6/rhel-7.6-amd64.iso to /tmp/kubekey/rhel-7.6-amd64.iso failed: get file stat failed: stat /data/kk/kubekey/repository/amd64/rhel/7.6/rhel-7.6-amd64.iso: no such file or directory

**Comment by zyx19855** [comment]
> Hi @zyx19855 The kk 2.0 artifact doesn't support RHEL. Here is a issue: #1224 And I think this PR: #1222 can fix it.

OH ,thanks ! so which version of kk can support RHEL?

**Comment by zyx19855** [comment]
> 
thanks~

**Comment by 24sama** [comment]
Hi @zyx19855 
Can you paste your manifest file here? I'm not sure if the RHEL iso file is in your kubekey artifact.

**Comment by 24sama** [comment]
@zyx19855 The PR #1222 has been merged, you can have a try.

**Comment by 24sama** [comment]
Hi @zyx19855 
Is this issue fixed?

**Comment by 24sama** [comment]
The kubekey v2.1.0 has fixed this issue, so I will close the issue. If you have any other problems, feel free to reopen it.

**Comment by zyx19855** [comment]
> The kubekey v2.1.0 has fixed this issue, so I will close the issue. If you have any other problems, feel free to reopen it.

ok ,thakns alot~
