### ISSUE TITLE
kk-2.1.0-alpha.0   离线安装依然要访问外网

### ISSUE THREAD

**Issue by walt008** [kubesphere/kubekey#1244]
### What is version of KubeKey has the issue?

2.1.0-alpha.0

### What is your os environment?

centos7.9

### KubeKey config file

apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master1, address: 10.100.3.78, internalAddress: 10.100.3.78, user: root, privateKeyPath: "~/.ssh/id_rsa"}
  roleGroups:
    etcd:
    - master1
    control-plane: 
    - master1
    worker:
    - master1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    internalLoadbalancer: haproxy
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.19.9
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false

---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.2.1
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  zone: cn
  local_registry: "dockerhub.kubekey.local"
  namespace_override: "library"
  # dev_tag: ""
  etcd:
    monitoring: true
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    # apiserver:
    #  resources: {}
    # controllerManager:
    #  resources: {}
    redis:
      enabled: true
      volumeSize: 2Gi
    openldap:
      enabled: false
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      # type: external
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: true
    gpu:
      kinds:         
      - resourceName: "nvidia.com/gpu"
        resourceType: "GPU"
        default: true
    es:
      # master:
      #   volumeSize: 4Gi
      #   replicas: 1
      #   resources: {}
      # data:
      #   volumeSize: 20Gi
      #   replicas: 1
      #   resources: {}
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchHost: ""
      externalElasticsearchPort: ""
  alerting:
    enabled: false
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:
    enabled: false
    # operator:
    #   resources: {}
    # webhook:
    #   resources: {}
  devops:
    enabled: false
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: false
    # operator:
    #   resources: {}
    # exporter:
    #   resources: {}
    # ruler:
    #   enabled: true
    #   replicas: 2
    #   resources: {}
  logging:
    enabled: false
    containerruntime: docker
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:
    enabled: true
  monitoring:
    storageClass: ""
    # kube_rbac_proxy:
    #   resources: {}
    # kube_state_metrics:
    #   resources: {}
    # prometheus:
    #   replicas: 1
    #   volumeSize: 20Gi
    #   resources: {}
    #   operator:
    #     resources: {}
    #   adapter:
    #     resources: {}
    # node_exporter:
    #   resources: {}
    # alertmanager:
    #   replicas: 1
    #   resources: {}
    # notification_manager:
    #   resources: {}
    #   operator:
    #     resources: {}
    #   proxy:
    #     resources: {}
    gpu:
      nvidia_dcgm_exporter:
        enabled: true
        # resources: {}
  multicluster:
    clusterRole: none 
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: false
  servicemesh:
    enabled: false
  kubeedge:
    enabled: false   
    cloudCore:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      cloudhubPort: "10000"
      cloudhubQuicPort: "10001"
      cloudhubHttpsPort: "10002"
      cloudstreamPort: "10003"
      tunnelPort: "10004"
      cloudHub:
        advertiseAddress:
          - ""
        nodeLimit: "100"
      service:
        cloudhubNodePort: "30000"
        cloudhubQuicNodePort: "30001"
        cloudhubHttpsNodePort: "30002"
        cloudstreamNodePort: "30003"
        tunnelNodePort: "30004"
    edgeWatcher:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      edgeWatcherAgent:
        nodeSelector: {"node-role.kubernetes.io/worker": ""}
        tolerations: []

### A clear and concise description of what happend.

 ./kk create cluster -f config-sample.yaml -a kubekey-artifact.tar.gz 

报错如下
downloading image: kubesphere/pause:3.2
02:43:12 UTC message: [master1]
pull image failed: Failed to exec command: sudo -E /bin/bash -c "env PATH=$PATH docker pull kubesphere/pause:3.2" 

### Relevant log output

```shell
downloading image: kubesphere/pause:3.2
02:43:12 UTC message: [master1]
pull image failed: Failed to exec command: sudo -E /bin/bash -c "env PATH=$PATH docker pull kubesphere/pause:3.2" 
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:47289->[::1]:53: read: connection refused: Process exited with status 1
02:43:12 UTC retry: [master1]
02:43:17 UTC message: [master1]
downloading image: kubesphere/pause:3.2
02:43:17 UTC message: [master1]
pull image failed: Failed to exec command: sudo -E /bin/bash -c "env PATH=$PATH docker pull kubesphere/pause:3.2" 
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:53290->[::1]:53: read: connection refused: Process exited with status 1
02:43:17 UTC retry: [master1]
```

**Comment by 24sama** [comment]
Hi @walt008 
I guess your config file is like that:
```
auths: # if docker add by `docker login`, if containerd append to `/etc/containerd/config.toml`
      "registry-1.docker.io":
        username: "xxx"
        password: "***"
```
The "registry-1.docker.io" is just an example. Please change it to your private registry domain.

**Comment by walt008** [comment]
> 

我删掉了，如果我all-in-one  是否必须安装私有镜像仓库，单机镜像仓库使用4443端口 ，发现Metrics Server  也要监听这个端口 冲突了

**Comment by 24sama** [comment]
> > 
> 
> 我删掉了，如果我all-in-one 是否必须安装私有镜像仓库，单机镜像仓库使用4443端口 ，发现Metrics Server 也要监听这个端口 冲突了

Any k8s cluster requires an image registry.

**Comment by walt008** [comment]
OK
