### ISSUE TITLE
KK environment check add linux basic tools like tar

### ISSUE THREAD

**Issue by Dawnwangxiaoying** [kubesphere/kubekey#1247]
### Your current KubeKey version

v2.1.0-alpha.1

### Describe this feature

安装k8s&ks，KK节点环境检查，只检查了网络相关的必要组件，其实各节点还需要安装一下linux基础工具，例如：tar

### Describe the solution you'd like

KK前期检查能将节点安装，必要的基础组件也加入到检查中

**Comment by 24sama** [comment]
I will close this issue. If you have any other feedback, feel free to reopen it.

/close
