### ISSUE TITLE
unable validate kubesphere endpoint, non-200 response returned from endpoint

### ISSUE THREAD

**Issue by wanminny** [kubesphere/kubekey#125]
in the same network eg : 10.5.x.xx
and on the kube-sphere master can ping ip ok ; and  telnet this ip:6443 is ok
but unable validate kubesphere endpoint, non-200 response returned from endpoint.
thx

**Comment by wanminny** [comment]
this ip is that i want to add cluster's  server: https://ip:6443

**Comment by pixiake** [comment]
Is there a firewall between machines?

**Comment by wanminny** [comment]
> Is there a firewall between machines?

in the same network eg : 10.5.x.xx
and on the kube-sphere master can ping ip ok ; and telnet this ip:6443 is ok

**Comment by pixiake** [comment]
If you want to access the cluster using `ip:6443`, this ip should be included in the kube-apiserver's certificate.

**Comment by wanminny** [comment]
> If you want to access the cluster using `ip:6443`, this ip should be included in the kube-apiserver's certificate.

how to do ?

**Comment by Forest-L** [comment]
Have you resolved your issues, @wanminny  ? Please let me know if you have any other questions or close this issue.
