### ISSUE TITLE
Reinstall multi-node failed

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#127]
Delete cluster using  ./kk delete cluster. Then reinstall and failed
<img width="1217" alt="Screen Shot 2020-07-07 at 10 54 10 AM" src="https://user-images.githubusercontent.com/28859385/86696843-6ac5a880-c040-11ea-906f-2c59d9e2e49c.png">

**Comment by pixiake** [comment]
You can try  `./kk delete cluster` again.
This should be a coincidence. Let's check.

**Comment by rayzhou2017** [comment]
I think I know what is the root cause. It is a multi-node cluster, so I need to use `./kk delete cluster -f config.yaml`. The `./kk delete cluster` only cleans the local machine. Is it still a bug?

**Comment by pixiake** [comment]
remove multi-nodes need  to specify configuration file.
https://github.com/kubesphere/kubekey#delete-cluster
