### ISSUE TITLE
need ubuntu-22.04-debs-amd64.iso for offline install

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubekey#1281]
### Your current KubeKey version

2.1.0

### Describe this feature

need ubuntu-22.04-debs-amd64.iso for offline install

### Describe the solution you'd like

1、upload to github release
2、generate by user it self, but should know how to generate

**Comment by 24sama** [comment]
Hi @willzhang 
At present, I think this [hack](https://github.com/kubesphere/kubekey/tree/master/hack/gen-repository-iso) can help you.

**Comment by 24sama** [comment]
I think we can add a GitHub action(like ubuntu 2004, 1804) to generate this iso file automatically after the next release.

See: https://github.com/kubesphere/kubekey/tree/master/hack/gen-repository-iso
/good-first-issue

**Comment by 24sama** [comment]
Because there is this PR #1309 now, I think this issue can be closed.
