### ISSUE TITLE
detect wrong node name

### ISSUE THREAD

**Issue by chengleqi** [kubesphere/kubekey#1289]
### What is version of KubeKey has the issue?

2.0.0

### What is your os environment?

CentOS 7.6

### KubeKey config file

```yaml
None, I just use the default command `./kk create cluster --with-kubernetes v1.21.5 --with-kubesphere v3.2.1`
```

### A clear and concise description of what happend.

I tried to install kubesphere with all-in-one mode on my brand new CVM(tencentcloud virtual machine instance),when I run `./kk create cluster --with-kubernetes v1.21.5 --with-kubesphere v3.2.1`, I got the failed message `remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes VM-4-12-centos node-role.kubernetes.io/master=:NoSchedule-"`.

My node name is **vm**-4-12-centos which was generated automatically by tencentcloud,but the error message is "/usr/local/bin/kubectl taint nodes **VM**-4-12-centos node-role.kubernetes.io/master=:NoSchedule-" which **VM** is Uppercase,I thought maybe kubeeye detect wrong node name.

### Relevant log output

```shell
Error from server (NotFound): nodes "VM-4-12-centos" not found
20:35:24 CST message: [VM-4-12-centos]
remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes VM-4-12-centos node-role.kubernetes.io/master=:NoSchedule-"
Error from server (NotFound): nodes "VM-4-12-centos" not found: Process exited with status 1
20:35:24 CST retry: [VM-4-12-centos]
20:35:29 CST stdout: [VM-4-12-centos]
Error from server (NotFound): nodes "VM-4-12-centos" not found
20:35:29 CST message: [VM-4-12-centos]
remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes VM-4-12-centos node-role.kubernetes.io/master=:NoSchedule-"
Error from server (NotFound): nodes "VM-4-12-centos" not found: Process exited with status 1
20:35:29 CST retry: [VM-4-12-centos]
20:35:34 CST stdout: [VM-4-12-centos]
Error from server (NotFound): nodes "VM-4-12-centos" not found
20:35:34 CST message: [VM-4-12-centos]
remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes VM-4-12-centos node-role.kubernetes.io/master=:NoSchedule-"
Error from server (NotFound): nodes "VM-4-12-centos" not found: Process exited with status 1
20:35:34 CST retry: [VM-4-12-centos]
20:35:39 CST stdout: [VM-4-12-centos]
Error from server (NotFound): nodes "VM-4-12-centos" not found
20:35:39 CST message: [VM-4-12-centos]
remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes VM-4-12-centos node-role.kubernetes.io/master=:NoSchedule-"
Error from server (NotFound): nodes "VM-4-12-centos" not found: Process exited with status 1
20:35:39 CST retry: [VM-4-12-centos]
20:35:44 CST stdout: [VM-4-12-centos]
Error from server (NotFound): nodes "VM-4-12-centos" not found
20:35:44 CST message: [VM-4-12-centos]
remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes VM-4-12-centos node-role.kubernetes.io/master=:NoSchedule-"
Error from server (NotFound): nodes "VM-4-12-centos" not found: Process exited with status 1
20:35:44 CST failed: [VM-4-12-centos]
error: Pipeline[CreateClusterPipeline] execute failed: Module[InitKubernetesModule] exec failed:
failed: [VM-4-12-centos] [RemoveMasterTaint] exec failed after 5 retires: remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes VM-4-12-centos node-role.kubernetes.io/master=:NoSchedule-"
Error from server (NotFound): nodes "VM-4-12-centos" not found: Process exited with status 1
```

**Comment by chengleqi** [comment]
And when I run `/usr/local/bin/kubectl taint nodes **vm**-4-12-centos node-role.kubernetes.io/master=:NoSchedule-` manually (I change the node name from **VM**-4-12-centos to **vm**-4-12-centos), and run `./kk create cluster --with-kubernetes v1.21.5 --with-kubesphere v3.2.1` again, kubernetes and kubesphere successfully installed.

**Comment by 24sama** [comment]
> And when I run `/usr/local/bin/kubectl taint nodes **vm**-4-12-centos node-role.kubernetes.io/master=:NoSchedule-` manually (I change the node name from **VM**-4-12-centos to **vm**-4-12-centos), and run `./kk create cluster --with-kubernetes v1.21.5 --with-kubesphere v3.2.1` again, kubernetes and kubesphere successfully installed.

Hi @chengleqi 
That is caused by k8s doesn't allow uppercase words as a resource name.
