### ISSUE TITLE
Support Kubernetes v1.24.1 and other new versions

### ISSUE THREAD

**Issue by brandan-schmitz** [kubesphere/kubekey#1306]
### Your current KubeKey version

v2.1.1

### Describe this feature

Kubernetes recently released a new round of updates on May 24th, 2022:

- v1.21.13
- v1.22.10
- v1.23.7
- v1.24.1

### Describe the solution you'd like

Add the ability to use these versions with the --with-kubernetes flag. Currently they cannot be used as the sha256 checksum and version is not in the application.

**Comment by 24sama** [comment]
Hi @brandan-schmitz , thanks for your feedback!
Support more Kubernetes versions are very necessary.
I think this fits as a "good-first-issue" so if you're interested in fixing it, please let me know.

/good-first-issue

**Comment by brandan-schmitz** [comment]
@24sama I would be be willing to work on this, what is the process that has been used for obtaining the checksum currently used in the project? I compared some of them to the checksums listed at https://www.downloadkubernetes.com/ (linked in the official k8s documentation) however they do not seem to match.

I also see that currently it pulls from a google storage account, however when I go to the links as I would expect them to be based on the contents of `pkg/files/file.go` it is unable to locate the files.

**Comment by 24sama** [comment]
Hi @brandan-schmitz
For now, kk need to add the `sha256` into `pkg/files/file.go`, it's really not elegant and flexible.
So we need to increase this map
https://github.com/kubesphere/kubekey/blob/b19724c728154af81d5e2daa5e28808e07b877c1/pkg/files/file.go#L304

And I think you can get the `sha256` checksum by the following link, this comes from the official doc: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

Example:
```
# amd64
https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/amd64/kubectl.sha256
https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/amd64/kubelet.sha256
https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/amd64/kubeadm.sha256

# arm64
https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/arm64/kubectl.sha256
https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/arm64/kubelet.sha256
https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/arm64/kubeadm.sha256
```

After that we need to add some new elements to this array and the docs:
https://github.com/kubesphere/kubekey/blob/b19724c728154af81d5e2daa5e28808e07b877c1/pkg/version/kubernetes/version_enum.go#L90

https://github.com/kubesphere/kubekey/blob/master/docs/kubernetes-versions.md

**Comment by brandan-schmitz** [comment]
@24sama I have created a PR that adds all the versions of Kubernetes that were missing starting with version 1.21.0 as that is the oldest currently supported version. The PR has been linked to this issue.
