### ISSUE TITLE
install error when use nfs storageClass

### ISSUE THREAD

**Issue by hawking-lab** [kubesphere/kubekey#133]
[node1 10.57.200.183] MSG:
podsecuritypolicy.policy/psp.flannel.unprivileged configured
clusterrole.rbac.authorization.k8s.io/flannel unchanged
clusterrolebinding.rbac.authorization.k8s.io/flannel unchanged
serviceaccount/flannel unchanged
configmap/kube-flannel-cfg unchanged
daemonset.apps/kube-flannel-ds-amd64 unchanged
daemonset.apps/kube-flannel-ds-arm64 unchanged
daemonset.apps/kube-flannel-ds-arm unchanged
daemonset.apps/kube-flannel-ds-ppc64le unchanged
daemonset.apps/kube-flannel-ds-s390x unchanged
INFO[14:06:07 CST] Joining nodes to cluster                     
INFO[14:06:27 CST] Start to download images on all nodes (storage) 
[node2] Downloading image: kubesphere/nfs-client-provisioner:v3.1.0-k8s1.11
[node1] Downloading image: kubesphere/nfs-client-provisioner:v3.1.0-k8s1.11
INFO[14:06:51 CST] Deploying storage plugin ...                 
[node1 10.57.200.183] Retrying ...
[node1 10.57.200.183] Retrying ...
[node1 10.57.200.183] Retrying ...
ERRO[14:08:27 CST] Failed to fetch nfs-client-provisioner chart: Failed to exec command: sudo -E /bin/sh -c "rm -rf /etc/kubernetes/addons/nfs-client-provisioner && /usr/local/bin/helm fetch kubesphere/nfs-client-provisioner -d /etc/kubernetes/addons --untar" 
Error: repo kubesphere not found: Process exited with status 1  node=10.57.200.183
WARN[14:08:27 CST] Task failed ...                              
WARN[14:08:27 CST] error: interrupted by error                  
Error: Failed to deploy storage plugin: interrupted by error
Usage:
  kk create cluster [flags]

Flags:
  -f, --file string              Path to a configuration file
  -h, --help                     help for cluster
      --with-kubernetes string   Specify a supported version of kubernetes (default "v1.17.8")
      --with-kubesphere          Deploy a specific version of kubesphere (default v3.0.0)

**Comment by pixiake** [comment]
You can try to build binary from the latest source code，and try again.

**Comment by hawking-lab** [comment]
I found the reason, because nfs-provisioner uses the helm scheme for installation, but the helm command does not configure the agent. Can the installation of nfs-provisioner be replaced with offline installation using yaml files?
![image](https://user-images.githubusercontent.com/47567011/88031272-ec542500-cb6e-11ea-9e4e-fe9a28ab4179.png)

**Comment by Forest-L** [comment]
Have you resolved your issues, @hawking-lab  ? Please let me know if you have any other questions or close this issue.
