### ISSUE TITLE
calico network plugin  status unavailable

### ISSUE THREAD

**Issue by hawking-lab** [kubesphere/kubekey#134]
Warning  Unhealthy  102s  kubelet, node1     Readiness probe failed: 2020-07-08 05:42:57.392 [INFO][226] confd/health.go 177: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 172.17.0.1
  Warning  Unhealthy  92s  kubelet, node1  Readiness probe failed: 2020-07-08 05:43:07.377 [INFO][266] confd/health.go 177: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 172.17.0.1
  Warning  Unhealthy  82s  kubelet, node1  Readiness probe failed: 2020-07-08 05:43:17.383 [INFO][306] confd/health.go 177: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 172.17.0.1
  Warning  Unhealthy  72s  kubelet, node1  Readiness probe failed: 2020-07-08 05:43:27.386 [INFO][338] confd/health.go 177: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 172.17.0.1
  Warning  Unhealthy  62s  kubelet, node1  Readiness probe failed: 2020-07-08 05:43:37.385 [INFO][371] confd/health.go 177: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 172.17.0.1
  Warning  Unhealthy  52s  kubelet, node1  Readiness probe failed: 2020-07-08 05:43:47.378 [INFO][408] confd/health.go 177: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 172.17.0.1
  Warning  Unhealthy  42s  kubelet, node1  Readiness probe failed: 2020-07-08 05:43:57.379 [INFO][440] confd/health.go 177: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 172.17.0.1
  Warning  Unhealthy  32s  kubelet, node1  Readiness probe failed: 2020-07-08 05:44:07.384 [INFO][474] confd/health.go 177: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 172.17.0.1
  Warning  Unhealthy  22s  kubelet, node1  Readiness probe failed: 2020-07-08 05:44:17.381 [INFO][507] confd/health.go 177: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 172.17.0.1
  Warning  Unhealthy  2s (x2 over 12s)  kubelet, node1  (combined from similar events): Readiness probe failed: 2020-07-08 05:44:37.380 [INFO][570] confd/health.go 177: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 172.17.0.1

**Comment by pixiake** [comment]
https://stackoverflow.com/questions/54465963/calico-node-is-not-ready-bird-is-not-ready-bgp-not-established
