### ISSUE TITLE
gpu安装

### ISSUE THREAD

**Issue by liushaobo05** [kubesphere/kubekey#1353]
能支持英伟达gpu的安装么

**Comment by 24sama** [comment]
Hi @liushaobo05 , for now, kk doesn't support installing GPU drivers. Please prepare it manually.

**Comment by bizy01** [comment]
有kubekey的微信群么

**Comment by 24sama** [comment]
> > Hi @liushaobo05 , for now, kk doesn't support installing GPU drivers because it's not a very common feature-request. Please prepare it manually. If you have any ideas or solutions, welcome to discuss them with us or leave some comments here.
> 
> 有kubekey的微信交流群么

可以微信搜索小程序 KubeSphere云原生，点击菜单栏中的 加入社区-》加入社群
