### ISSUE TITLE
Support for deploying k8e

### ISSUE THREAD

**Issue by xiaods** [kubesphere/kubekey#1359]
### Describe this feature

k8e native support install enterprise environment 

[Kubernetes Easy (k8e)](https://getk8e.com/) is a lightweight, Extensible, Enterprise Kubernetes distribution that allows users to uniformly manage, secure, and get out-of-the-box kubernetes cluster for enterprise environments.

The k8e 🚀 (said 'kuber easy') project builds on upstream project [K3s](https://github.com/rancher/k3s) as codebase, remove Edge/IoT features and extend enterprise features with best practices.

### Describe the solution you'd like

use kubekey install k8e cluster.

**Comment by 24sama** [comment]
Hi @xiaods, very happy to learn about k8e!
Would you like to join our online sig meeting and discuss this agenda?


```
Meeting Time: 2022/07/07 16:00-17:00 (GMT+08:00) China Standard Time - Beijing
Recurrence: 2022/06/23-2022/09/15 16:00-17:00, Biweekly on Thursday

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/VP3lmqghjrhy

#TencentMeeting：742-8114-5907

One tap mobile
+8675536550000,,74281145907# (Chinese mainland)
+85230018898,,,2,74281145907# (Hong Kong, China)

Dial by your location
+8675536550000 (Chinese mainland)
+85230018898 (Hong Kong, China)

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting
```

**Comment by xiaods** [comment]
I have a meeting conflict and cannot attend your scheduled web meeting.

**Comment by 24sama** [comment]
> I have a meeting conflict and cannot attend your scheduled web meeting.

OK, maybe next biweekly meeting?

**Comment by xiaods** [comment]
> > I have a meeting conflict and cannot attend your scheduled web meeting.
> 
> OK, maybe next biweekly meeting?

OK

**Comment by xiaods** [comment]
I found kk already support k3s. k8e codebase is fork from k3s. so it will streamly support k8e

**Comment by xiaods** [comment]
@24sama  I will provide a PR to support this feature of installing k8e clusters

**Comment by 24sama** [comment]
Thanks, @xiaods , that's gonna be very cool. I'm waiting for your PR.

**Comment by xiaods** [comment]
@24sama  welcome codereview and comments. I let k8e only one version at once. this is LTS term.
for k8e, now only support 1.21.x upstream.
testing work like a charm:
create cluster:
./bin/linux/amd64/kk create cluster --with-kubernetes v1.21.14-k8e
delete cluster:
./bin/linux/amd64/kk delete cluster --with-kubernetes v1.21.14-k8e
testing on AWS Linux OS

**Comment by xiaods** [comment]
https://github.com/kubesphere/kubekey/pull/1452

**Comment by xiaods** [comment]
thanks @24sama support. I will share my experience on next meeting call.
