### ISSUE TITLE
Support version number without v

### ISSUE THREAD

**Issue by pixiake** [kubesphere/kubekey#1365]
### Describe this feature

At present, kk only supports version numbers with `v` , such as v1.22.10. Version numbers without `v` should also be supported.

I found that both method of kubeadm are supported.
```
kubeadm init --kubernetes-version 1.22.10
kubeadm init --kubernetes-version v1.22.10
```

### Describe the solution you'd like

Modify the parameter validate logic to support the version number without `v`.

**Comment by deepto98** [comment]
Can I pick this up?

**Comment by 24sama** [comment]
Hi @deepto98 welcome!

I guess adding a function to return a normalized build version in the `Loader` can solve this issue.
https://github.com/kubesphere/kubekey/blob/7c1a74ad651e24aa6e9fa53e4cc5e90719232386/pkg/common/loader.go#L46

Here are some ref links for you:
https://github.com/kubernetes/kubernetes/blob/89aaf7c02dd33415ac994cecfddca7c02ed75834/cmd/kubeadm/app/util/version.go#L152

**Comment by mangoGoForward** [comment]
Hi @deepto98 , Do you already processing on this issue?
I'd like also to work on it~
