### ISSUE TITLE
How to migrate  etcd cluster to outside

### ISSUE THREAD

**Issue by zj452008181** [kubesphere/kubekey#1372]
### Your current KubeKey version

2.2.0

### Describe this feature

my etcd  cluster was install on master node by kk，now i want to migrate  etcd cluster to outside，how to use kk to do this

### Describe the solution you'd like

i change config.yaml,add etcd nodes info and edit roleGroups.etcd[master1,master2,master3] to  roleGroups.etcd[etcd1,etcd2,etcd3],then i used kk add nodes -f config.yaml,after a few seconds，i get the errors：

[certs] certificate node-master1 not signed by CA certificate ca: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "etcd-ca")

**Comment by 24sama** [comment]
Hi @zj452008181 
KK does not support migrating the etcd cluster. Please do it manually.
