### ISSUE TITLE
os2022:first step of update_cluster phase run  

### ISSUE THREAD

**Issue by 77yu77** [kubesphere/kubekey#1373]
### Your current KubeKey version

latest+unreleased

### Describe this feature

For the pipeline of update_cluster,kk should have phase run support to reduce losses from duplicate implementations.

### Describe the solution you'd like

Phase run means we should divide the origin pipeline into several parts, and the first step is to pre-check the nodes and cluster. If needed, it should have a new modules first to set the configs in the pipelinecache.

**Comment by 24sama** [comment]
Looks good to me!
/assign @77yu77
