### ISSUE TITLE
upload kubeadmin v1.22.11/v1.24.2 to kubernetes-release.pek3b.qingstor.com

### ISSUE THREAD

**Issue by yjqg6666** [kubesphere/kubekey#1377]
### What is version of KubeKey has the issue?

v2.2.1

### What is your os environment?

Ubuntu 20.04

### KubeKey config file

```yaml
./kubekey-v2.2.1 create config --with-kubernetes v1.22.11 --with-kubesphere v3.3.0
```

### A clear and concise description of what happend.

kubeadm can NOT be download from CN kkzone.

### Relevant log output

```shell
08:22:20 UTC message: [LocalHost]
Failed to download kubeadm binary: curl -L -o /home/user/deploy/kubekey/kube/v1.22.11/amd64/kubeadm https://kubernetes-release.pek3b.qingstor.com/release/v1.22.11/bin/linux/amd64/kubeadm error: No SHA256 found for kubeadm. v1.22.11 is not supported.
08:22:20 UTC failed: [LocalHost]
error: Pipeline[CreateClusterPipeline] execute failed: Module[NodeBinariesModule] exec failed:
failed: [LocalHost] [DownloadBinaries] exec failed after 1 retires: Failed to download kubeadm binary: curl -L -o /home/user/deploy/kubekey/kube/v1.22.11/amd64/kubeadm https://kubernetes-release.pek3b.qingstor.com/release/v1.22.11/bin/linux/amd64/kubeadm error: No SHA256 found for kubeadm. v1.22.11 is not supported.
```

### Additional information

![image](https://user-images.githubusercontent.com/1879641/178938309-3f04c867-a650-4da7-9a02-cf9dde7954b9.png)
![image](https://user-images.githubusercontent.com/1879641/178938370-372ae1ca-a1ff-49af-8b3f-6212b581fda9.png)

The v1.24.2 version is also unavailable. kubeadmin/kubelet/kubectl files are needed.

**Comment by 24sama** [comment]
The versions v1.22.11and v1.24.2 is not supported. Here is the support list:https://github.com/kubesphere/kubekey/blob/master/docs/kubernetes-versions.md

We will support it in the next kk version.
And if you're interested in supporting it, please let me know.
Ref: https://github.com/kubesphere/kubekey/issues/1306

/kind good-first-issue

**Comment by yjqg6666** [comment]
@24sama How about put [a link](https://github.com/kubesphere/kubekey/blob/master/docs/kubernetes-versions.md) on the repo root README file?

**Comment by yjqg6666** [comment]
The two are not in sync. The readme file , v1.22 up to v1.22.9, while the other one up to v1.22.10. I would suggest to change:
"Kubernetes Versions" -> "Supported Kubernetes Versions" 
v1.22: v1.22.0 ~ v1.22.10

**Comment by 24sama** [comment]
Wow, that is also a document issue. Would you be interested in fixing it?

**Comment by yjqg6666** [comment]
@24sama I made a PR #1384 fixing it.
