### ISSUE TITLE
是否支持普通用户安装

### ISSUE THREAD

**Issue by Phoebus888** [kubesphere/kubekey#1385]
### Describe this feature

2.0.0

### Describe the solution you'd like

是否支持普通用户安装

**Comment by 24sama** [comment]
Yes, kk supported it. But it required the normal user has `sudo` privilage.
You can use the kk config file, and configure the normal user in the `hosts` field.

**Comment by cubxxw** [comment]
@24sama  Is it supported rootless? 
> 
If sudo, how to configure hosts? Is there any documentation?
>
