### ISSUE TITLE
kubekey artifact export failed when non-standard ssh port is used.

### ISSUE THREAD

**Issue by yjqg6666** [kubesphere/kubekey#1387]
### What is version of KubeKey has the issue?

v2.2.1

### What is your os environment?

Ubuntu 20.04 LTS

### KubeKey config file

```yaml
./kubekey-v2.2.1 artifact export -m manifest-sample.yaml -o ks.tar.gz
```

### A clear and concise description of what happend.

When ssh non-standard port is used, the export would fail. How could i specify/config the ssh port other than 22?

### Relevant log output

```shell
02:07:17 UTC [GreetingsModule] Greetings
02:07:17 UTC failed: [node1]
error: Pipeline[ArtifactExportPipeline] execute failed: Module[GreetingsModule] exec failed:
failed: [node1] failed to connect to <all-in-one-host-ip>: could not establish connection to <all-in-one-host-ip>:22: dial tcp <all-in-one-host-ip>:22: connect: connection refused
```

**Comment by 24sama** [comment]
/kind bug

The `artifact export` command needs to remove the `GreetingsModule` due to it doesn't need to use the SSH connection.

**Comment by VladimirCores** [comment]
Still have the error related to `GreetingsModule` when run `./kk create cluster --with-kubernetes v1.22.12 --with-kubesphere v3.3.2`

```
error: Pipeline[CreateClusterPipeline] execute failed: Module[GreetingsModule] exec failed: 
failed: [localhost.localdomain] failed to connect to 192.168.124.121: could not establish connection to 192.168.124.121:22: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by guojianyu** [comment]
> Still have the error related to `GreetingsModule` when run `./kk create cluster --with-kubernetes v1.22.12 --with-kubesphere v3.3.2`
> 
> ```
> error: Pipeline[CreateClusterPipeline] execute failed: Module[GreetingsModule] exec failed: 
> failed: [localhost.localdomain] failed to connect to 192.168.124.121: could not establish connection to 192.168.124.121:22: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
> ```
you can try:

1:
vim /etc/ssh/sshd_config
2:
PermitRootLogin  yes
RSAAuthentication yes
PubkeyAuthentication yes
3: 
systemctl restart sshd.service
