### ISSUE TITLE
Ubuntu multi nodes install failed

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#14]
hosts:
  - {name: master1, address: 192.168.100.2, internalAddress: 192.168.100.2, user: ubuntu, password: xxxx}
  - {name: master2, address: 192.168.100.3, internalAddress: 192.168.100.3, user: ubuntu, password: xxxxx}
  - {name: master3, address: 192.168.100.4, internalAddress: 192.168.100.4, user: ubuntu, password: xxxxx}
  - {name: node1, address: 192.168.100.5, internalAddress: 192.168.100.5, user: ubuntu, password: xxxxx}
  - {name: node2, address: 192.168.100.9, internalAddress: 192.168.100.9, user: ubuntu, password: xxxx}
  - {name: node3, address: 192.168.100.10, internalAddress: 192.168.100.10, user: ubuntu, password: xxxx}

**The error is:**

INFO[03:31:48 UTC] Generating etcd certs
ERRO[03:31:49 UTC] Failed to write etcd certs content: Failed to exec command: sudo -E /bin/sh -c “echo cat: /etc/ssl/etcd/ssl/ca-key.pem: Permission denied | base64 -d > /etc/ssl/etcd/ssl/ca-key.pem”: Process exited with status 1  node=192.168.100.4
ERRO[03:31:49 UTC] Failed to write etcd certs content: Failed to exec command: sudo -E /bin/sh -c “echo cat: /etc/ssl/etcd/ssl/admin-master1-key.pem: Permission denied | base64 -d > /etc/ssl/etcd/ssl/admin-master1-key.pem”: Process exited with status 1  node=192.168.100.3

**Comment by pixiake** [comment]
This will only happen with ubuntu18.04. I have escalated execution permission, please try it again.

**Comment by rayzhou2017** [comment]
Still failed.

net.ipv4.ip_local_reserved_ports = 30000-32767
INFO[14:27:44 UTC] Installing docker ...
ERRO[14:27:49 UTC] Failed to install docker: Failed to exec command: sudo -E /bin/sh -c "if [ -z $(which docker) ]; then curl https://kubernetes.pek3b.qingstor.com/tools/kubekey/docker-install.sh | sh && systemctl enable docker && echo ewogICJsb2ctb3B0cyI6IHsKICAgICJtYXgtc2l6ZSI6ICI1bSIsCiAgICAibWF4LWZpbGUiOiIzIgogIH0sCiAgImV4ZWMtb3B0cyI6IFsibmF0aXZlLmNncm91cGRyaXZlcj1zeXN0ZW1kIl0KfQo= | base64 -d > /etc/docker/daemon.json && systemctl reload docker; fi": Process exited with status 100  node=192.168.100.2

**Comment by pixiake** [comment]
Newly created ubuntu18.04 on the public cloud, its APT is occupied and it takes about ten minutes for it to work.
The following commands can be executed to check if the APT is occupied.
`ps -ef | grep apt`

**Comment by rayzhou2017** [comment]
verified
