### ISSUE TITLE
support recent k8s patch versions

### ISSUE THREAD

**Issue by yjqg6666** [kubesphere/kubekey#1406]
### What is version of KubeKey has the issue?

v2.2.2

### What is your os environment?

Ubuntu 22.04 LTS

**Comment by yjqg6666** [comment]
@24sama Is there any github actions to upload k8s binary files (kubeadm/kubelet/kubectl) ?  The url https://kubernetes-release.pek3b.qingstor.com/release/v1.22.12/bin/linux/amd64/kubeadm still get 404.

**Comment by 24sama** [comment]
> @24sama Is there any github actions to upload k8s binary files (kubeadm/kubelet/kubectl) ? The url https://kubernetes-release.pek3b.qingstor.com/release/v1.22.12/bin/linux/amd64/kubeadm still get 404.

Can you try it again? I have already uploaded the binaries to "qingstor.com".

**Comment by yjqg6666** [comment]
@24sama kubesphereio/kube-apiserver images are absent. How about uploading them too ?

> Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/kubesphereio/kube-apiserver:v1.22.12 not found: manifest unknown: manifest unknown: Process exited with status 1

**Comment by yjqg6666** [comment]
@24sama PTAL.

**Comment by 24sama** [comment]
> @24sama PTAL.

![image](https://user-images.githubusercontent.com/43993589/182814177-58bcf827-7116-4fbb-8d75-cefbb71a9fc5.png)
I think it's ok.
