### ISSUE TITLE
kk安装能修改docker的存储目录吗

### ISSUE THREAD

**Issue by Phoebus888** [kubesphere/kubekey#1410]
### Describe this feature

kk安装能修改docker的默认存储目录吗

### Describe the solution you'd like

kk安装能修改docker的默认存储目录吗

**Comment by 24sama** [comment]
Please see: https://github.com/kubesphere/kubekey/pull/1375

**Comment by xiaods** [comment]
need sample docs to learn it.

**Comment by xiaods** [comment]
@Phoebus888 请验证下这个参数，并给一个例子，谢谢。
