### ISSUE TITLE
Add CRI clean logic when delete all the cluster

### ISSUE THREAD

**Issue by life-** [kubesphere/kubekey#1415]
### Your current KubeKey version

v2.1.0

### Describe this feature

Sometimes, I want to clean all CRI(docker/containerd...) configuration and data directories when I delete the total cluster.

### Describe the solution you'd like

./kk delete cluster -f config.yaml --all

Add --all params to indicate remove all CRI  directories.

**Comment by 24sama** [comment]
That is a good feature. 

/kind feature-request

**Comment by 24sama** [comment]
I guess this can be a good-first-issue. If anyone is interested in this, welcome to leave some comments.

/good-first-issue

**Comment by zaunist** [comment]
/assign  

I'm interested in completing it, but I'm not familiar with kubekey yet, can anyone give some advice?

**Comment by 24sama** [comment]
Hi @zaunist , welcome!
Here is a simple kk [architecture introducation](https://github.com/kubesphere/kubekey/blob/master/docs/developer-guide.md#architecture).

BTW, you can start with this pipeline to understand the source code of the kk delete cluster.
https://github.com/kubesphere/kubekey/blob/691611a4c0e6522bf8a9c1a7bcd0780fd7d73fff/pkg/pipelines/delete_cluster.go#L31

And I guess you may need to add a new `module` into this pipeline for cleaning up CRI to solve this issue.

**Comment by zaunist** [comment]
> Hi @zaunist , welcome! Here is a simple kk [architecture introducation](https://github.com/kubesphere/kubekey/blob/master/docs/developer-guide.md#architecture).
> 
> BTW, you can start with this pipeline to understand the source code of the kk delete cluster.
> 
> https://github.com/kubesphere/kubekey/blob/691611a4c0e6522bf8a9c1a7bcd0780fd7d73fff/pkg/pipelines/delete_cluster.go#L31
> 
> And I guess you may need to add a new `module` into this pipeline for cleaning up CRI to solve this issue.

Thanks a lot.
