### ISSUE TITLE
在使用 kubekey安装 k3s的时候

### ISSUE THREAD

**Issue by Heyz6** [kubesphere/kubekey#1416]
### Your current KubeKey version

2.2.0

### Describe this feature

apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 192.168.1.1, internalAddress: 192.168.1.1, user: root, password: "passsword"}
  roleGroups:
    etcd:
    - node1
    control-plane:
    - node1
    worker:
    - node1
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.4-k3s
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []

export KKZONE=cn.;./k8s_install create cluster --with-kubernetes v1.21.4-k3s -f config-sample.yaml
我该如何使用 docker 作为 容器运行时，而不是 containered 

### Describe the solution you'd like

config-sample.yaml 是否支持 自定义运行时 名称

**Comment by 24sama** [comment]
安装k3s环境使用的k3s自带的containerd，如果需要修改k3s的容器运行时可参考rancher的文档：https://rancher.com/docs/k3s/latest/en/advanced/

**Comment by 24sama** [comment]
如果有更多的信息，欢迎重新打开这个issue。
