### ISSUE TITLE
kubekey 2.2.2 not support kubernetes v1.22.12

### ISSUE THREAD

**Issue by tanmx** [kubesphere/kubekey#1419]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"2.2.2", GitCommit:"2ef69c68", GitTreeState:"", GoVersion:"go1.17.12"}

### What is your os environment?

ubuntu 20.04

### KubeKey config file

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Manifest
metadata:
  name: kubekey
spec:
  arches: # Define the architecture that will be included in the artifact.
  - amd64
  operatingSystems: # Define the operating system that will be included in the artifact.
  #- arch: amd64
  #  type: linux
  #  id: ubuntu
  #  version: "20.04"
  #  osImage: Ubuntu 20.04.3 LTS
  #  repository: # Define the operating system repository iso file that will be included in the artifact.
  #    iso:
  #      localPath: ./ubuntu.iso # Define getting the iso file from the local path.
  #      url: # Define getting the iso file from the URL.
  #- arch: amd64
  #  type: linux
  #  id: centos
  #  version: "7"
  #  osImage: CentOS Linux 7 (Core)
  #  repository:
  #    iso:
  #      localPath: ./centos-7-amd64-rpms.iso
  #      #url:
  kubernetesDistributions: # Define the kubernetes distribution that will be included in the artifact.
  - type: kubernetes
    version: v1.22.12
```

### A clear and concise description of what happend.

I found the 1.22.12 is support [支持Kubernetes 版本](https://github.com/kubesphere/kubekey/blob/master/docs/kubernetes-versions.md)

### Relevant log output

```shell
Failed to download kubeadm binary: curl -L -o /root/kubekey/kubekey/artifact/kube/v1.22.12/amd64/kubeadm https://storage.googleapis.com/kubernetes-release/release/v1.22.12/bin/linux/amd64/kubeadm error: No SHA256 found for kubeadm. v1.22.12 is not supported.
14:14:48 CST failed: [LocalHost]
error: Pipeline[ArtifactExportPipeline] execute failed: Module[ArtifactBinariesModule] exec failed:
failed: [LocalHost] [DownloadBinaries] exec failed after 1 retires: Failed to download kubeadm binary: curl -L -o /root/kubekey/kubekey/artifact/kube/v1.22.12/amd64/kubeadm https://storage.googleapis.com/kubernetes-release/release/v1.22.12/bin/linux/amd64/kubeadm error: No SHA256 found for kubeadm. v1.22.12 is not supported.
```

**Comment by 24sama** [comment]
Hi @tanmx 
I'm sorry this may be a little confusing for you. The README is the latest version and is for the latest source code.

This PR #1407 supports the k8s v1.22.12 but this part has not been officially released. If you want this feature, you can clone the kk repo and build it manually.
```
git clone https://github.com/kubesphere/kubekey.git
cd kubekey
make kk
```

**Comment by tanmx** [comment]
> 



> Hi @tanmx I'm sorry this may be a little confusing for you. The README is the latest version and is for the latest source code.
> 
> This PR #1407 supports the k8s v1.22.12 but this part has not been officially released. If you want this feature, you can clone the kk repo and build it manually.
> 
> ```
> git clone https://github.com/kubesphere/kubekey.git
> cd kubekey
> make kk
> ```

got it.
thank you
