### ISSUE TITLE
document to show k3s versions supported

### ISSUE THREAD

**Issue by zhouqiu0103** [kubesphere/kubekey#1432]
### Describe this feature

need document to show the k3s versions supported by kubekey, like [kubekey/docs/kubernetes-versions.md](https://github.com/kubesphere/kubekey/blob/master/docs/kubernetes-versions.md)

### Describe the solution you'd like

add file kubekey/docs/k3s-versions.md

**Comment by zaunist** [comment]
[WeOpen Star]I would like to help

**Comment by zaunist** [comment]
Hi community, how do I know what k3s version are already supported? Does anyone give me some advice?

**Comment by 24sama** [comment]
Hi @zaunist , you can see here:
https://github.com/kubesphere/kubekey/blob/072fed09d6989e71087bcaf0fc1f0b0a9e323760/pkg/files/file.go#L715

**Comment by zaunist** [comment]
> Hi @zaunist , you can see here:
> 
> https://github.com/kubesphere/kubekey/blob/072fed09d6989e71087bcaf0fc1f0b0a9e323760/pkg/files/file.go#L715

Thanks :)
