### ISSUE TITLE
document to show versions of plugins and components

### ISSUE THREAD

**Issue by zhouqiu0103** [kubesphere/kubekey#1433]
### Describe this feature

like **calico** which default version information is in [apis/kubekey/v1alpha1/default.go](https://github.com/kubesphere/kubekey/blob/986449b5790df0928fff9605bd885c9836db622c/apis/kubekey/v1alpha1/default.go#L43) instead of a document , so have a document to show versions of plugins and components used by kubekey can help users troubleshoot version compatibility issues more easily

### Describe the solution you'd like

add file in kubekey/docs/

**Comment by 24sama** [comment]
[apis/kubekey/v1alpha1/default.go](https://github.com/kubesphere/kubekey/blob/986449b5790df0928fff9605bd885c9836db622c/apis/kubekey/v1alpha1/default.go#L43) -> [apis/kubekey/v1alpha2/default.go](https://github.com/kubesphere/kubekey/blob/986449b5790df0928fff9605bd885c9836db622c/apis/kubekey/v1alpha2/default.go#L49)
/good-first-issue

**Comment by xiaods** [comment]
code is document. don't need write documents. if you need it, welcome pr.

**Comment by xiaods** [comment]
@zhouqiu0103
