### ISSUE TITLE
CAPK supports to install docker

### ISSUE THREAD

**Issue by 24sama** [kubesphere/kubekey#1434]
### Your current KubeKey version

latest

### Describe this feature

At present, cluster-api-kubekey-provider(CAPK) only supports to install `containerd`. We need to support installing `docker`.

### Describe the solution you'd like

Add a `dockerService` in the capk `pkg/service/containermanager`.

**Comment by xiaods** [comment]
no pkg/service/containermanager file.

**Comment by 24sama** [comment]
> no pkg/service/containermanager file.

Please wait for the [PR](https://github.com/kubesphere/kubekey/pull/1421) to merge.

**Comment by xiaods** [comment]
welcome pr

**Comment by arugal** [comment]
@24sama  I will contribute this feature :)
