### ISSUE TITLE
ClusterConfiguration file info

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#147]
I installed a minimal environment, so it is using localVolume as storage class. But using `kubectl get cc ks-installer -n kubesphere-system -o yaml` I found the sc is empty.

<img width="243" alt="Screen Shot 2020-07-13 at 11 25 31 AM" src="https://user-images.githubusercontent.com/28859385/87268144-3fd5cb80-c4fc-11ea-9c55-b702a65deb30.png">

**Comment by pixiake** [comment]
Yes,  `storageClass` is empty means the `default` storage class is used. The specified storage class name was not filled in config during installation.
