### ISSUE TITLE
Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/kubesphereio/kube-ovn:v1.10.5 not found: 

### ISSUE THREAD

**Issue by pennpeng** [kubesphere/kubekey#1487]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"2.3.0-rc.1", GitCommit:"eb460804", GitTreeState:"", GoVersion:"go1.18.5"}

### What is your os environment?

ubuntu 20.04

### A clear and concise description of what happend.

pull image failed: Failed to exec command: sudo -E /bin/bash -c "env PATH=$PATH docker pull registry.cn-beijing.aliyuncs.com/kubesphereio/kube-ovn:v1.10.5" 
Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/kubesphereio/kube-ovn:v1.10.5 not found: manifest unknown: manifest unknown: Process exited with status 1
09:11:58 UTC failed: [k8s-2]
09:11:58 UTC failed: [k8s-1]
error: Pipeline[CreateClusterPipeline] execute failed: Module[PullModule] exec failed: 
failed: [k8s-2] [PullImages] exec failed after 3 retires: pull image failed: Failed to exec command: sudo -E /bin/bash -c "env PATH=$PATH docker pull registry.cn-beijing.aliyuncs.com/kubesphereio/kube-ovn:v1.10.5" 
Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/kubesphereio/kube-ovn:v1.10.5 not found: manifest unknown: manifest unknown: Process exited with status 1
failed: [k8s-1] [PullImages] exec failed after 3 retires: pull image failed: Failed to exec command: sudo -E /bin/bash -c "env PATH=$PATH docker pull registry.cn-beijing.aliyuncs.com/kubesphereio/kube-ovn:v1.10.5" 
Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/kubesphereio/kube-ovn:v1.10.5 not found: manifest unknown: manifest unknown: Process exited with status 1
root@penn:~/kubekey#

**Comment by pixiake** [comment]
![image](https://user-images.githubusercontent.com/22290449/188109092-bddb5a90-d3dc-4b7b-af27-0d0ebd57ea93.png)

@pennpeng Thanks for your feedback. This image can already be pulled.

**Comment by pennpeng** [comment]
@pixiake  OK thanks
