### ISSUE TITLE
Refactor the KubeKey project structure

### ISSUE THREAD

**Issue by 24sama** [kubesphere/kubekey#1504]
### Backgroud
1. Currently, the KubeKey operator mode has some defects, such as not enough abstraction that only defines the `cluster` object, and using `job` to run a command line program (kk) in a way that is difficult to maintain the idempotency.
2. The codes of kk operator mode are heavily coupled with the codes of command line mode. For example, the command-line mode codes have to add operator-related control statement codes in it.
3. To solve the above problems, we have developed cluster-api-provider-kubekey (CAPKK). At present, the basic functionality of CAPKK is nearly complete, and some e2e tests are also provided to ensure stability.
4. The CAPKK's codes are already in the `exp/` directory, but it still cause some problems (e.g. main.go conflicts, directory confusion, difficulty in adapting clusterctl etc.), so for better development, we need to refactor the project structure and clean up the unused codes.

### Solution
CAPKK will be paired with the KubeKey command line (kk) as the next generation way to manage the Kubernetes cluster lifecycle. The KubeKey project will also include 2 sub-project codes as before:
* kk: A command line program. The codes will be moved to `cmd/kk`.
* CAPKK: A Kubernetes extension operator. The codes will be moved out from `exp/` and replace the original kk operator mode's.

After the refactor, the project tree will be:
```
./kubekey 
├── cmd/
│   └── kk/
│       ├── apis/
│       ├── cmd/
│       ├── hack/
│       ├── pkg/
│       └── main.go # the main.go of kk.
├── api/
│   └── v1beta1/
├── config/
├── controllers/
├── docs/
├── hack/
├── pkg/
├── scripts/
├── test/
├── Dockerfile
├── Makefile
├── PROJECT
├── go.mod
├── go.sum
└── main.go         # the main.go of CAPKK.
```

**Comment by xiaods** [comment]
cool, I can't waiting for your proposal
