### ISSUE TITLE
make controller-gen failed because of different locations between downloading and invoking

### ISSUE THREAD

**Issue by lwabish** [kubesphere/kubekey#1516]
### What is version of KubeKey has the issue?

git commit id b731d2f4

### What is your os environment?

darwin 12.6

### A clear and concise description of what happend.

line `GOBIN=$(PROJECT_DIR)/bin go get $(2)`
in Makefile go-get-tool function is not running as expected because go get is not consuming GOBIN env.
It downloads the controller-gen to the global gobin dir.
I am using go version go1.19 darwin/amd64
I tried switching `go get` to `go install` and it can consume GOBIN env.
Maybe consider switching go get to go install?
If necessary, I'd love to summit a pr to fix this.

Meanwhile, `make kustomize` doesn't work either and switching `go get` to `go install` can't fix it.
Did some workaround to make it work: According to [kustomize install](https://kubectl.docs.kubernetes.io/installation/kustomize/source/#install-the-kustomize-cli-from-source-without-cloning-the-repo), after change `go get` to `go install`, I replaced the kustomize version to v4 and installed it successfully.

### Relevant log output

```shell
❯ make run
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.6.1
/Users/XXXXXX/lib/kubekey/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
bash: line 1: /Users/XXXXXX/lib/kubekey/bin/controller-gen: No such file or directory
make: *** [Makefile:84: manifests] Error 127
```

### Additional information
After doing some search, found that go 1.17 and upper has changed the usage of `go get` and `go install` a little bit: [go-get-install-deprecation](https://go.dev/doc/go-get-install-deprecation)

**Comment by 24sama** [comment]
Hi @lwabish, happy to see you are interested in kk operator mode.
I found a same issue: https://stackoverflow.com/questions/71608442/generating-controller-gen-with-kubebuilder

And we are preparing to [refactor the kk project structure](https://github.com/kubesphere/kubekey/issues/1504). The next generation kk operator codes are in the `exp/` dir (also contains the Makefile), it uses a script(implemented by `go install`) to install these tools.

**Comment by lwabish** [comment]
Copy that.I have made some temporary changes for current using.

By the way, when will the CAPKK be released? Is there an estimated schedule?

**Comment by 24sama** [comment]
We will release v2.3.0 in two weeks (depending on [KubeSphere](https://github.com/kubesphere/kubesphere) released v3.3.1) and after that, we can do the refactor on the master branch and then release the first CAPKK version.

**Comment by lwabish** [comment]
Will the operator of old releases still in maintenance then?
My org is just about to apply this operator in production😂

**Comment by 24sama** [comment]
Low Priority. As you can see the old operator has no changes for 6 months cause there are some defects. 

So, we highly recommend that you can use CAPKK. 

If you have any problems with CAPKK, please search to add the WeChat bot "kubesphere".

**Comment by pixiake** [comment]
> Will the operator of old releases still in maintenance then? My org is just about to apply this operator in production😂

It is recommend to use capkk instead of the old operator, because capkk is based on the `cluster-api` specification, and it can manage clusters more finely.

**Comment by lwabish** [comment]
Thanks a lot!
