### ISSUE TITLE
How can I edit 'containerLogMaxSize' with kubekey

### ISSUE THREAD

**Issue by x86cloud** [kubesphere/kubekey#1532]
### Your current KubeKey version

./kk create cluster -f config.yaml

### Describe this feature

for some resonse, i want to edit kubelet's config `containerLogMaxSize` and `containerLogMaxFiles `. is there any solution?

### Describe the solution you'd like

config or args?

**Comment by 24sama** [comment]
Just like this issue: https://github.com/kubesphere/kubekey/issues/1509
```
kuberneters:
  kubeletConfiguration:
    containerLogMaxSize: 5Mi
```
