### ISSUE TITLE
在ubuntu 20.04上离线安装时会自动下载已存在的包

### ISSUE THREAD

**Issue by JohnsonJo** [kubesphere/kubekey#1543]
### Your current KubeKey version

version.BuildInfo{Version:"2.2.2", GitCommit:"2ef69c68", GitTreeState:"", GoVersion:"go1.17.12"}

### Describe this feature

已经做好了离线安装包，离线安装包里存在对应的文件，但是执行安装命令时依然会再次进行下载。
如下图，存在etcd包:
![image](https://user-images.githubusercontent.com/32511145/195072205-f604e514-c7fe-4ba6-83e1-1c95c96d8286.png)
离线安装命令如下： 
`./kk create cluster -f config-sample.yaml -a kubesphere.tar.gz`
离线安装日志如下：
日志中显示kk重新下载了amd64 etcd v3.4.13包

### Describe the solution you'd like

希望已存在包的情况下不要再下载了（如果是真实的离线环境，也肯定不能成功的）。
不过我最真实的需求是能在arm平台上直接使用离线部署包进行安装。
目前我这个kubesphere.tar.gz制品包实际上是arm版本的，但因为kk没法支持arm，所以把里面的arm文件夹和文件名都替换成了amd。
难道是这个原因导致kk重新下载包的？是因为包的md5码不一致，kk校验发现需要重新下载吗？

**Comment by JohnsonJo** [comment]
日志图片貌似没上传成功，重新来一次：
![image](https://user-images.githubusercontent.com/32511145/195074879-d744cb34-0580-4f7d-be6c-7581c5777d76.png)

**Comment by JohnsonJo** [comment]
明白了。
kk果然做的很严谨。
不过我的问题就变成了为啥我是在arm服务器上运行的，指定的kubesphere.tar.gz制品包也是arm的。
但使用kk安装时，kk一直在下载amd的包。
我的操作系统信息：
![image](https://user-images.githubusercontent.com/32511145/195242330-ef390ab3-e887-4cac-acc2-20191c89e87a.png)
我的制品包内容：
![image](https://user-images.githubusercontent.com/32511145/195242531-73b024ac-7d18-4d13-bb3f-ee0da98f41ed.png)
配置文件：
![image](https://user-images.githubusercontent.com/32511145/195242683-caa353c5-5b30-4781-9c26-b1989162a27d.png)
安装时的日志：
![image](https://user-images.githubusercontent.com/32511145/195242896-e83b72f1-a6e2-4a55-b6f5-206d78ffd091.png)
求教，是我哪块配置不对吗？

**Comment by pixiake** [comment]
https://github.com/kubesphere/kubekey/blob/595695c4f9397d801a647ac811b77f034e885d6b/cmd/kk/apis/kubekey/v1alpha2/cluster_types.go#L68

You need to add `arch` in the hosts configuration.

**Comment by JohnsonJo** [comment]
非常感谢，加上arch后就可以跑了。
不过还有个问题要请教下，我在制作离线包的时候指定了crictl版本为1.22.0，但是安装时kk需要下载1.24.0版本。
这个是什么原因呢？怎么设置具体组件的版本呢？
![image](https://user-images.githubusercontent.com/32511145/195246197-e1aa65d4-7971-4b27-a2e6-14f577c3e84b.png)

**Comment by 24sama** [comment]
你安装的k8s版本是1.24吗，这种情况下离线包中的crictl也需要是1.24.0版本

**Comment by JohnsonJo** [comment]
> 你安装的k8s版本是1.24吗，这种情况下离线包中的crictl也需要是1.24.0版本

我装的k8s版本是v1.22.10

**Comment by JohnsonJo** [comment]
好的，多谢！
