### ISSUE TITLE
Installed forward compatibility is broken, older versions of Kubernetes cannot be installed

### ISSUE THREAD

**Issue by TaibiaoGuo** [kubesphere/kubekey#1559]
### What is version of KubeKey has the issue?

v2.2.2

### What is your os environment?

Centos 7.9

### KubeKey config file

```yaml
All-in-one
```

### A clear and concise description of what happend.

I used All-in-One mode to install the old version of Kubernetes, because the current Calico is not compatible with the old version of Kubernetes API, so Calico installation failed. The Kubernetes v1.20.6 I need to install is in the recommended version of the Kubekey documentation. From the error log, it appears that the latest CNI plug-in version is used when installing any version of Kubernetes. Kubekey does not consider providing compatible version dependencies for different versions of Kubernetes.

### Relevant log output

```shell
error: unable to recognize "/etc/kubernetes/network-plugin.yaml": no matches for kind "PodDisruptionBudget" in version "policy/v1"
10:47:25 CST message: [hmb-01]
deploy network plugin failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl apply -f /etc/kubernetes/network-plugin.yaml --force"
```

**Comment by 24sama** [comment]
Thanks for your feedback!
For now, you can set the `.spec.network.plugin: none`
```
  network:
    plugin: none
```
And use kk addons to deploy your customized CNI yaml file.
https://github.com/kubesphere/kubekey/blob/master/docs/addons.md

**Comment by xiaods** [comment]
resolved as /close
