### ISSUE TITLE
kubsephere的console组件是否可以自定义版本

### ISSUE THREAD

**Issue by polarbear122** [kubesphere/kubekey#1584]
### Describe this feature

使用kubekey同时安装k8s集群和kubesphere时，发现仅能设置设置其主版本。
我想对kubesphere的console组件进行二次开发，但是不清楚如何将二次开发后的组件重新打包安装，在kubekey的帮助文档中发现没有该选择。

### Describe the solution you'd like

是否可以教我如何通过kubekey选择自定义的console版本。kubekey目前是否可以支持这个功能？如果没有支持的话，能否指导一下通过修改kubekey的代码是否可以达到选择自定义的console版本的目的，大概需要修改哪几处的源码？

**Comment by 24sama** [comment]
Hi @polarbear122 , kubesphere is deployed by [ks-installer](https://github.com/kubesphere/ks-installer), you need to develop that project.

**Comment by polarbear122** [comment]
> Hi @polarbear122 , kubesphere is deployed by [ks-installer](https://github.com/kubesphere/ks-installer), you can see that.

Thank you,  I will have a look at ks-installer.
