### ISSUE TITLE
Docs for master lb

### ISSUE THREAD

**Issue by yuswift** [kubesphere/kubekey#162]
Kubekey sets firsr master node as kubeconfig server. However, when master1 is unavailable, all master and worker nodes will be not ready, because kubelet will connect apiserver with kubeconfig. 
Need docs for creating loadbalance for master before create cluster.

**Comment by FeynmanZhou** [comment]
Are these guides enough?

https://v3-0.docs.kubesphere.io/docs/installing-on-linux/public-cloud/kubesphere-on-qingcloud-instance/
https://v3-0.docs.kubesphere.io/zh/docs/installing-on-linux/on-premise/install-kubesphere-on-vmware-vsphere/

**Comment by yuswift** [comment]
Yeap. It's enough. Closed.
