### ISSUE TITLE
kk artifact export 执行异常

### ISSUE THREAD

**Issue by airufei** [kubesphere/kubekey#1629]
### What is version of KubeKey has the issue?

2.1.0

### What is your os environment?

centos7

### A clear and concise description of what happend.

执行kk artifact export -m manifest-sample.yaml -o kubesphere.tar.gz 的时候，会访问本机22端口，但是ssh端口被改了，就会出现异常：

error: Pipeline[ArtifactExportPipeline] execute failed: Module[GreetingsModule] exec failed: 
failed: [test-k8s-master-1] failed to connect to 192.168.0.13: could not establish connection to 192.168.0.13:22: dial tcp 192.168.0.13:22: connect: connection refused

只有把机器ssh端口改了才能正常执行：
1）不知道连接22端口是干啥？
2）如何通过kk 指定特定的端口执行？

**Comment by 24sama** [comment]
The kk v2.1.0 version contains some useless checks. Try to use the latest version (v3.0.2).

**Comment by 24sama** [comment]
/close

Feel free to reopen it.
