### ISSUE TITLE
Kubelet Always Restarting After Install the Cluster or Host Added

### ISSUE THREAD

**Issue by antikilahdjs** [kubesphere/kubekey#1641]
### What is version of KubeKey has the issue?

3.0.1

### What is your os environment?

Ubuntu 20.04

### A clear and concise description of what happend.

When the new cluster needs to added the events logs show the Kubelet always trying Restarting and I cannot use the Host as well. To fix this issue I need enter manually into the Host then restart the Kubelet Service. I saw in some blogs I can happens due wrong sequence about Docker vs Kubelet. The kubelet trying start before docker running 100% up.

### Relevant log output

```shell
Normal	Starting	an hour ago	kubelet	Starting kubelet.
```

### Additional information

![image](https://user-images.githubusercontent.com/33559260/205070312-67c30d26-b768-484b-8b13-7248e630b8cf.png)

**Comment by 24sama** [comment]
Can you give some more detailed information? Is the kubelet not working properly after the cluster is created?

**Comment by antikilahdjs** [comment]
Hello @24sama . Sure, Kubelet works perfectly on the machine but when the cluster has been re-created or re-deployed apparently the Kubelet try to start before docker and sometimes the Kubelet always show *restarting* and Docker get some troubles with Failed to Image GC . I founded on the google this can be a error with Garbage Collector then it is about the service sequence, in other words Kubelet trying start before Docker's up .

**Comment by 24sama** [comment]
Hi @antikilahdjs ,sorry to reply late.
> Sure, Kubelet works perfectly on the machine
I guess, they can eventually launch successfully, is it right? So, maybe you don't need to care about the short-lived error.

**Comment by antikilahdjs** [comment]
Hi @24sama  no problem . Kubelet and Docker works but I need enter in the machine manually then restart a Kubelet cuz the error *Kubelet Starting and Failed to Get ImageFS* cannot bring up all services.

The error below show it a little bit more detailed. If I am not enter in the machine manually to restart a Kubelet Service I cannot add their machine in the cluster. When I try to search on the Google about the error many guys said "It is because the Kubelet trying start before Docker Service, in that case needs to be change the sequence then add Docker before Kubelet".

I've just opened this issue to understand if in the ansible script can be perform this change and I guess the sequence about service is wrong. Thank you :)

![image](https://user-images.githubusercontent.com/33559260/205637971-e8d49776-2495-4b39-86e5-9668e1444c51.png)

**Comment by 24sama** [comment]
Hi @antikilahdjs 
It is really strange. KK will install and launch the docker before the kubelet. Here is the code:
https://github.com/kubesphere/kubekey/blob/736af43bd7efdabd889fbef987dbdc4147461fb7/cmd/kk/pkg/pipelines/create_cluster.go#L60-L96

As you can see, `&container.InstallContainerModule{}` will install the docker, and then, there are `images.PullModule`, `etcd module`, and so on. So, the sequence is correct. Maybe there are other cases,is there an error in the docker service? Is there an error about CNI?

**Comment by antikilahdjs** [comment]
@24sama I really appreciate your attention about that then I will check internally because if almost guys does not have the error like mine the issues is from my side. Thank you much.

**Comment by 24sama** [comment]
You are welcome, feel free to create other issues if you have any problem.
