### ISSUE TITLE
k8s v1.25.4 is not supported

### ISSUE THREAD

**Issue by zaunist** [kubesphere/kubekey#1643]
### What is version of KubeKey has the issue?

kk version version.BuildInfo{Version:"2.2.2", GitCommit:"2ef69c68", GitTreeState:"", GoVersion:"go1.17.12"}

### What is your os environment?

ubuntu 20.04

### A clear and concise description of what happend.

文档上写的支持 k8s v1.25.4，但是实际上还不支持

https://github.com/kubesphere/kubekey/blob/master/docs/kubernetes-versions.md

### Relevant log output

```shell
06:17:21 UTC message: [LocalHost]
Failed to download kubeadm binary: curl -L -o /root/kubekey/kube/v1.25.4/amd64/kubeadm https://kubernetes-release.pek3b.qingstor.com/release/v1.25.4/bin/linux/amd64/kubeadm error: No SHA256 found for kubeadm. v1.25.4 is not supported. 
06:17:21 UTC failed: [LocalHost]
error: Pipeline[CreateClusterPipeline] execute failed: Module[NodeBinariesModule] exec failed: 
failed: [LocalHost] [DownloadBinaries] exec failed after 1 retires: Failed to download kubeadm binary: curl -L -o /root/kubekey/kube/v1.25.4/amd64/kubeadm https://kubernetes-release.pek3b.qingstor.com/release/v1.25.4/bin/linux/amd64/kubeadm error: No SHA256 found for kubeadm. v1.25.4 is not supported.
```

**Comment by 24sama** [comment]
Please use the latest kk version.

**Comment by 24sama** [comment]
These new features, like support new k8s version, usually need to create a patch PR and release a new version. So, user need also replace their kk binary which is in their linux to experience these.

**Comment by zaunist** [comment]
Thanks.
