### ISSUE TITLE
Make es configurable when installing ks

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#173]
Current config yaml only uses built-in es. It is highly possible for enterprise customers to configure it to user external es. So provide such configuration in the lnstallation config file.

**Comment by benjaminhuo** [comment]
[config-example.md](https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md)  this config-example doc is too old to reflect current changes: the es config has been moved from logging to common by [this PR](https://github.com/kubesphere/ks-installer/pull/904/commits/b7ac9240441224b575bba29425c46d58746b1a31). 

We may need to adjust cc or this doc accordingly .

There're already external es setting in ks-installer like this, we can simply add it to the cc's doc?:
![image](https://user-images.githubusercontent.com/18525465/88659441-a0255980-d107-11ea-89f0-418d4f1b4abb.png)

**Comment by rayzhou2017** [comment]
verified
