### ISSUE TITLE
use kk delete cluster error

### ISSUE THREAD

**Issue by hawking-lab** [kubesphere/kubekey#175]
[root@localhost data]# curl -O -k https://kubernetes.pek3b.qingstor.com/tools/kubekey/kk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41.0M  100 41.0M    0     0   987k      0  0:00:42  0:00:42 --:--:-- 1039k
[root@localhost data]# chmod +x kk
[root@localhost data]# ./kk create config --with-kubesphere
config-sample.yaml  demo.yaml  kk
[root@localhost data]# ./kk  delete cluster -f demo.yaml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12e0ce9]

goroutine 1 [running]:
github.com/kubesphere/kubekey/pkg/delete.ResetCluster(0x7ffecdea8833, 0x9, 0xc00042e000, 0x1, 0x1584f1d, 0x4)
	/usr/src/myapp/pkg/delete/delete.go:39 +0xb9
github.com/kubesphere/kubekey/cmd.glob..func3(0x21e35a0, 0xc000274f30, 0x1, 0x3)
	/usr/src/myapp/cmd/delete.go:30 +0x163
github.com/spf13/cobra.(*Command).execute(0x21e35a0, 0xc000274f00, 0x3, 0x3, 0x21e35a0, 0xc000274f00)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x21e3840, 0x1595381, 0x16, 0xc0000c1f20)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/kubesphere/kubekey/cmd.Execute()
	/usr/src/myapp/cmd/root.go:54 +0x31
main.main()
	/usr/src/myapp/kubekey.go:38 +0x1a5

**Comment by pixiake** [comment]
Something wrong with the format of the configuration file `demo.yaml`?

**Comment by hawking-lab** [comment]
I found that reason, can't run 'delete cluster ' common first.
