### ISSUE TITLE
Change curl to wget

### ISSUE THREAD

**Issue by Dawei-Simayi** [kubesphere/kubekey#1774]
### Describe this feature

When I export artifact with kk, even I use proxy in terminal,  it download the package from github very slowly from China through using curl. 

![image](https://user-images.githubusercontent.com/56547870/226152515-8e3914b3-31f7-494f-9ad2-b68e2d4367eb.png)

### Describe the solution you'd like

Use wget not curl
Or other ways to make it possobale to use proxy

**Comment by Dawei-Simayi** [comment]
> You can try again after setting environment 'export KKZONE=cn'

Hi，I have set this in .zshrc, it doesn't work, and it still download from github without proxy

**Comment by HeyChiang** [comment]
It's impossible. I have tried it many times on Alibaba Cloud servers, and it's okay.

**Comment by Dawei-Simayi** [comment]
> It's impossible. I have tried it many times on Alibaba Cloud servers, and it's okay.

Oh, maybe it works on cloud platfom, I just try it with my desktop.

**Comment by xiaods** [comment]
welcome PR

**Comment by Dawei-Simayi** [comment]
> en I export artifact with k

It's a good idea! Let me see the develop guide for a while. I can't stand this download speed
