### ISSUE TITLE
kubesphere/metrics-server:v0.4.2 doesn't work on Kylin V10 arm64 

### ISSUE THREAD

**Issue by weiliang-ms** [kubesphere/kubekey#1777]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.7-dirty", GitCommit:"e755baf67198d565689d7207378174f429b508ba", GitTreeState:"drty", BuildDate:"2023-01-18T01:59:52Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}

### What is your os environment?

Kylin Linux Advanced Server release V10 (Lance)

### A clear and concise description of what happend.

1. when i use `kubekey` to install `kubesphere`  on arm64, the metrics-server on `CrashLoopBackOff` status.

```
$ kubectl logs -f metrics-server-7ddc55f5f4-hg99v -n kube-system
standard_init_linux.go:219: exec user process caused "exec format error"
libcontainer: container start initialization failed: standard_init_linux.go:219: exec user process caused "exec format error"
```

2. use `docker` to run the image

```
$  docker run --rm kubesphere/metrics-server:v0.4.2
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was reuested
standard_init_linux.go:219: exec user process caused "exec format error"
libcontainer: container start initialization failed: standard_init_linux.go:219: exec user process caused "exec format error"
```

3. Then i change the image tag to `kubesphere/metrics-server:v0.4.5`, the service runs well.

**Comment by pixiake** [comment]
As far as I know, currently, KubeSphere team does not maintain a separate ARM64 version. If you need to deploy KubeSphere on ARM64 architecture devices, you can try to build ARM64 images yourself or search for third-party ARM64 images. 

Additionally, if you need to deploy KubeSphere Enterprise (ARM64), you can contact the KubeSphere team or visit [kubesphere.cloud](https://kubesphere.cloud/en/self-service/qkcp/) for information on supported architectures and versions. Enterprise editions typically offer more support and services to better meet the needs of enterprise-level applications.

**Comment by yzcyayaya** [comment]
set image
`kubesphere/metrics-server:v0.4.2-arm64`
