### ISSUE TITLE
The terminal keyboard in the container cannot be used

### ISSUE THREAD

**Issue by wuxiangping** [kubesphere/kubekey#183]
KubeSphere 2.1 and KubeSphere 3.0
The container terminal keyboard arrow keys, home end insert delete key cannot be used. 
The tab key also cannot be used
![20200803141612](https://user-images.githubusercontent.com/9893160/89151673-0ee53580-d594-11ea-852c-850592b2ca22.png)

**Comment by pixiake** [comment]
What browser are you using?
Is it used through remote desktop?

**Comment by wuxiangping** [comment]
> What browser are you using?
> Is it used through remote desktop?

browser

**Comment by pixiake** [comment]
@wuxiangping 
What browser are you using?

**Comment by leoendless** [comment]
Try exec `bash` in the terminal.

**Comment by leoendless** [comment]
The container image might use `sh` as default start command.

**Comment by wuxiangping** [comment]
> Try exec in the terminal.`bash`

bash is ok !
