### ISSUE TITLE
Mac M1 使用OrbStack 使用问题

### ISSUE THREAD

**Issue by imkratos** [kubesphere/kubekey#1833]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.7-dirty", GitCommit:"e755baf67198d565689d7207378174f429b508ba", GitTreeState:"dirty", BuildDate:"2023-01-18T01:59:52Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}

### What is your os environment?

Linux ubuntu 6.1.27-orbstack-00159-g449a0a140030 #1 SMP Thu May  4 03:11:08 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### KubeKey config file

```yaml
无，官方all in one 例子

./kk create cluster --with-kubernetes v1.22.12 --with-kubesphere v3.3.2
```

### A clear and concise description of what happend.

执行 ./kk create cluster --with-kubernetes v1.22.12 --with-kubesphere v3.3.2

### Relevant log output

```shell
_   __      _          _   __
| | / /     | |        | | / /
| |/ / _   _| |__   ___| |/ /  ___ _   _
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

11:15:39 CST [GreetingsModule] Greetings
11:15:39 CST failed: [ubuntu]
error: Pipeline[CreateClusterPipeline] execute failed: Module[GreetingsModule] exec failed:
failed: [ubuntu] failed to connect to 100.115.93.97: could not establish connection to 100.115.93.97:22: dial tcp 100.115.93.97:22: connect: connection refused
```

### Additional information

root@ubuntu:~# cat /etc/hosts
127.0.0.1	ubuntu
100.115.93.97	ubuntu
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters

root@ubuntu:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 5e:24:0f:11:d3:91 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 100.115.93.97/24 metric 100 brd 100.115.93.255 scope global dynamic eth0
       valid_lft 172053sec preferred_lft 172053sec
    inet6 fd00:30:31:0:5c24:fff:fe11:d391/64 scope global mngtmpaddr noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::5c24:fff:fe11:d391/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:d0:96:06:ab brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

**Comment by pixiake** [comment]
```
dial tcp 100.115.93.97:22: connect: connection refused
```
22 connection refused. Did your node not turn on ssh?

**Comment by imkratos** [comment]
> 

3ks, start ssh server it's working.
