### ISSUE TITLE
请问，可以支持部署cni为空嘛？即只部署k8s，我想自己部署cni

### ISSUE THREAD

**Issue by bobz965** [kubesphere/kubekey#1868]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"0", GitVersion:"v3.0.7", GitCommit:"e755baf67198d565689d7207378174f429b508ba", GitTreeState:"clean", BuildDate:"2023-01-18T01:57:24Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

rocky9

### KubeKey config file

```yaml
无
```

### A clear and concise description of what happend.

无

### Relevant log output

```shell
无
```

### Additional information

无

**Comment by littleBlackHouse** [comment]
refer to https://github.com/kubesphere/kubekey#network-plugins. You can create a cluster by configuring a configuration file. and set `network:plugin:none` in your configuration file.
1. generate default config file `kk create config`.
2. change the default config. set `network:plugin:none` 
3. create cluster `kk create cluster -f xxx.yaml`

**Comment by bobz965** [comment]
> refer to https://github.com/kubesphere/kubekey#network-plugins. You can create a cluster by configuring a configuration file. and set `network:plugin:none` in your configuration file.
> 
> 1. generate default config file `kk create config`.
> 2. change the default config. set `network:plugin:none`
> 3. create cluster `kk create cluster -f xxx.yaml`

thank you very much
