### ISSUE TITLE
Display the time and duration of successful installation

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubekey#188]
- [ ] To help users to clearly confirm the installation, it would be better to display the **time and duration** of successful installation  on the final page:

![image](https://user-images.githubusercontent.com/40452856/89274871-17ad3880-d674-11ea-8514-9188de625790.png)

**Comment by pixiake** [comment]
https://github.com/kubesphere/ks-installer/pull/1007

**Comment by FeynmanZhou** [comment]
Thanks
