### ISSUE TITLE
failed: [node3] [GenerateScript] exec failed after 3 retires: scp file /home/scapp/kubekey/node3/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied

### ISSUE THREAD

**Issue by nsdsb123** [kubesphere/kubekey#1880]
### Your current KubeKey version

3.0.7

### Describe this feature

使用kk安装k8s集群过程中，scp initOS.sh到各个节点时报错permission denied，包括master本身也是失败，检查过文件目录权限没问题，config不是使用密钥的形式，使用的是密码登录

### Describe the solution you'd like

请问如何解决

**Comment by littleBlackHouse** [comment]
Can you provide the complete installation logs?

**Comment by nsdsb123** [comment]
> Can you provide the complete installation logs?

17:30:43 CST [GreetingsModule] Greetings
17:30:44 CST message: [node2]
Greetings, KubeKey!
17:30:44 CST message: [node3]
Greetings, KubeKey!
17:30:45 CST message: [node4]
Greetings, KubeKey!
17:30:45 CST message: [node1]
Greetings, KubeKey!
17:30:45 CST message: [master]
Greetings, KubeKey!
17:30:45 CST success: [node2]
17:30:45 CST success: [node3]
17:30:45 CST success: [node4]
17:30:45 CST success: [node1]
17:30:45 CST success: [master]
17:30:45 CST [NodePreCheckModule] A pre-check on nodes
17:30:45 CST success: [node1]
17:30:45 CST success: [master]
17:30:45 CST success: [node2]
17:30:45 CST success: [node3]
17:30:45 CST success: [node4]
17:30:45 CST [ConfirmModule] Display confirmation form
17:30:45 CST success: [LocalHost]
17:30:45 CST [NodeBinariesModule] Download installation binaries
17:30:45 CST message: [localhost]
downloading amd64 kubeadm v1.24.1 ...
17:30:46 CST message: [localhost]
kubeadm is existed
17:30:46 CST message: [localhost]
downloading amd64 kubelet v1.24.1 ...
17:30:48 CST message: [localhost]
kubelet is existed
17:30:48 CST message: [localhost]
downloading amd64 kubectl v1.24.1 ...
17:30:48 CST message: [localhost]
kubectl is existed
17:30:48 CST message: [localhost]
downloading amd64 helm v3.9.0 ...
17:30:49 CST message: [localhost]
helm is existed
17:30:49 CST message: [localhost]
downloading amd64 kubecni v0.9.1 ...
17:30:49 CST message: [localhost]
kubecni is existed
17:30:49 CST message: [localhost]
downloading amd64 crictl v1.24.0 ...
17:30:49 CST message: [localhost]
crictl is existed
17:30:49 CST message: [localhost]
downloading amd64 etcd v3.4.13 ...
17:30:49 CST message: [localhost]
etcd is existed
17:30:49 CST message: [localhost]
downloading amd64 containerd 1.6.4 ...
17:30:50 CST message: [localhost]
containerd is existed
17:30:50 CST message: [localhost]
downloading amd64 runc v1.1.1 ...
17:30:50 CST message: [localhost]
runc is existed
17:30:50 CST success: [LocalHost]
17:30:50 CST [ConfigureOSModule] Get OS release
17:30:50 CST success: [node1]
17:30:50 CST success: [node2]
17:30:50 CST success: [node3]
17:30:50 CST success: [master]
17:30:50 CST success: [node4]
17:30:50 CST [ConfigureOSModule] Prepare to init OS
17:30:51 CST success: [node2]
17:30:51 CST success: [node4]
17:30:51 CST success: [node3]
17:30:51 CST success: [node1]
17:30:51 CST success: [master]
17:30:51 CST [ConfigureOSModule] Generate init os script
17:30:51 CST message: [master]
scp file /home/scapp/kubekey/master/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:30:51 CST retry: [master]
17:30:51 CST message: [node4]
scp file /home/scapp/kubekey/node4/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:30:51 CST retry: [node4]
17:30:51 CST message: [node3]
scp file /home/scapp/kubekey/node3/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:30:51 CST retry: [node3]
17:30:51 CST message: [node1]
scp file /home/scapp/kubekey/node1/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:30:51 CST retry: [node1]
17:30:51 CST message: [node2]
scp file /home/scapp/kubekey/node2/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:30:51 CST retry: [node2]
17:30:56 CST message: [master]
scp file /home/scapp/kubekey/master/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:30:56 CST retry: [master]
17:30:56 CST message: [node4]
scp file /home/scapp/kubekey/node4/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:30:56 CST retry: [node4]
17:30:56 CST message: [node1]
scp file /home/scapp/kubekey/node1/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:30:56 CST retry: [node1]
17:30:56 CST message: [node3]
scp file /home/scapp/kubekey/node3/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:30:56 CST retry: [node3]
17:30:56 CST message: [node2]
scp file /home/scapp/kubekey/node2/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:30:56 CST retry: [node2]
17:31:01 CST message: [node4]
scp file /home/scapp/kubekey/node4/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:31:01 CST message: [master]
scp file /home/scapp/kubekey/master/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:31:01 CST message: [node3]
scp file /home/scapp/kubekey/node3/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:31:01 CST message: [node1]
scp file /home/scapp/kubekey/node1/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:31:01 CST message: [node2]
scp file /home/scapp/kubekey/node2/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
17:31:01 CST failed: [node4]
17:31:01 CST failed: [master]
17:31:01 CST failed: [node3]
17:31:01 CST failed: [node1]
17:31:01 CST failed: [node2]

**Comment by littleBlackHouse** [comment]
You might be using the **scapp** user for the installation. Kubekey requires root privileges during installation. You can try installing it using the **root** user.

**Comment by nsdsb123** [comment]
> You might be using the **scapp** user for the installation. Kubekey requires root privileges during installation. You can try installing it using the **root** user.

你好，我是使用root用户执行kk程序的，config-sample.yaml里面使用的用户不是root，这样会有影响吗，我看官方文档也没写要求config里面需要使用root用户

**Comment by nsdsb123** [comment]
> You might be using the **scapp** user for the installation. Kubekey requires root privileges during installation. You can try installing it using the **root** user.

你好，我是使用root用户执行kk程序的，config-sample.yaml里面使用的用户不是root，这样会有影响吗，我看官方文档也没写要求config里面需要使用root用户

**Comment by littleBlackHouse** [comment]
Based on my logs, it appears that the permission settings are fine.
You can execute the `umask` command on the node to check if it is set to 022.

**Comment by yisampi** [comment]
the same question for me

**Comment by yisampi** [comment]
> ### Your current KubeKey version
> 3.0.7
> 
> ### Describe this feature
> 使用kk安装k8s集群过程中，scp initOS.sh到各个节点时报错permission denied，包括master本身也是失败，检查过文件目录权限没问题，config不是使用密钥的形式，使用的是密码登录
> 
> ### Describe the solution you'd like
> 请问如何解决
> 
> ### Additional information
> _No response_

the same question for me

**Comment by littleBlackHouse** [comment]
> Based on your logs, it appears that the permission settings are fine.
> You can execute the `umask` command on the node to check if it is set to 022.

Is this configuration also correct?

**Comment by wenwenxiong** [comment]
yes, i meet the same error

**Comment by wenwenxiong** [comment]
sudo -E /bin/bash -c "mkdir -p /opt/cni/bin && chown kube -R /opt/cni"
14:56:53 CST command: [master1]
sudo -E /bin/bash -c "mkdir -p /var/lib/calico && chown kube -R /var/lib/calico"
14:56:53 CST command: [master2]
sudo -E /bin/bash -c "mkdir -p /opt/cni/bin && chown kube -R /opt/cni"
14:56:53 CST command: [master3]
sudo -E /bin/bash -c "mkdir -p /opt/cni/bin && chown kube -R /opt/cni"
14:56:53 CST command: [master1]
sudo -E /bin/bash -c "mkdir -p /var/lib/etcd && chown etcd -R /var/lib/etcd"
14:56:53 CST command: [master2]
sudo -E /bin/bash -c "mkdir -p /var/lib/calico && chown kube -R /var/lib/calico"
14:56:53 CST command: [master3]
sudo -E /bin/bash -c "mkdir -p /var/lib/calico && chown kube -R /var/lib/calico"
14:56:53 CST command: [master2]
sudo -E /bin/bash -c "mkdir -p /var/lib/etcd && chown etcd -R /var/lib/etcd"
14:56:53 CST command: [master3]
sudo -E /bin/bash -c "mkdir -p /var/lib/etcd && chown etcd -R /var/lib/etcd"
14:56:53 CST command: [master1]
sudo -E /bin/bash -c "if [ -d /tmp/kubekey ]; then rm -rf /tmp/kubekey ;fi && mkdir -m 777 -p /tmp/kubekey"
14:56:53 CST command: [master2]
sudo -E /bin/bash -c "if [ -d /tmp/kubekey ]; then rm -rf /tmp/kubekey ;fi && mkdir -m 777 -p /tmp/kubekey"
14:56:53 CST command: [master3]
sudo -E /bin/bash -c "if [ -d /tmp/kubekey ]; then rm -rf /tmp/kubekey ;fi && mkdir -m 777 -p /tmp/kubekey"
14:56:53 CST command: [master1]
sudo -E /bin/bash -c "hostnamectl set-hostname master1 && sed -i '/^127.0.1.1/s/.*/127.0.1.1      master1/g' /etc/hosts"
14:56:53 CST command: [master2]
sudo -E /bin/bash -c "hostnamectl set-hostname master2 && sed -i '/^127.0.1.1/s/.*/127.0.1.1      master2/g' /etc/hosts"
14:56:53 CST command: [master3]
sudo -E /bin/bash -c "hostnamectl set-hostname master3 && sed -i '/^127.0.1.1/s/.*/127.0.1.1      master3/g' /etc/hosts"
14:56:53 CST success: [master1]
14:56:53 CST success: [master2]
14:56:53 CST success: [master3]
14:56:53 CST [ConfigureOSModule] Generate init os script
14:56:53 CST scp local file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master3/initOS.sh to remote /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:56:53 CST message: [master3]
scp file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master3/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:56:53 CST retry: [master3]
14:56:53 CST scp local file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master1/initOS.sh to remote /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:56:53 CST message: [master1]
scp file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master1/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:56:53 CST retry: [master1]
14:56:53 CST scp local file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master2/initOS.sh to remote /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:56:53 CST message: [master2]
scp file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master2/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:56:53 CST retry: [master2]
14:56:58 CST scp local file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master1/initOS.sh to remote /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:56:58 CST message: [master1]
scp file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master1/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:56:58 CST retry: [master1]
14:56:58 CST scp local file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master2/initOS.sh to remote /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:56:58 CST message: [master2]
scp file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master2/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:56:58 CST retry: [master2]
14:56:58 CST scp local file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master3/initOS.sh to remote /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:56:58 CST message: [master3]
scp file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master3/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:56:58 CST retry: [master3]
14:57:03 CST scp local file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master2/initOS.sh to remote /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:57:03 CST message: [master2]
scp file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master2/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:57:03 CST scp local file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master1/initOS.sh to remote /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:57:03 CST message: [master1]
scp file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master1/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:57:03 CST scp local file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master3/initOS.sh to remote /tmp/kubekey/usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:57:03 CST message: [master3]
scp file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master3/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
14:57:03 CST failed: [master2]
14:57:03 CST failed: [master1]
14:57:03 CST failed: [master3]
error: Pipeline[InitRegistryPipeline] execute failed: Module[ConfigureOSModule] exec failed:
failed: [master2] [GenerateScript] exec failed after 3 retires: scp file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master2/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
failed: [master1] [GenerateScript] exec failed after 3 retires: scp file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master1/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied
failed: [master3] [GenerateScript] exec failed after 3 retires: scp file /home/mep/MEC-D-5.0.7-b-20230731/kubernetes-v2.1.0/01-k8s-install/kubekey/master3/initOS.sh to remote /usr/local/bin/kube-scripts/initOS.sh failed: permission denied

**Comment by wenwenxiong** [comment]
root@master1:/home/mep# umask
0022
root@master1:/home/mep# exit
exit
mep@master1:~$ umask
0002

**Comment by wenwenxiong** [comment]
how to fix it ?

**Comment by nsdsb123** [comment]
> how to fix it ?

我一开始用账号密码形式解决不了，后面配置文件用配置密钥路径就可以了
