### ISSUE TITLE
 Installation of additional components

### ISSUE THREAD

**Issue by Nello-Angelo** [kubesphere/kubekey#1912]
### Describe this feature

https://github.com/kubernetes-sigs/metrics-server
https://github.com/acassen/keepalived

### Describe the solution you'd like

add the ability to install and configure keepalived and metrics-server

**Comment by lbrigman124** [comment]
These can easily be added via the addons section.  I have done this with the metrics server:
`
  addons:
  - name: namespaces
    sources:
      yaml:
        path:
        - charts/namespaces.yaml
  - name: nfs-client
    namespace: storage
    sources:
    sources:
      yaml:
        path:
        - charts/nfs-storage.yaml
  - name: metrics
    namespace: kube-system
    sources:
      yaml:
        path:
        - charts/metrics.yaml
`
In my case, I took helm charts and templated them out to file to commit to my git repo.
The could just have easily use the helm chart directly which was what I originally did during my testing.

**Comment by Nello-Angelo** [comment]
https://github.com/kubesphere/kubekey/blob/master/docs/addons.md
