### ISSUE TITLE
生成apiserver证书时，能否添加指定的域名？

### ISSUE THREAD

**Issue by Macrow** [kubesphere/kubekey#1921]
### Your current KubeKey version

3.0.8

### Describe this feature

使用其他工具远程访问k8s集群，需要验证apiserver的tls证书，此证书没有绑定自定义的域名

### Describe the solution you'd like

能否在初始化集群或者重新生成证书时，添加指定的域名，将域名加入到的apiserver证书中

**Comment by pixiake** [comment]
This is supported.
https://github.com/kubesphere/kubekey/blob/583bb0cae296c30b4a85b4f20f643c4c0634af8d/cmd/kk/apis/kubekey/v1alpha2/kubernetes_types.go#L32

**Comment by Macrow** [comment]
好的，谢谢！
