### ISSUE TITLE
registry.cn-beijing.aliyuncs.com/kubesphereio/etcd:v3.5.6 not foud

### ISSUE THREAD

**Issue by wongearl** [kubesphere/kubekey#1942]
### What is version of KubeKey has the issue?

master

### What is your os environment?

ubuntu20.04

### A clear and concise description of what happend.

使用kk创建集群，etcd的类型设置为kubeadm,报错日志如下：
`error: Pipeline[CreateClusterPipeline] execute failed: Module[PullModule] exec failed: 
failed: [master1] [PullImages] exec failed after 3 retries: pull image failed: Failed to exec command: sudo -E /bin/bash -c "env PATH=$PATH crictl pull registry.cn-beijing.aliyuncs.com/kubesphereio/etcd:v3.5.6 --platform amd64" 
E0802 14:11:28.360919    7311 remote_image.go:238] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"registry.cn-beijing.aliyuncs.com/kubesphereio/etcd:v3.5.6\": failed to resolve reference \"registry.cn-beijing.aliyuncs.com/kubesphereio/etcd:v3.5.6\": registry.cn-beijing.aliyuncs.com/kubesphereio/etcd:v3.5.6: not found" image="registry.cn-beijing.aliyuncs.com/kubesphereio/etcd:v3.5.6"
FATA[0000] pulling image: rpc error: code = NotFound desc = failed to pull and unpack image "registry.cn-beijing.aliyuncs.com/kubesphereio/etcd:v3.5.6": failed to resolve reference "registry.cn-beijing.aliyuncs.com/kubesphereio/etcd:v3.5.6": registry.cn-beijing.aliyuncs.com/kubesphereio/etcd:v3.5.6: not found: Process exited with status 1
`

### Additional information

应该是仓库没有上传镜像，registry.cn-beijing.aliyuncs.com/kubesphereio/etcd:v3.5.6，麻烦推一下，谢谢

**Comment by pixiake** [comment]
Done

**Comment by LinuxSuRen** [comment]
Thanks for your time.

![image](https://github.com/kubesphere/kubekey/assets/1450685/5c4f629d-75b7-49cd-9f39-b4de5b933c9f)
