### ISSUE TITLE
E: Version '' for 'docker-ce' was not found

### ISSUE THREAD

**Issue by HeathKang** [kubesphere/kubekey#200]
# issue:
I used `Ubuntu 20.04` and can't install docker-ce and show these messages:
```
Reading package lists... Done
+ apt-cache madison docker-ce
+ + + head -n 1
grepcut -d   -f 4
 19.03.8
+ sh -c apt-get install -y -q docker-ce=
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '' for 'docker-ce' was not found: Process exited with status 100  node=
```
# research
I do a little research for this and find this: https://github.com/kubesphere/kubekey/blob/d12ad37ef41028721b8a0aa701390853b818af4f/scripts/docker-install.sh#L317
Then I run `apt-cache madison docker-ce` show these:
```
 docker-ce | 5:19.03.12~3-0~ubuntu-focal | https://mirrors.aliyun.com/docker-ce/linux/ubuntu focal/stable amd64 Packages
 docker-ce | 5:19.03.11~3-0~ubuntu-focal | https://mirrors.aliyun.com/docker-ce/linux/ubuntu focal/stable amd64 Packages
 docker-ce | 5:19.03.10~3-0~ubuntu-focal | https://mirrors.aliyun.com/docker-ce/linux/ubuntu focal/stable amd64 Packages
 docker-ce | 5:19.03.9~3-0~ubuntu-focal | https://mirrors.aliyun.com/docker-ce/linux/ubuntu focal/stable amd64 Packages
```
Maybe there were no docker-ce 19.03.8 in **ubuntu -focal-20.04**.

**Comment by FeynmanZhou** [comment]
You can install Docker yourself, and ubuntu 20.04 is not officially supported in the [list](https://github.com/kubesphere/kubekey#linux-distributions)

**Comment by HeathKang** [comment]
changed Ubuntu to 18.04 finally
