### ISSUE TITLE
kk helm error (ubuntu18.04 )

### ISSUE THREAD

**Issue by LiuG-lynx** [kubesphere/kubekey#207]
kk helm error (ubuntu18.04 )

` TASK [common : Kubesphere | Check openldap] ************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm list -n kubesphere-system | grep \"ks-openldap\"\n", "delta": "0:00:00.051361", "end": "2020-08-16 01:02:32.373425", "msg": "non-zero return code", "rc": 1, "start": "2020-08-16 01:02:32.322064", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

TASK [common : Kubesphere | Deploy openldap] ***********************************
changed: [localhost]

TASK [common : Kubesphere | Load old openldap data] ****************************
skipping: [localhost]

TASK [common : Kubesphere | Check openldap-ha status] **************************
skipping: [localhost]

TASK [common : Kubesphere | Get openldap-ha pod list] **************************
skipping: [localhost]

TASK [common : Kubesphere | Get old openldap data] *****************************
skipping: [localhost]

TASK [common : Kubesphere | Migrating openldap data] ***************************
skipping: [localhost]

TASK [common : Kubesphere | Disable old openldap] ******************************
skipping: [localhost]

TASK [common : Kubesphere | Restart openldap] **********************************
skipping: [localhost]

TASK [common : KubeSphere | Restarting ks-account] *****************************
skipping: [localhost]

TASK [common : Kubesphere | import openldap status] ****************************
changed: [localhost]

TASK [common : Kubesphere | Getting minio installation files] ******************
changed: [localhost] => (item=minio-ha)

TASK [common : Kubesphere | Creating manifests] ********************************
changed: [localhost] => (item={'name': 'custom-values-minio', 'file': 'custom-values-minio.yaml'})

TASK [common : Kubesphere | Check minio] ***************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm list -n kubesphere-system | grep \"ks-minio\"\n", "delta": "0:00:00.044618", "end": "2020-08-16 01:02:40.581411", "msg": "non-zero return code", "rc": 1, "start": "2020-08-16 01:02:40.536793", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring `

I don't know how to deal with this problem

`root@ks-0001:~# /usr/local/bin/helm list -n kubesphere-system

NAME            NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ks-openldap     kubesphere-system       1               2020-08-16 01:02:32.950596626 +0800 CST deployed        openldap-ha-0.1.0       1.0        
ks-redis        kubesphere-system       1               2020-08-16 01:02:28.102819545 +0800 CST deployed        redis-ha-3.9.0          5.0.5    `

**Comment by FeynmanZhou** [comment]
Where did you install it?

**Comment by LiuG-lynx** [comment]
huaweicloud

**Comment by FeynmanZhou** [comment]
Try:

```
kubectl get sc
kubectl get pvc
```

**Comment by LiuG-lynx** [comment]
`root@ks-0001:~# kubectl get sc
NAME                        PROVISIONER                                       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
glusterfs                   kubernetes.io/glusterfs                           Delete          Immediate              true                   31m
huaweicloud-sfs (default)   cluster.local/nfs-client-nfs-client-provisioner   Delete          Immediate              true                   31m
local                       openebs.io/local                                  Delete          WaitForFirstConsumer   false                  31m
rbd                         ceph.com/rbd                                      Delete          Immediate              true                   31m
root@ks-0001:~# kubectl get pvc
No resources found in default namespace.
root@ks-0001:~# `

**Comment by FeynmanZhou** [comment]
Sorry, try this cmd with all ns
```
kubectl get pvc --all-namespaces
```

**Comment by LiuG-lynx** [comment]
![image](https://user-images.githubusercontent.com/29352057/90318153-1e378c00-df61-11ea-9b29-ee029d424a8e.png)

**Comment by rayzhou2017** [comment]
It seems the storage problem

**Comment by Forest-L** [comment]
@LiuG-lynx  Whether the stored client is installed?

**Comment by LiuG-lynx** [comment]
Yes, I can see all the nodes installed nfs client in KK @Forest-L

**Comment by Forest-L** [comment]
You can try mount -t nfs <serverip>:<serverPath> <clientPat>, such as:
mount -t nfs 192.**.**.**:/nfsdatas /tmp/nfsdata

**Comment by Forest-L** [comment]
Have you resolved your issues, @LiuG-lynx  ? Please let me know if you have any other questions or close this issue.

**Comment by LiuG-lynx** [comment]
I have closed the issue
