### ISSUE TITLE
Updates for Kubernetes versions

### ISSUE THREAD

**Issue by lbrigman124** [kubesphere/kubekey#2128]
### Your current KubeKey version

3.0.13

### Describe this feature

When can we expect a new version of kubekey to support newer versions of Kubernetes.
There is an open bug saying that 1.28.X cannot be installed due to missing SHA256 value.

### Describe the solution you'd like

Updates to kubekey to the latest released version of Kubernetes.

If that isn't possible by the current developers, then a write-up in the docs about how to allow others to submit a PR to
do the update.

**Comment by pixiake** [comment]
The master branch contains the latest version of Kubernetes, which is automatically submitted as a pull request through actions.
https://github.com/kubesphere/kubekey/blob/master/.github/workflows/kubernetes-auto-support.yaml
https://github.com/kubesphere/kubekey/blob/master/version/components.json

If you need to install k8s v1.18+，you can build kk from the master branch or use 3.1.0-alpha.7
https://github.com/kubesphere/kubekey/releases/tag/v3.1.0-alpha.7
