### ISSUE TITLE
DevOps project description is missing after upgrade

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubekey#215]
![image](https://user-images.githubusercontent.com/22350668/90393443-59ea6700-e0c3-11ea-9f25-b0171e2bbc30.png)

**Comment by shaowenchen** [comment]
fixed
![image](https://user-images.githubusercontent.com/43693241/90468819-e0498c00-e149-11ea-9924-e0afd7bb2ab9.png)

/kind need-to-verify

**Comment by huanggze** [comment]
verified
