### ISSUE TITLE
Sonarqube report is missing

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubekey#216]
Before upgrade:

![image](https://user-images.githubusercontent.com/22350668/90393597-a6ce3d80-e0c3-11ea-914c-c8b9404de5f1.png)

After upgrade:

![image](https://user-images.githubusercontent.com/22350668/90393628-b2b9ff80-e0c3-11ea-91b6-cb86223fc9ce.png)

**Comment by shaowenchen** [comment]
There is not sonarqube config in kubesphere-config comfigmap after Sonarqube.

@pixiake

**Comment by pixiake** [comment]
https://github.com/kubesphere/ks-installer/pull/1064

**Comment by huanggze** [comment]
not fixed

**Comment by huanggze** [comment]
@shaowenchen

**Comment by shaowenchen** [comment]
```bash
project_pipeline_sonar_handler.go:99] [ServiceError:404] GET http://ks-jenkins.kubesphere-devops-system.svc/job/project-eglbxgn2brmr/job/sonarqube/job/github/api/json:404 <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /job/project-eglbxgn2brmr/job/sonarqube/job/github/api/json. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>
```

not http://ks-jenkins.kubesphere-devops-system.svc/job/project-eglbxgn2brmr/job/sonarqube/job/github/api/json ,but http://ks-jenkins.kubesphere-devops-system.svc/job/project-eglbxgn2brmr/job/github/job/sonarqube/api/json

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/90863376-7f2bed80-e3c1-11ea-925a-51f7d1b600f2.png)

fixed
