### ISSUE TITLE
Pipeline setting is overwritten

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubekey#217]
These params were overwritten: 

- repo trigger
- swallow clone
- clone timeout

Before upgrade:

![image](https://user-images.githubusercontent.com/22350668/90394086-923e7500-e0c4-11ea-9c24-7ac25cae55fa.png)

![image](https://user-images.githubusercontent.com/22350668/90394123-a6827200-e0c4-11ea-92e8-5ce3959aafeb.png)

After upgrade:

![image](https://user-images.githubusercontent.com/22350668/90394114-a2eeeb00-e0c4-11ea-8599-cc72092bfc91.png)

**Comment by huanggze** [comment]
Only Github pipeline has this issue

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/90484267-83110300-e168-11ea-878c-15a6eee5e54e.png)

git_clone_option:
        depth: 1
        shallow: false
        timeout: 30

shallow default is false

@harrisonliu5

**Comment by shaowenchen** [comment]
The problems of `repo trigger` will also occur in 2.1.1, which fixed in the upgrade script.

**Comment by harrisonliu5** [comment]
done

**Comment by huanggze** [comment]
verified
