### ISSUE TITLE
Failed to download cri-dockerd binary

### ISSUE THREAD

**Issue by qihuang0** [kubesphere/kubekey#2178]
### What is version of KubeKey has the issue?

"v3.1.0-alpha.4.144-66bc55e8fc55ec"

### What is your os environment?

centos

### A clear and concise description of what happend.

failed: [LocalHost] [DownloadBinaries] exec failed after 1 retries: Failed to download cri-dockerd binary: curl -L -o /data/kubekey/bin/kubekey/cri-dockerd/0.3.10/amd64/cri-dockerd-0.3.10.tgz https://kubernetes-release.pek3b.qingstor.com/cri-dockerd/releases/download/v0.3.10/cri-dockerd-0.3.10.amd64.tgz error: SHA256 no match. 46bc9594c634e1bae9b4c7dfaba1b4b34917b407c3275c08425f93d193024dab not equal 3e19ef525e02d2d1dfd42e8d661ee45b4bc8a49a6dcafd8baa578bdb3a23aeb6

**Comment by pixiake** [comment]
cri-docker v0.3.10 been updated, which caused a change in sha256. The issue has been fixed and you can now use v3.1.0-rc.1.
https://github.com/kubesphere/kubekey/pull/2169
https://github.com/kubesphere/kubekey/releases/tag/v3.1.0-rc.1
