### ISSUE TITLE
single-branch svn setting is missing

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubekey#219]
![image](https://user-images.githubusercontent.com/22350668/90394975-3a087280-e0c6-11ea-8293-76caf2408c3a.png)

![image](https://user-images.githubusercontent.com/22350668/90394981-3f65bd00-e0c6-11ea-8d46-e84d378ff67e.png)

**Comment by rayzhou2017** [comment]
Is this caused by upgrading? Do you have the upgrading env info?

**Comment by huanggze** [comment]
Guess it is caused by upgrading. I had a SVN pipeline with proper server url. credentials. etc. But after upgrade, they are all missing

**Comment by huanggze** [comment]
verified
