### ISSUE TITLE
devops credentials are reset to empty

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubekey#221]
![image](https://user-images.githubusercontent.com/22350668/90395274-de8ab480-e0c6-11ea-8591-fcebcfcd7659.png)

![image](https://user-images.githubusercontent.com/22350668/90395367-02e69100-e0c7-11ea-9a11-5197bb63611b.png)

![image](https://user-images.githubusercontent.com/22350668/90395401-142f9d80-e0c7-11ea-9ac2-5677930c5506.png)

![image](https://user-images.githubusercontent.com/22350668/90395434-227db980-e0c7-11ea-9f5e-9c847a870d90.png)

**Comment by shaowenchen** [comment]
This is expected and can't affect the usage of users.

We can't get secrets data from Jenkins.

**Comment by rayzhou2017** [comment]
Is it similar we can't open the secret in console? But it does exist in Jenkins and users still can use them, right?

**Comment by shaowenchen** [comment]
> Is it similar we can't open the secret in console? But it does exist in Jenkins and users still can use them, right?

Yes, we can't save the secret value in Kubesphere DB in 2.1.1.  Jenkins doesn't allow to get the plaintext secret. But, users still can use them.
