### ISSUE TITLE
Could not resolve host: kubernetes-release.pek3b.qingstor.com

### ISSUE THREAD

**Issue by feifeifeimoon** [kubesphere/kubekey#2215]
### What is version of KubeKey has the issue?

kk version: &version.Info{Major:"3", Minor:"1", GitVersion:"v3.1.1", GitCommit:"7a184f786b02bec20d5534af137896f50e510396", GitTreeState:"clean", BuildDate:"2024-04-16T04:28:43Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### What is your os environment?

Ubuntu 20.04

### A clear and concise description of what happend.

Could not resolve host: kubernetes-release.pek3b.qingstor.com
<img width="605" alt="image" src="https://github.com/kubesphere/kubekey/assets/26476500/ec67a901-a925-430e-a330-9d388217875c">

### Relevant log output

```shell
`downloading amd64 kubeadm v1.23.15 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: kubernetes-release.pek3b.qingstor.com
17:54:13 CST message: [LocalHost]
Failed to download kubeadm binary: curl -L -o /root/kubekey/kube/v1.23.15/amd64/kubeadm https://kubernetes-release.pek3b.qingstor.com/release/v1.23.15/bin/linux/amd64/kubeadm error: exit status 6 
17:54:13 CST failed: [LocalHost]
error: Pipeline[CreateClusterPipeline] execute failed: Module[NodeBinariesModule] exec failed: 
failed: [LocalHost] [DownloadBinaries] exec failed after 1 retries: Failed to download kubeadm binary: curl -L -o /root/kubekey/kube/v1.23.15/amd64/kubeadm https://kubernetes-release.pek3b.qingstor.com/release/v1.23.15/bin/linux/amd64/kubeadm error: exit status 6 `
```

**Comment by zheng1** [comment]
<img width="599" alt="截屏2024-04-19 15 14 44" src="https://github.com/kubesphere/kubekey/assets/4156721/9a383848-f8ca-494e-8c3a-1ec52f57ddb9">
I tested it, this address is worked, maybe there is something wrong with your local dns, you can try to change a dns server.
