### ISSUE TITLE
export KKZONE=cn 无法下载安装

### ISSUE THREAD

**Issue by kayNdragon** [kubesphere/kubekey#2222]
### Your current KubeKey version

v3.0.13

### Describe this feature

Rocky Linux 9.3 (Blue Onyx)
kubernetes 版本在export KKZONE=cn下无法安装

### Describe the solution you'd like

kubernetes 版本在export KKZONE=cn下无法安装

### Additional information

export KKZONE=cn
[root@k8s-master01 kk]# ./kk create cluster -f config.yaml

 _   __      _          _   __
| | / /     | |        | | / /
| |/ / _   _| |__   ___| |/ /  ___ _   _
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

17:27:58 CST [GreetingsModule] Greetings
17:27:58 CST message: [k8s-node04]
Greetings, KubeKey!
17:27:58 CST message: [k8s-node01]
Greetings, KubeKey!
17:27:58 CST message: [k8s-master01]
Greetings, KubeKey!
17:27:58 CST message: [k8s-node02]
Greetings, KubeKey!
17:27:58 CST message: [k8s-node03]
Greetings, KubeKey!
17:27:58 CST success: [k8s-node04]
17:27:58 CST success: [k8s-node01]
17:27:58 CST success: [k8s-master01]
17:27:58 CST success: [k8s-node02]
17:27:58 CST success: [k8s-node03]
17:27:58 CST [NodePreCheckModule] A pre-check on nodes
17:27:59 CST success: [k8s-node03]
17:27:59 CST success: [k8s-master01]
17:27:59 CST success: [k8s-node02]
17:27:59 CST success: [k8s-node04]
17:27:59 CST success: [k8s-node01]
17:27:59 CST [ConfirmModule] Display confirmation form
+--------------+------+------+---------+----------+-------+-------+---------+-----------+--------+----------+------------+------------+-------------+------------------+--------------+
| name         | sudo | curl | openssl | ebtables | socat | ipset | ipvsadm | conntrack | chrony | docker   | containerd | nfs client | ceph client | glusterfs client | time         |
+--------------+------+------+---------+----------+-------+-------+---------+-----------+--------+----------+------------+------------+-------------+------------------+--------------+
| k8s-master01 | y    | y    | y       | y        | y     | y     | y       | y         | y      | 20.10.10 | v1.4.11    | y          |             |                  | CST 17:27:59 |
| k8s-node01   | y    | y    | y       | y        | y     | y     | y       | y         | y      | 20.10.10 | v1.4.11    | y          |             |                  | CST 17:27:59 |
| k8s-node02   | y    | y    | y       | y        | y     | y     | y       | y         | y      | 20.10.10 | v1.4.11    | y          |             |                  | CST 17:27:59 |
| k8s-node03   | y    | y    | y       | y        | y     | y     | y       | y         | y      | 20.10.10 | v1.4.11    | y          |             |                  | CST 17:27:59 |
| k8s-node04   | y    | y    | y       | y        | y     | y     | y       | y         | y      | 20.10.10 | v1.4.11    | y          |             |                  | CST 17:27:59 |
+--------------+------+------+---------+----------+-------+-------+---------+-----------+--------+----------+------------+------------+-------------+------------------+--------------+

This is a simple check of your environment.
Before installation, ensure that your machines meet all requirements specified at
https://github.com/kubesphere/kubekey#requirements-and-recommendations

Continue this installation? [yes/no]: yes
17:28:00 CST success: [LocalHost]
17:28:00 CST [NodeBinariesModule] Download installation binaries
17:28:00 CST message: [localhost]
downloading amd64 kubeadm v1.23.17 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: kubernetes-release.pek3b.qingstor.com
17:28:00 CST message: [LocalHost]
Failed to download kubeadm binary: curl -L -o /data/service/kk/kubekey/kube/v1.23.17/amd64/kubeadm https://kubernetes-release.pek3b.qingstor.com/release/v1.23.17/bin/linux/amd64/kubeadm error: exit status 6
17:28:00 CST failed: [LocalHost]
error: Pipeline[CreateClusterPipeline] execute failed: Module[NodeBinariesModule] exec failed:
failed: [LocalHost] [DownloadBinaries] exec failed after 1 retries: Failed to download kubeadm binary: curl -L -o /data/service/kk/kubekey/kube/v1.23.17/amd64/kubeadm https://kubernetes-release.pek3b.qingstor.com/release/v1.23.17/bin/linux/amd64/kubeadm error: exit status 6

**Comment by JackloveJam** [comment]
重新执行吧。
我安装时候也是遇到各种报错，反复执行了好几次安装命令才安装好。

**Comment by LinuxSuRen** [comment]
可能是当时的网络环境不稳定，刚测试上面的文件是可以下载的。有问题了，可以再提供更多信息。
