### ISSUE TITLE
中国地区安装优化

### ISSUE THREAD

**Issue by LIANGQI0811** [kubesphere/kubekey#2242]
### Your current KubeKey version

centos 7

### Describe this feature

我在本机安装体验了一下，感觉由于大部分软件包都是在国外的服务器上，整个安装时间约12个小时，导致安装体验非常差。
能否在kk的命令行添加一个参数，这样从头到尾我都能直接从中国拉包

### Describe the solution you'd like

./kk --registry=https://registry.npmmirror.com 
这样就可以指定仓库地址，可以体验快速的安装

**Comment by liangzai006** [comment]
国内地区安装，可以执行 export KKZONE=cn  在进行安装

**Comment by LIANGQI0811** [comment]
已经用了这个命令，依旧装了12个小时，那天又死活配置不了vpn

**Comment by LinuxSuRen** [comment]
```
./kk --registry=https://registry.npmmirror.com/
```

安装包不是 NPM 包，您提供的这种方式是没法解决的。如有更具体的错误信息，欢迎提供。

**Comment by LIANGQI0811** [comment]
我知道不是npm的包，我只是给你举个例子。无论何种形式的包，它都有国内的镜像。你们能否把所有涉及到的包全部上传至国内镜像网站，另外给kk提供命令行切换镜像服务器地址的能力

**Comment by calvinyv** [comment]
> 我知道不是npm的包，我只是给你举个例子。无论何种形式的包，它都有国内的镜像。你们能否把所有涉及到的包全部上传至国内镜像网站，另外给kk提供命令行切换镜像服务器地址的能力
Here is the translation of the provided text:

---

Refer to these links:
- [Manifest and Artifact](https://github.com/kubesphere/kubekey/blob/master/docs/manifest_and_artifact.md)
- [Manifest Example](https://github.com/kubesphere/kubekey/blob/master/docs/manifest-example.md)

Create your own installation package that meets your requirements. The goal of kk is to help users deploy diverse Kubernetes environments by enriching its flexibility. However, it does not intend to manage dependencies for multiple versions of various operating systems. Therefore, it offers the M2A (manifest to artifact) feature, allowing users to customize installation packages based on their environments.
