### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by hawking-lab** [kubesphere/kubekey#227]
ERRO[19:38:18 CST] Failed to add worker to cluster: Failed to exec command: sudo -E /bin/sh -c "/usr/local/bin/kubeadm join  lb.kubesphere.local:6443 --token svewm8.mkgzgu9o8aoyy7rq     --discovery-token-ca-cert-hash sha256:cf045a0007860f74a586e1fdc454730897d5287167ddbac78f87dba767406828"
W0817 19:38:29.763537   12954 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR Port-10250]: Port 10250 is in use
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

**Comment by pixiake** [comment]
`[ERROR Port-10250]: Port 10250 is in use`    
Port occupied.  
Try to execute `./kk delete cluster -f xxx.yaml `

**Comment by hawking-lab** [comment]
I try it again  same error.

**Comment by pixiake** [comment]
Try to execute `systemctl stop kubelet` on the error machine.
