### ISSUE TITLE
ks-gateway and ks-account still exist

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubekey#229]
![image](https://user-images.githubusercontent.com/22350668/90465516-1b47c180-e142-11ea-9a59-2994d3d8f8b1.png)

**Comment by pixiake** [comment]
Yes, not deleted just deactivated.

**Comment by rayzhou2017** [comment]
Is it possible users may activate it?

**Comment by pixiake** [comment]
I've changed deactivate to delete.

https://github.com/kubesphere/ks-installer/pull/1063

**Comment by huanggze** [comment]
not fixed @pixiake
