### ISSUE TITLE
devops viewer can delete pipelines

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubekey#230]
`regular3` was devops reporter before upgrading and is viewer now. The problem is that `regular3` can delete now

![image](https://user-images.githubusercontent.com/22350668/90465711-842f3980-e142-11ea-82d6-0a7176ca8607.png)

![image](https://user-images.githubusercontent.com/22350668/90465778-b04aba80-e142-11ea-83db-be8bb5cef083.png)

**Comment by wansir** [comment]
@huanggze  What is the workspace role of regular3?

**Comment by huanggze** [comment]
workspace self provisioner

https://github.com/kubesphere/kubekey/issues/231

**Comment by huanggze** [comment]
verified
