### ISSUE TITLE
Workspace regular became workspace self provisioner after upgrading?

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubekey#231]
![image](https://user-images.githubusercontent.com/22350668/90465953-1a635f80-e143-11ea-9cdd-ad08e6255568.png)

![image](https://user-images.githubusercontent.com/22350668/90465902-facc3700-e142-11ea-8e24-25aeb0f4056c.png)

![image](https://user-images.githubusercontent.com/22350668/90465867-e425e000-e142-11ea-8cee-c2f9230f946d.png)

**Comment by wansir** [comment]
As expected, ws-regular can create projects before upgrade.
