### ISSUE TITLE
kubesphere update error

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubekey#232]
There is a kubesphere cluster with version 2.1.1, the k8s version is 1.15.3. It has 3 masters and 3 nodes, the os is ubuntu 18.04.  Update the k8s to 1.18.3, and update kubesphere to 3.0.0, there are some problems during the upgrade:

1. Upgrade failed, need to re-run the upgrade procedure
![image](https://user-images.githubusercontent.com/53003665/90467608-2cdf9800-e147-11ea-8f00-c72f844a09dc.png)

2. There is an error in ks-installer
`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install elasticsearch-logging /kubesphere/kubesphere/elasticsearch/elasticsearch-1.22.1.tgz -f /kubesphere/kubesphere/elasticsearch/custom-values-elasticsearch.yaml --namespace kubesphere-logging-system\n", "delta": "0:01:41.119652", "end": "2020-08-17 17:32:47.233896", "msg": "non-zero return code", "rc": 1, "start": "2020-08-17 17:31:06.114244", "stderr": "Error: UPGRADE FAILED: cannot patch \"elasticsearch-logging-discovery\" with kind StatefulSet: StatefulSet.apps \"elasticsearch-logging-discovery\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden", "stderr_lines": ["Error: UPGRADE FAILED: cannot patch \"elasticsearch-logging-discovery\" with kind StatefulSet: StatefulSet.apps \"elasticsearch-logging-discovery\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"], "stdout": "", "stdout_lines": []}`

3. The applications in the App Store do not upgrade.
![image](https://user-images.githubusercontent.com/53003665/90467894-da52ab80-e147-11ea-93da-02646fe280e5.png)

/assign @pixiake 
/assign @huanggze 
/assign @zheng1

**Comment by zheng1** [comment]
@pixiake  rerun release-app job after upgrade

**Comment by pixiake** [comment]
https://github.com/kubesphere/ks-installer/pull/1061

add rerun release-app job after upgrade

**Comment by wanjunlei** [comment]
verfied
/close
