### ISSUE TITLE
kubekey升级calico3.27.3后与内核不兼容问题

### ISSUE THREAD

**Issue by flyrun9527** [kubesphere/kubekey#2326]
### What is version of KubeKey has the issue?

3.1.1

### What is your os environment?

centos7.9 内核 5.4.273

### A clear and concise description of what happend.

calico不兼容配置问题，要么降低calico至3.26  或者等3.28.1发布 或者 关闭xdp
https://github.com/projectcalico/calico/issues/4984

**Comment by lkad** [comment]
我用的kk version: &version.Info{Major:"3", Minor:"1", GitVersion:"v3.1.5", GitCommit:"8347277057bf9f84e89fec174019a675d582b23b", GitTreeState:"clean", BuildDate:"2024-08-15T11:55:51Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"} 版本安装 1.28.4 的版本 使用的 calico的版本是3.27.3也是有这个bug .ubuntu 20.04 .
nux node1 5.4.0-189-generic #209-Ubuntu SMP Fri Jun 7 14:05:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
我看到官方已经https://github.com/projectcalico/calico/issues/8856 已经修复了 需要3.27.4和3.28.1 希望官方能修复下
