### ISSUE TITLE
custom full permission role are not migrated correctly

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubekey#245]
Before upgrade:
![image](https://user-images.githubusercontent.com/22350668/90853710-80531f80-e3ad-11ea-8d06-53ffb7ee9840.png)

![image](https://user-images.githubusercontent.com/22350668/90853726-8943f100-e3ad-11ea-81c3-4cce567496f3.png)

![image](https://user-images.githubusercontent.com/22350668/90853743-91039580-e3ad-11ea-801d-388a21088e4d.png)

**Comment by wansir** [comment]
Custom roles are upgraded according to the policy rules. Checking all does not mean that you have all permissions after upgrading,  only matching rules will be upgraded.

upgrade rules:

https://github.com/kubesphere/ks-upgrade/blob/master/pkg/globalrolebindings/globalrolebindings.go#L113-L230
https://github.com/kubesphere/ks-upgrade/blob/master/pkg/rolebindings/rolebindings.go#L182-L347
