### ISSUE TITLE
新增海光C86物理机节点时，calico-node无法启动

### ISSUE THREAD

**Issue by fzziii** [kubesphere/kubekey#2479]
### What is version of KubeKey has the issue?

v3.1.6

### What is your os environment?

Ubuntu 20.04.6 LTS"

### A clear and concise description of what happend.

kubesphere v3.4.1  kubernetes 1.23.10 

新增一海光C86机器节点时，发生calico-node无法启动，容器无错误日志，事件无明显的异常描述
其他非国产化机器无该问题

![image](https://github.com/user-attachments/assets/46cb0b9c-43a8-451e-bfef-a4b0280a2dae)

![image](https://github.com/user-attachments/assets/3ed665b8-aa12-4c52-b4ce-dc8f0585acd9)

**Comment by fzziii** [comment]
![image](https://github.com/user-attachments/assets/72739827-c2ac-44b7-86ab-5245ae1fb60b)

**Comment by zlianzhuang** [comment]
calico 版本换成 3.37.3

**Comment by fzziii** [comment]
> calico 版本换成 3.37.3

![image](https://github.com/user-attachments/assets/dbf899dc-d5c7-4e59-b7da-c81cd30c6579)
calico 官方最新的 没有这个版本

![image](https://github.com/user-attachments/assets/cd181bea-f851-4618-a73b-9a357cc5ba35)

![image](https://github.com/user-attachments/assets/fd2612fc-2bf5-4e38-96ea-cd8d9fda1da1)
kubesphere仓库也没有这个版本

**Comment by pixiake** [comment]
v3.27.3

> > calico 版本换成 3.37.3
> 
> ![image](https://private-user-images.githubusercontent.com/39999647/398524088-dbf899dc-d5c7-4e59-b7da-c81cd30c6579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMDc5MjMsIm5iZiI6MTczNTEwNzYyMywicGF0aCI6Ii8zOTk5OTY0Ny8zOTg1MjQwODgtZGJmODk5ZGMtZDVjNy00ZTU5LWI3ZGEtYzgxY2QzMGM2NTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA2MjAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNDBhYWI0OTdlYzdhOTlkNGZiMTE2YWZmZmJjOWM3NzEzNTVkZDNmYWNiYTdmOWU1NWFlODkxN2VlNzU5YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AMouuxHWVdfO2yUzA0W2QSEXy_1aurCtrP8fQRyassY) calico 官方最新的 没有这个版本
> 
> ![image](https://private-user-images.githubusercontent.com/39999647/398524344-cd181bea-f851-4618-a73b-9a357cc5ba35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMDc5MjMsIm5iZiI6MTczNTEwNzYyMywicGF0aCI6Ii8zOTk5OTY0Ny8zOTg1MjQzNDQtY2QxODFiZWEtZjg1MS00NjE4LWE3M2ItOWEzNTdjYzViYTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA2MjAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Y2E3Zjg1Njk3ODJmM2RjNGEwOWVjYTExNGI4MmZiZTlmNWY3MGU4Y2MwN2JhYmQ4ZmVmNzczYzlkMzc3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zBt5RZpNkPWWKSMIMzd0TYCxI1vXC7rmY2zMownHH74)
> 
> ![image](https://private-user-images.githubusercontent.com/39999647/398524224-fd2612fc-2bf5-4e38-96ea-cd8d9fda1da1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMDc5MjMsIm5iZiI6MTczNTEwNzYyMywicGF0aCI6Ii8zOTk5OTY0Ny8zOTg1MjQyMjQtZmQyNjEyZmMtMmJmNS00ZTM4LTk2ZWEtY2Q4ZDlmZGExZGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA2MjAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZDg1ODc0YmZlNDdhNjY0ZGEwZmRkYzRjZDllZTQ3MjA1ZjM1NTljNWUwZWM2YTFlOGFjZGFlOThkMTQwOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MR4Re_yG86AOA-dG82hW37XND_BMuqlwKX594qvzL0I) kubesphere仓库也没有这个版本

**Comment by fzziii** [comment]
node镜像 v3.27.4   ---> v3.27.3   解决
