### ISSUE TITLE
离线部署报错failed: [LocalHost] [GenerateRegistryCerts] exec failed after 1 retries: unable to sign certificate: must specify a CommonName

### ISSUE THREAD

**Issue by dollygaga** [kubesphere/kubekey#2481]
### Describe this feature

离线安装报错

### Describe the solution you'd like

./kk init registry -f config-sample.yaml -a kubernetes-offline.tar.gz
[certs] Using existing ca certificate authority
08:32:56 CST message: [LocalHost]
unable to sign certificate: must specify a CommonName
08:32:56 CST failed: [LocalHost]
error: Pipeline[InitRegistryPipeline] execute failed: Module[InitRegistryModule] exec failed: 
failed: [LocalHost] [GenerateRegistryCerts] exec failed after 1 retries: unable to sign certificate: must specify a CommonName

### Additional information

主机名都已经核对了，不知道这个要怎么配置

**Comment by liangzai006** [comment]
看看配置

**Comment by dollygaga** [comment]
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 172.21.45.110, internalAddress: 172.21.45.110, user: root, password: "Vcdn_2024@214"}
  - {name: node2, address: 172.21.45.248, internalAddress: 172.21.45.248, user: root, password: "Vcdn_2024@214"}
  roleGroups:
    etcd:
    - node1
    control-plane: 
    - node1
    worker:
    - node1
    - node2
    registry:
    - node1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.29.0
    clusterName: cluster.local
#    autoRenewCerts: true
#    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    type: harbor
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []

> 看看配置

**Comment by liangzai006** [comment]
registry:
type: harbor
privateRegistry: ""
namespaceOverride: ""
registryMirrors: []
insecureRegistries: []  
registry相关内容都没有填写    https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md  这是参考配置。

**Comment by dollygaga** [comment]
> registry: type: harbor privateRegistry: "" namespaceOverride: "" registryMirrors: [] insecureRegistries: [] registry相关内容都没有填写 https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md 这是参考配置。

感谢，确实，加上privateRegistry: node1  就可以了
