### ISSUE TITLE
Qingcloud CSI is not upgraded when upgrading from 1.16.7/KS2.1.1->1.18.6/KS3.0.0

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubekey#249]
Install KS2.1.1 will install old version of Qingcloud CSI, upgraded with kk to KS 3.0.0, Qingcloud CSI is not upgraded, this will result to user creation ReadWriteMany(RWX) volume pending in KS 3.0.0
![image](https://user-images.githubusercontent.com/38337958/90872075-a63cec00-e3ce-11ea-9720-7bec77bb6f24.png)

**Comment by pixiake** [comment]
Qingcloud-csi's documentation can be refered to for update qingcloud-csi.
https://github.com/yunify/qingcloud-csi

**Comment by Ma-Dan** [comment]
Run the following commands to upgrade Qingcloud CSI manually
```
git clone https://github.com/yunify/qingcloud-csi.git
cd qingcloud-csi/
git checkout v1.1.1
kubectl delete -f  deploy/disk/kubernetes/releases/qingcloud-csi-disk-v1.1.1.yaml
kubectl delete sc csi-qingcloud

helm repo add test https://charts.kubesphere.io/test
helm install test/csi-qingcloud --name-template csi-qingcloud --namespace kube-system \
--set config.qy_access_key_id=KEY,config.qy_secret_access_key=SECRERT,config.zone=ZONE
```

**Comment by Ma-Dan** [comment]
Manual qingcloud-csi upgrading verified
