### ISSUE TITLE
在用kk安装Kubernetes的时候，在给节点打标签的时候，失败会退出整个流程。个人认为打标签并不是一个非常重要的操作，即使失败也不应该退出流程。

### ISSUE THREAD

**Issue by cool-ops** [kubesphere/kubekey#269]
Run 'kubectl get nodes' on the control-plane to see this node join the cluster.
ERRO[12:25:53 CST] Failed to add worker label: Failed to exec command: sudo -E /bin/sh -c "/usr/local/bin/kubectl label node node2 node-role.kubernetes.io/worker=" 
The connection to the server localhost:8080 was refused - did you specify the right host or port?: Process exited with status 1  node=172.17.100.122
ERRO[12:25:53 CST] Failed to add worker label: Failed to exec command: sudo -E /bin/sh -c "/usr/local/bin/kubectl label node node1 node-role.kubernetes.io/worker=" 
The connection to the server localhost:8080 was refused - did you specify the right host or port?: Process exited with status 1  node=172.17.100.121

**Comment by cool-ops** [comment]
我重跑一次，虽然还是没有打标成功，但是这次成功跳过了。

**Comment by pixiake** [comment]
What OS are you using?  Does `/root/.kube/config` exist?

**Comment by FeynmanZhou** [comment]
Sorry, English only in GitHub. For Chinese questions, please go to [China Forum](https://kubesphere.com.cn/forum/).
