### ISSUE TITLE
dependency for installation

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#282]
I remember socat and conntrack are needed only for K8s >= 1.18. But here it seems for all versions. 
![Screen Shot 2020-09-03 at 10 17 21 AM](https://user-images.githubusercontent.com/28859385/92063893-d755ed00-edce-11ea-9ca4-7aeac8f495d0.png)

**Comment by Sherlock113** [comment]
Just confirmed with @pixiake 

If the Kubernetes version >= 1.18, socat and conntrack are required, and ebtables and ipset are optional but high recommended.

If the Kubernetes version < 1.18, all these four components are optional but highly recommended.

I will update the doc accordingly.
