### ISSUE TITLE
install Allinon 3.0 faild 

### ISSUE THREAD

**Issue by m84686660** [kubesphere/kubekey#306]
Push /tmp/kubekey/v1.18.6/amd64/kubeadm to 192.168.100.246:/tmp/kubekey/kubeadm   Failed
ERRO[12:41:46 CST] Failed to sync binaries: open /tmp/kubekey/v1.18.6/amd64/kubeadm: no such file or directory  node=192.168.100.246
WARN[12:41:46 CST] Task failed ...                              
WARN[12:41:46 CST] error: interrupted by error                  
Error: Failed to install kube binaries: interrupted by error

Monitoring this directory deletes files such as Kubeadm, causing the push command to fail!

**Comment by m84686660** [comment]
help

**Comment by pixiake** [comment]
Do you execute the installation in `/tmp` directory ?

**Comment by m84686660** [comment]
Yes,path is /tmp/kk

**Comment by m84686660** [comment]
i move 'kk' to other path is insatll over!
