### ISSUE TITLE
kk cannot remove master node

### ISSUE THREAD

**Issue by JadeRing** [kubesphere/kubekey#317]
nothing happend when i run command  "./kk delete node master4 -f ks-config.yaml"

**Comment by Forest-L** [comment]
@JadeRing  Are you sure to delete master?

**Comment by JadeRing** [comment]
Yes, I'am sure
master is very important to the cluster, so High availability of the master is essential
Hope to increase the expansion, shrinkage and replacement function of the master

**Comment by Forest-L** [comment]
If you do need to remove the master, follow these instructions
```
kubectl drain <masterName>  --delete-local-data --ignore-daemonsets
kubectl delete node <>masterName
```

**Comment by hustlibraco** [comment]
I do same operation, and get nothing. maybe it should print some tips when debug flag enabled.
