### ISSUE TITLE
kk on arm64 etcd error

### ISSUE THREAD

**Issue by sbhnet** [kubesphere/kubekey#331]
kk create cluster -f config.yaml -y 
 
docker logs -f etcd1
2020-10-09 09:02:07.027019 E | etcdmain: etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=arm64 set.

kk create cluster (all-in-one) ok.

**Comment by sbhnet** [comment]
need add ETCD_UNSUPPORTED_ARCH=arm64 to /etc/etcd.env

**Comment by pixiake** [comment]
You need to set `arch` in the host configuration.
example:
```
- {name: node1, address: 172.16.0.2, internalAddress: 172.16.0.2, password: 123456, arch: arm64}
```

**Comment by sbhnet** [comment]
I've modified the source code and compiled it. etcd.go and default
