### ISSUE TITLE
arm64 calico version

### ISSUE THREAD

**Issue by sbhnet** [kubesphere/kubekey#332]
default version   v3.15.1
Warning  Failed            38s (x4 over 5m44s)   kubelet, node1     Failed to pull image "calico/kube-controllers:v3.15.1": rpc error: code = Unknown desc = context canceled
  Warning  Failed            38s (x4 over 5m44s)   kubelet, node1     Error: ErrImagePull
  Normal   BackOff           1s (x7 over 5m44s)    kubelet, node1     Back-off pulling image "calico/kube-controllers:v3.15.1"
  Warning  Failed            1s (x7 over 5m44s)    kubelet, node1     Error: ImagePullBackOff

pls use DefaultCalicoVersion       = "v3.16.3" for arch arm64

**Comment by pixiake** [comment]
Thanks, upgrading calico is in our plans.

I see that `calico/kube-controllers:v3.15.1` for arm64 should be available for download.
https://hub.docker.com/layers/calico/kube-controllers/v3.15.1/images/sha256-f6f2b1fea497a620cc19c2382fed58828917b99ff578d7081ca3c80e2ca209fb?context=explore

**Comment by sbhnet** [comment]
OK，wait new calico version.
