### ISSUE TITLE
using config to create cluster with 3 master failed

### ISSUE THREAD

**Issue by ZhangShiy** [kubesphere/kubekey#343]
It reported an error “When the environment has at least three masters, You must set the value of the LB address.”， but LB address was configured.

error was found in the following code：
	clusterCfg.RoleGroups = cfg.RoleGroups
	hostGroups, err := clusterCfg.GroupHosts()
	if err != nil {
		return nil, nil, err
	}
clusterCfg.ControlPlaneEndpoint  is empty

**Comment by FeynmanZhou** [comment]
Can you attach the yaml configuration of yours?

**Comment by ZhangShiy** [comment]
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: ick-m01, address: 172.17.0.117, internalAddress: 172.17.0.117, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: ick-m02, address: 172.17.0.104, internalAddress: 172.17.0.104, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: ick-m03, address: 172.17.0.160, internalAddress: 172.17.0.160, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: ick-n01, address: 172.17.0.91 , internalAddress: 172.17.0.91 , privateKeyPath: "~/.ssh/id_rsa"}
  - {name: ick-n02, address: 172.17.0.207, internalAddress: 172.17.0.207, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: ick-n03, address: 172.17.0.84 , internalAddress: 172.17.0.84 , privateKeyPath: "~/.ssh/id_rsa"}
  - {name: ick-n04, address: 172.17.0.206, internalAddress: 172.17.0.206, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: ick-n05, address: 172.17.0.30 , internalAddress: 172.17.0.30 , privateKeyPath: "~/.ssh/id_rsa"}
  roleGroups:
    etcd:
    - ick-m01
    - ick-m02
    - ick-m03
    master:
    - ick-m01
    - ick-m02
    - ick-m03
    worker:
    - ick-n01
    - ick-n02
    - ick-n03
    - ick-n04
    - ick-n05
  controlPlaneEndpoint:
    domain: lb.iapcloud.local
    address: "172.17.0.161"
    port: 6443
  kubernetes:
    version: v1.18.6
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []

**Comment by pixiake** [comment]
Do you build the binary by yourself ？

**Comment by ZhangShiy** [comment]
> Do you build the binary by yourself ？Which branch ？
yes,  master branch
