### ISSUE TITLE
Error with message 'configmap "kubesphere-config" not found'

### ISSUE THREAD

**Issue by xmapst** [kubesphere/kubekey#344]
ks-apiserver/ks-controller-manager
```
Events:
  Type     Reason       Age                   From                   Message
  ----     ------       ----                  ----                   -------
  Normal   Scheduled    5m33s                 default-scheduler      Successfully assigned kubesphere-system/ks-apiserver-66c548fcd8-pxqzp to linux-master
  Warning  FailedMount  3m30s                 kubelet, linux-master  Unable to attach or mount volumes: unmounted volumes=[kubesphere-config], unattached volumes=[kubesphere-token-kpq57 docker-sock ks-router-config kubesphere-config host-time]: timed out waiting for the condition
  Warning  FailedMount  83s (x10 over 5m32s)  kubelet, linux-master  MountVolume.SetUp failed for volume "kubesphere-config" : configmap "kubesphere-config" not found
  Warning  FailedMount  76s                   kubelet, linux-master  Unable to attach or mount volumes: unmounted volumes=[kubesphere-config], unattached volumes=[host-time kubesphere-token-kpq57 docker-sock ks-router-config kubesphere-config]: timed out waiting for the condition
```

**Comment by Forest-L** [comment]
@xmapst   What to store？ look at the `kubectl get sc`

**Comment by pixiake** [comment]
It seems that the installation is not complete.
If you have any more questions, please go to the forum: https://kubesphere.com.cn/forum

**Comment by Forest-L** [comment]
Have you resolved your issues, @xmapst  ? Please let me know if you have any other questions or close this issue.

**Comment by LinuxSuRen** [comment]
/retitle Error with message 'configmap "kubesphere-config" not found'

**Comment by xmapst** [comment]
> Have you resolved your issues, @xmapst ? Please let me know if you have any other questions or close this issue.

我放弃了

**Comment by kahramanakyil** [comment]
![image](https://github.com/kubesphere/kubekey/assets/9756639/8ce4334a-c746-43d3-8254-3c9172c06173)
![image](https://github.com/kubesphere/kubekey/assets/9756639/0779fbe5-f477-472b-bc26-72ad61ebdd1f)
![image](https://github.com/kubesphere/kubekey/assets/9756639/4f7d3e77-5e15-466e-95eb-64e57e4d72be)
[ks-installer-bc998985d-9xcxr.log](https://github.com/kubesphere/kubekey/files/14342981/ks-installer-bc998985d-9xcxr.log)

**Comment by dl-devops-esds** [comment]
This process takes time to set up, so please wait until the installation is complete. Once finished, you'll be able to see all the KubeSphere resources in your cluster. In my case, it took 15 minutes. In the meantime, you can monitor the installation progress.
