### ISSUE TITLE
Report error if docker already installed and not running

### ISSUE THREAD

**Issue by liucy1983** [kubesphere/kubekey#347]
在部署的时候，程序会直接调用pkg/container-engine/docker/docker.go中的InstallerDocker方法，然后在每台Node中执行installDockerOnNode方法，内容如下。

```go
func installDockerOnNode(mgr *manager.Manager, _ *kubekeyapi.HostCfg) error {
	dockerConfig, err := GenerateDockerConfig(mgr)
	if err != nil {
		return err
	}
	dockerConfigBase64 := base64.StdEncoding.EncodeToString([]byte(dockerConfig))
	output, err1 := mgr.Runner.ExecuteCmd(fmt.Sprintf("sudo -E /bin/sh -c \"if [ -z $(which docker) ] || [ ! -e /var/run/docker.sock ]; then curl https://kubernetes.pek3b.qingstor.com/tools/kubekey/docker-install.sh | sh && systemctl enable docker && echo %s | base64 -d > /etc/docker/daemon.json && systemctl reload docker; fi\"", dockerConfigBase64), 0, false)
	if err1 != nil {
		return errors.Wrap(errors.WithStack(err1), fmt.Sprintf("Failed to install docker:\n%s", output))
	}

	return nil
}

```

然后里面执行了一个Shell命令，去掉sudo以后，实际执行的内容为
```bash
if [ -z $(which docker) ] || [ ! -e /var/run/docker.sock ]; then
  curl https://kubernetes.pek3b.qingstor.com/tools/kubekey/docker-install.sh | sh && 
    systemctl enable docker && 
    echo %s | base64 -d > /etc/docker/daemon.json && 
    systemctl reload docker; 
fi
```

在if中的判断条件为，找不到docker命令，或是/var/run/docker.sock文件不存在，就去安装Docker并启动服务。
这会导致在，用户事先安装了Docker，但服务没启动时，逻辑判断不正确，程序又去重试安装Docker，报错。

**Comment by Forest-L** [comment]
@liucy1983 
* 1. Are you using the Master branch or the Release-1.0 installation package?
* 2. When the Docker service is not started, the /var/run/docker.sock file does not exist.
* 3. The docker.sock file judgment was not added in the Release-1.0 Installation package.
* 4. You can start docker manually first, systemctl enable docker; systemctl restart docker.

**Comment by liucy1983** [comment]
1. yes
2. when docker-ce installed and not running, `[ -z $(which docker) ] || [ ! -e /var/run/docker.sock ]` means cannot find docker command or /var/run/docker.sock not exists, the result of this expression is true, then error will occurred in docker installation progress.
3. https://github.com/kubesphere/kubekey/blob/release-1.0/pkg/container-engine/docker/docker.go
4. yes i can, but kubekey should fix this issue.

**Comment by LinuxSuRen** [comment]
I met the same problem. I was wondering if @liucy1983  you can rewrite the issue title with English.

/kind feature
