### ISSUE TITLE
with-storage参数不存在

### ISSUE THREAD

**Issue by wushifeng** [kubesphere/kubekey#353]
发布文档中 https://kubesphere.io/docs/installing-on-linux/introduction/multioverview/ 有如下的说明
./kk create config --with-storage localVolume

**下载发布版本执行**
# ./kk version
version.BuildInfo{Version:"v1.0.0", GitCommit:"ab0dc4a9ad922f697af6de6de696d07507bdcb83", GitTreeState:"clean", GoVersion:"go1.14.7"}
# ./kk create config --with-storage localVolumeError: unknown flag: --with-storage
Usage:
  kk create config [flags]

Flags:
  -f, --filename string          Specify a configuration file path
      --from-cluster             Create a configuration based on existing cluster
  -h, --help                     help for config
      --kubeconfig string        Specify a kubeconfig file
      --name string              Specify a name of cluster object (default "sample")
      --with-kubernetes string   Specify a supported version of kubernetes
      --with-kubesphere          Deploy a specific version of kubesphere (default v3.0.0)

Global Flags:
      --debug   Print detailed information (default true)

unknown flag: --with-storage

下载了代码https://github.com/kubesphere/kubekey master分支，也搜不到这个选项

应该是代码bug吧？
这样的话，存储设置只能手工修改了【https://kubesphere.io/docs/installing-on-linux/introduction/storage-configuration】

**Comment by pixiake** [comment]
The document is old and will be updated in the near future.
For now you can refer to the readme:
https://github.com/kubesphere/kubekey/blob/master/README.md

Storage plugins can be configured using addons (If not configured, localVolume is used by default):
https://github.com/kubesphere/kubekey/blob/master/docs/addons.md
https://kubesphere.io/docs/installing-on-linux/introduction/storage-configuration

**Comment by wushifeng** [comment]
的确看到了说明
建议：文档这块也分下版本，如没有发布文档的就看不到，这样初次接触的人就不会产生这种问题。
看不到比看到一个旧的文档给人的感觉可是差别很大
