### ISSUE TITLE
v3.0.0离线安装多节点错误

### ISSUE THREAD

**Issue by wushifeng** [kubesphere/kubekey#355]
按照如下的文档和文件包
https://kubesphere.com.cn/forum/d/2034-kubekey-kubesphere-v300
https://kubesphere-installer.pek3b.qingstor.com/offline/v3.0.0/kubesphere-all-v3.0.0-offline-linux-amd64.tar.gz

**按照发布建议选择了版本如下：**
kubernetes: v1.17.9
kubesphere: v3.0.0

**虚拟机配置和kubesphere的配置如下**
https://gitee.com/wushifeng/kubesphere-offline/blob/master/1-2mnodes/Vagrantfile
https://gitee.com/wushifeng/kubesphere-offline/blob/master/1-2mnodes/kubesphere3_cfg.yaml

**出错信息如下**
【详细的安装步骤和错误信息在 https://gitee.com/wushifeng/kubesphere-offline/blob/master/1-2mnodes/install.sh 这个地方有记录】

kube-system         calico-node-kjgx9                             0/1     CrashLoopBackOff   7          13m
kube-system         metrics-server-98546f9bd-w922k                0/1     CrashLoopBackOff   6          11m
kube-system         openebs-ndm-r6ckp                             0/1     CrashLoopBackOff   7          13m

kubectl logs -n kube-system calico-node-kjgx9
2020-11-03 00:21:38.147 [INFO][8] startup/startup.go 374: Hit error connecting to datastore - retry error=Get https://10.233.0.1:443/api/v1/nodes/foo: dial tcp 10.233.0.1:443: connect: connection refused

kubectl logs -n kube-system metrics-server-98546f9bd-w922k 
Get https://10.233.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 10.233.0.1:443: connect: connection refused

kubectl logs -n kube-system openebs-ndm-r6ckp 
Get https://10.233.0.1:443/api?timeout=32s: dial tcp 10.233.0.1:443: connect: connection refused

kubectl describe pods -n kube-system openebs-ndm-r6ckp 
  node-disk-manager:
    Container ID:  docker://b0c59109a566e4af5aec124a1b42dd7bbc24104fadcba12af5e705071875d279
    Image:         dockerhub.kubekey.local/kubesphere/node-disk-manager:0.5.0
    Image ID:      docker-pullable://dockerhub.kubekey.local/kubesphere/node-disk-manager@sha256:3359bf4ab78ca961b321d291158b98d384021c34fdc9c7d62d82c0c4ea5b3bea
    Port:          <none>
    Host Port:     <none>
    Args:
      -v=4
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 03 Nov 2020 00:37:38 +0000
      Finished:     Tue, 03 Nov 2020 00:37:38 +0000
    Ready:          False
    Restart Count:  10
    Liveness:       exec [pgrep ndm] delay=30s timeout=1s period=60s #success=1 #failure=3
    Environment:
      NAMESPACE:          kube-system (v1:metadata.namespace)
      NODE_NAME:           (v1:spec.nodeName)
      SPARSE_FILE_DIR:    /var/openebs/sparse
      SPARSE_FILE_SIZE:   10737418240
      SPARSE_FILE_COUNT:  0
    Mounts:
      /host/node-disk-manager.config from config (ro,path="node-disk-manager.config")
      /host/proc from procmount (ro)
      /run/udev from udev (rw)
      /var/openebs/ndm from basepath (rw)
      /var/openebs/sparse from sparsepath (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from openebs-maya-operator-token-ngcnh (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      openebs-ndm-config
    Optional:  false
  udev:
    Type:          HostPath (bare host directory volume)
    Path:          /run/udev
    HostPathType:  Directory
  procmount:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:  Directory
  basepath:
    Type:          HostPath (bare host directory volume)
    Path:          /var/openebs/ndm
    HostPathType:  DirectoryOrCreate
  sparsepath:
    Type:          HostPath (bare host directory volume)
    Path:          /var/openebs/sparse
    HostPathType:  
  openebs-maya-operator-token-ngcnh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  openebs-maya-operator-token-ngcnh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                   From                       Message
  ----     ------     ----                  ----                       -------
  Normal   Scheduled  29m                   default-scheduler          Successfully assigned kube-system/openebs-ndm-r6ckp to kubesphere-node1
  Normal   Pulled     28m (x4 over 28m)     kubelet, kubesphere-node1  Successfully pulled image "dockerhub.kubekey.local/kubesphere/node-disk-manager:0.5.0"
  Normal   Created    28m (x4 over 28m)     kubelet, kubesphere-node1  Created container node-disk-manager
  Normal   Started    28m (x4 over 28m)     kubelet, kubesphere-node1  Started container node-disk-manager
  Normal   Pulling    27m (x5 over 29m)     kubelet, kubesphere-node1  Pulling image "dockerhub.kubekey.local/kubesphere/node-disk-manager:0.5.0"
  Warning  BackOff    4m2s (x121 over 28m)  kubelet, kubesphere-node1  Back-off restarting failed container

kubectl exec -n kube-system -it openebs-ndm-r6ckp sh

$ sudo docker ps -a|grep openebs-ndm
e4ed5470d4a2        dockerhub.kubekey.local/kubesphere/node-disk-manager   "/usr/local/bin/entr…"   About a minute ago   Exited (1) About a minute ago                         k8s_node-disk-manager_openebs-ndm-r6ckp_kube-system_052d7e42-8d8b-4eb2-b8d3-66e897dc7109_11
2410fa1bba4d        dockerhub.kubekey.local/kubesphere/pause:3.1           "/pause"                 32 minutes ago       Up 32 minutes                                         k8s_POD_openebs-ndm-r6ckp_kube-system_052d7e42-8d8b-4eb2-b8d3-66e897dc7109_0
[vagrant@kubesphere-node1 ~]$ sudo docker log
login   logout  logs    
[vagrant@kubesphere-node1 ~]$ sudo docker logs k8s_node-disk-manager_openebs-ndm-r6ckp_kube-system_052d7e42-8d8b-4eb2-b8d3-66e897dc7109_11
[entrypoint.sh] launching ndm process.
I1103 00:42:48.812592       6 commands.go:64] Starting Node Device Manager Daemon...
I1103 00:42:48.812684       6 commands.go:65] Version Tag : v0.5.0
I1103 00:42:48.812690       6 commands.go:66] GitCommit : 63ca87a283e5feea87821c4f96c8b38c038343e3
Get https://10.233.0.1:443/api?timeout=32s: dial tcp 10.233.0.1:443: connect: connection refused

**Comment by Forest-L** [comment]
@wushifeng Is the firewall off?

**Comment by wushifeng** [comment]
$ systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)

关闭了防火墙也一样的问题，主要是这个 https://10.233.0.1:443/ 不能访问，这个是哪个的服务呢

**Comment by wushifeng** [comment]
看下这个日志，2个虚拟机的信息不太一样，都是这个default  kubernetes  服务不行，估计还是多机的安装问题吧？

**=在主节点**
[vagrant@kubesphere-dev ~]$ k get svc -A
NAMESPACE              NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default                kubernetes                  ClusterIP   10.233.0.1      <none>        443/TCP                  104m
kube-system            coredns                     ClusterIP   10.233.0.3      <none>        53/UDP,53/TCP,9153/TCP   104m
kube-system            metrics-server              ClusterIP   10.233.60.82    <none>        443/TCP                  102m
kubernetes-dashboard   dashboard-metrics-scraper   ClusterIP   10.233.33.184   <none>        8000/TCP                 92m
kubernetes-dashboard   kubernetes-dashboard        ClusterIP   10.233.49.239   <none>        443/TCP                  92m
[vagrant@kubesphere-dev ~]$ curl -k https://10.233.0.1:443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
[vagrant@kubesphere-dev ~]$ k get po -A
NAMESPACE              NAME                                          READY   STATUS              RESTARTS   AGE
kube-system            calico-kube-controllers-677cbc8557-l8vqx      1/1     Running             0          109m
kube-system            calico-node-rxv9z                             0/1     Running             33         109m
kube-system            calico-node-wkcmp                             1/1     Running             0          109m
kube-system            coredns-79878cb9c9-bssf2                      1/1     Running             0          109m
kube-system            coredns-79878cb9c9-sxwjq                      1/1     Running             0          109m
kube-system            kube-apiserver-kubesphere-dev                 1/1     Running             0          109m
kube-system            kube-controller-manager-kubesphere-dev        1/1     Running             0          109m
kube-system            kube-proxy-8kxpq                              1/1     Running             0          109m
kube-system            kube-proxy-dltfz                              1/1     Running             0          109m
kube-system            kube-scheduler-kubesphere-dev                 1/1     Running             0          109m
kube-system            metrics-server-98546f9bd-2j6t6                0/1     CrashLoopBackOff    25         107m
kube-system            nodelocaldns-5bppl                            1/1     Running             0          109m
kube-system            nodelocaldns-gxpqb                            1/1     Running             0          109m
kube-system            openebs-localpv-provisioner-5cd9579c5-p5tt9   1/1     Running             0          109m
kube-system            openebs-ndm-kbssp                             0/1     CrashLoopBackOff    26         109m
kube-system            openebs-ndm-operator-6656f85b86-25dn7         1/1     Running             1          109m
kube-system            openebs-ndm-pqlt6                             1/1     Running             0          109m
kubernetes-dashboard   dashboard-metrics-scraper-557f68956f-79jjf    0/1     ContainerCreating   0          97m
kubernetes-dashboard   kubernetes-dashboard-669cb44fb8-xl27v         0/1     ContainerCreating   0          97m
kubesphere-system      ks-installer-78745765f5-x7dbr                 1/1     Running             0          109m

[vagrant@kubesphere-dev ~]$ k logs -n kube-system openebs-ndm-kbssp
[entrypoint.sh] launching ndm process.
I1103 09:11:18.974940       6 commands.go:64] Starting Node Device Manager Daemon...
I1103 09:11:18.975086       6 commands.go:65] Version Tag : v0.5.0
I1103 09:11:18.975092       6 commands.go:66] GitCommit : 63ca87a283e5feea87821c4f96c8b38c038343e3
Get https://10.233.0.1:443/api?timeout=32s: dial tcp 10.233.0.1:443: connect: connection refused

**=在工作节点**
[vagrant@kubesphere-node1 ~]$ k get svc -A
NAMESPACE              NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default                kubernetes                  ClusterIP   10.233.0.1      <none>        443/TCP                  110m
kube-system            coredns                     ClusterIP   10.233.0.3      <none>        53/UDP,53/TCP,9153/TCP   110m
kube-system            metrics-server              ClusterIP   10.233.60.82    <none>        443/TCP                  108m
kubernetes-dashboard   dashboard-metrics-scraper   ClusterIP   10.233.33.184   <none>        8000/TCP                 98m
kubernetes-dashboard   kubernetes-dashboard        ClusterIP   10.233.49.239   <none>        443/TCP                  98m

[vagrant@kubesphere-node1 ~]$ curl -k https://10.233.0.1:443
curl: (7) Failed connect to 10.233.0.1:443; 拒绝连接

**Comment by Forest-L** [comment]
@wushifeng Are all the firewalls turned off? 443 is the firewall port

**Comment by wushifeng** [comment]
2个节点的防火墙都关了，一直不能用
我使用vagrant销毁重建的，所以环境配置肯定不是问题
具体的设置在这里
https://gitee.com/wushifeng/kubesphere-offline/blob/master/1-2mnodes/Vagrantfile
这个不知道什么原因，可以给我留信息，可以远程我的环境排查[ wushifengcn@qq.com 这个邮箱]

时间等不及，我试了下sealos安装k8s，然后只部署kubesphere，遇到一个更奇怪的问题
**kubesphere的镜像如果是联网下载的，可以正常使用。把这个镜像导出来，离线部署kubesphere出现问题
这个问题的重现步骤：**
https://gitee.com/wushifeng/kubesphere-offline/tree/master/sealos
1 执行 install.sh 通过sealos部署好k8s
2 通过k8s dashboard检查k8s正常了后，执行 install-ks.sh http://192.168.99.10:30880 这个可以正常
3 导入2个节点的镜像
ssh -i private_key -o StrictHostKeyChecking=no root@192.168.99.10 "cd /vagrant/image/; sudo ./saveimg.sh kubesphere-dev"
ssh -i private_key -o StrictHostKeyChecking=no root@192.168.99.10 "cd /vagrant/image/; sudo ./saveimg.sh kubesphere-node1"

vagrant destroy -f 销毁2个节点，离线安装
1 1 执行 install.sh 通过sealos部署好k8s
2 通过k8s dashboard检查k8s正常了后，执行 install-ks.sh ks 执行离线部署kubesphere
k8s dashboard中可以看到所有的service和pod都是绿色，但 http://192.168.99.10:30880 不能访问
查看明细 ks-console这个总是出现如下问题
Containers
 ks-console
Image
 kubesphere/ks-console:v3.0.0

Liveness probe failed: Get http://100.90.171.200:8000/login: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
kubelet kubesphere-dev
spec.containers{ks-console}
看下了2个节点的ipvsadm -Ln 端口也中转了

这个问题应该从哪个方面排查呢，给几个线索吧？ 

【之所以要离线部署，因为我们搞的软件需要在离线环境下用，估计这也是个比较常见的需求吧】

**Comment by Forest-L** [comment]
@wushifeng  Does offline deployment refer to the following documentation?
https://kubesphere.com.cn/forum/d/2034-kubekey-kubesphere-v300

**Comment by wushifeng** [comment]
我最初反馈的就是这个问题，https://kubesphere.com.cn/forum/d/2034-kubekey-kubesphere-v300 参考这个文档，部署2节点启动失败，具体的安装脚本在这个
https://gitee.com/wushifeng/kubesphere-offline/blob/master/1-2mnodes/install.sh

**Comment by wushifeng** [comment]
在sealos安装的k8s基础上离线部署kubesphere服务无法访问，诊断后的原因如下
安装后登录报错
When logon to  http://192.168.99.10:30880/login, the page has following error:
request to http://ks-apiserver.kubesphere-system.svc/oauth/token failed, reason: connect EHOSTUNREACH 10.100.30.86:80

查看如下信息
# kubectl get po -n kubesphere-system -o wide
NAME                                     READY   STATUS    RESTARTS   AGE   IP               NODE               NOMINATED NODE   READINESS GATES
ks-apiserver-7b65577d6c-2wzgt            1/1     Running   0          52m   100.90.171.202   kubesphere-dev     <none>           <none>
ks-console-b4df86d6f-zn4xd               1/1     Running   0          54m   100.90.171.199   kubesphere-dev     <none>           <none>

[root@kubesphere-dev vagrant]# kubectl get svc -n kubesphere-system -o wide
NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE   SELECTOR
ks-apiserver            ClusterIP   10.100.30.86     <none>        80/TCP         55m   app=ks-apiserver,tier=backend,version=v3.0.0
ks-console              NodePort    10.107.234.142   <none>        80:30880/TCP   55m   app=ks-console,tier=frontend,version=v3.0.0


#kubectl describe svc ks-apiserver -n kubesphere-system
selector:          app=ks-apiserver,tier=backend,version=v3.0.0
Type:              ClusterIP
IP:                10.100.30.86
Port:              <unset>  80/TCP
TargetPort:        9090/TCP
Endpoints:         100.90.171.202:9090

#kubectl logs ks-apiserver-7b65577d6c-2wzgt -n kubesphere-system
I1105 02:42:57.179945       1 apiserver.go:232] Start listening on :9090

# ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn

TCP  10.100.30.86:80 rr
  -> 100.90.171.200:9090          Masq    1      0          6

如上课件srevice指向的pod的ip地址不对
It Should be : 100.90.171.202:9090
Why?

手动修改下
Manual change it:
ipvsadm -Ln|grep 100.90.171.202 -A 3 -B 3


ipvsadm -d -t 10.100.30.86:80 -r 100.90.171.202:9090
ipvsadm -D -t 10.100.30.86:80

ipvsadm -Ln|grep '10.100.30.86' -A 2 -B2

ipvsadm -A -t 10.100.30.86:80
ipvsadm -a -t 10.100.30.86:80 -r 100.90.171.202:9090 -m

或者更快捷的方法，ipvsadm -C 全部清理，等待几秒，k8s会自动重建

ipvs的指定是否是属于k8s的功能，如此看来这个问题是k8s的问题还是kubesphere？ 这块的地址分配和ipvs指定关系没有分析过
[修正脚本和说明更新到这 https://gitee.com/wushifeng/kubesphere-offline/tree/master/sealos ]

**Comment by Forest-L** [comment]
Have you resolved your issues, @wushifeng  ? Please let me know if you have any other questions or close this issue.

**Comment by wushifeng** [comment]
Yes, resolved. But manual modify by using ipvsadm -C below.
