### ISSUE TITLE
./kk create安装报错，已重新下载./kk

### ISSUE THREAD

**Issue by aogg** [kubesphere/kubekey#368]
![image](https://user-images.githubusercontent.com/8998031/98558013-e7fb7580-22df-11eb-9eb8-89688cc8d0f4.png)

**Comment by aogg** [comment]
./kk create config --with-kubernetes v1.18.6 --with-kubesphere v3.0.0 -f a.yaml
创建的config.yml

**Comment by Forest-L** [comment]
@aogg   Check the etcd set parameters in a.yaml

**Comment by Forest-L** [comment]
Have you resolved your issues, @aogg  ? Please let me know if you have any other questions or close this issue.

**Comment by LinuxSuRen** [comment]
/retitle Panic due the nil occur with kk create command
