### ISSUE TITLE
kubekey not update CIDR

### ISSUE THREAD

**Issue by xuelangos** [kubesphere/kubekey#383]
delete cluster -f k8s.yaml ;
update CIDR;
kk create cluster;
but,/run/flannel/subnet.env ,not update at first num;
FLANNEL_NETWORK=xxx;that is old CIDR;

**Comment by pixiake** [comment]
You can remove `kubekey/network-plugin.yaml`

**Comment by xuelangos** [comment]
remove？Where should I define CIDR?

**Comment by pixiake** [comment]
Yes, remove this file and a new one will be created according to the configuration, otherwise, the file will be used to create network plugin.
