### ISSUE TITLE
error：Failed to enable kubelet service

### ISSUE THREAD

**Issue by xrjk** [kubesphere/kubekey#393]
version 1.0.1
ERRO[17:10:50 CST] Failed to enable kubelet service: Failed to exec command: sudo -E /bin/sh -c "systemctl enable kubelet && ln -snf /usr/local/bin/kubelet /usr/bin/kubelet"
Failed to execute operation: File exists: Process exited with status 1  node=

**Comment by Forest-L** [comment]
@xrjk  Is the machine clean? You can kubelet logs， such as systemctl status kubelet or journalctl -u kubelet -f.

**Comment by xrjk** [comment]
Dec 09 21:05:56 k8s1 kubelet[27784]: F1209 21:05:56.913365   27784 server.go:199] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Dec 09 21:05:56 k8s1 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Dec 09 21:05:56 k8s1 systemd[1]: Unit kubelet.service entered failed state.
Dec 09 21:05:56 k8s1 systemd[1]: kubelet.service failed.
Dec 09 21:06:07 k8s1 systemd[1]: kubelet.service holdoff time over, scheduling restart.
Dec 09 21:06:07 k8s1 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Dec 09 21:06:07 k8s1 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 09 21:06:07 k8s1 kubelet[27791]: F1209 21:06:07.168886   27791 server.go:199] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Dec 09 21:06:07 k8s1 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Dec 09 21:06:07 k8s1 systemd[1]: Unit kubelet.service entered failed state.
Dec 09 21:06:07 k8s1 systemd[1]: kubelet.service failed.

**Comment by Forest-L** [comment]
Firstly ./kk delete cluster and ./kk create cluster ***

**Comment by xrjk** [comment]
执行了 ./kk delete cluster

**Comment by Forest-L** [comment]
@xrjk  
1. Please provide the operating system you are using.
2. Provide the config-sample.yaml .
3. More kubelet log, such as journalctl -u kubelet -f.

**Comment by d3957** [comment]
systemctl disable kubelet
