### ISSUE TITLE
Investigate: Support install EKS-D with KubeKey

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubekey#397]
We want to add KubeKey (or ks-installer) and KubeSphere to [EKS-D Partner page](https://distro.eks.amazonaws.com/community/partners/) if EKS-D could be installed using kk or integrated with KubeSphere.

**Comment by FeynmanZhou** [comment]
EKS-D includes upstream Kubernetes, which means ks-installer should be naturally supported. From my view, the most important thing is that how to integrate more closely with its CSI and EKS-D's related components.

![image](https://user-images.githubusercontent.com/40452856/102737926-a270a480-4383-11eb-8570-199bca5dc5ac.png)

**Comment by Forest-L** [comment]
EKS-D relies on this tool kOps installation of K8s, and the dependency on AWS is quite strong.
