### ISSUE TITLE
A机器安装B机器的单节点k8s，是不是需要开通etcd的端口，能改为不开通的吗

### ISSUE THREAD

**Issue by aogg** [kubesphere/kubekey#398]
[node1] Downloading image: calico/node:v3.15.1
[node1] Downloading image: calico/pod2daemon-flexvol:v3.15.1
INFO[13:16:09 CST] Generating etcd certs                        
INFO[13:16:10 CST] Synchronizing etcd certs                     
INFO[13:16:10 CST] Creating etcd service                        
INFO[13:16:11 CST] Starting etcd cluster                        
[node1 159.75.213.128] MSG:
Configuration file already exists
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start

**Comment by Forest-L** [comment]
Only one install KubeSphere by kk? No ports need to be opened.

**Comment by FeynmanZhou** [comment]
Closed. If you think this is unresolved, pls reopen it.
