### ISSUE TITLE
Add `-y` flag for delete command

### ISSUE THREAD

**Issue by xiaosuiba** [kubesphere/kubekey#418]
We are integrating kk in our devops solution, automation is important. We found `kk create` has a `-y` flag, which will skip pre-check of the installation, a.k.a perform a quiet install. But `-y` does not exist in `kk delete` context, so we need to do a `yes | kk delete ...` or `echo yes | kk delete...`. That works, but we will be really appreciated if you could add `-y` flag  for `kk delete`.

**Comment by LinuxSuRen** [comment]
So glad to hear that you're using `kk` as part of your solution. I believe your suggestion is very good. I'm looking forward this feature too.

/kind feature

**Comment by pixiake** [comment]
Deleting a cluster is a high-risk operation. If secondary confirmation is skipped, I think there is a risk of mistake operation.
