### ISSUE TITLE
在离线环境下，能否离线安装 Docker?

### ISSUE THREAD

**Issue by wangkuan** [kubesphere/kubekey#442]
如题

**Comment by pixiake** [comment]
https://kubesphere.com.cn/forum/d/2034-kubekey-kubesphere-v300

如果离线包中有对应操作系统的依赖包，是可以离线安装相关以来软件的，不过为了避免依赖问题，建议提前将以来软件装好做成系统镜像。

PS: 中文问题建议到 [ KubeSphere 中文官方论坛](https://kubesphere.com.cn/forum/)发帖提问。
