### ISSUE TITLE
question about the certification when installing k8s with kk

### ISSUE THREAD

**Issue by herotan** [kubesphere/kubekey#454]
请教：
1、默认安装后证书有效期也是1年吗？
2、kk 1.0.1 版本没有./kk certs 参数可用
3、部署的K8S关键服务（kube-api,kube-schedule,kube-control等）全部是通过二进制方式 运行的吗？
谢谢！

**Comment by pixiake** [comment]
Installed using kubeadm, so the control-plane components are containers，and the certificate is valid for 1 year.
v1.1.0-alpha should be able to use ./kk certs.

**Comment by LinuxSuRen** [comment]
/retitle question about the certification when installing k8s with kk

We encourage everyone to communicate in English. It's good for community health.

**Comment by Forest-L** [comment]
https://github.com/kubesphere/kubekey/pull/380
Have you resolved your issues, @herotan  ? Please let me know if you have any other questions or close this issue.

**Comment by 24sama** [comment]
This issue has been inactive, I will close this issue. Feel free to reopen it, if there are any new messages.
/close
