### ISSUE TITLE
err: exit status 1: stderr: package k8s.io/code-generator: build constraints exclude all Go files in go\pkg\mod\k8s.io\code-generator@v0.18.8

### ISSUE THREAD

**Issue by sbhnet** [kubesphere/kubekey#491]
-
package tools
import _ "k8s.io/code-generator“
+
package tools

import (
	_ "k8s.io/code-generator/cmd/client-gen"
	_ "k8s.io/code-generator/cmd/conversion-gen"
	_ "k8s.io/code-generator/cmd/deepcopy-gen"
	_ "k8s.io/code-generator/cmd/defaulter-gen"
	_ "k8s.io/code-generator/cmd/go-to-protobuf"
	_ "k8s.io/code-generator/cmd/import-boss"
	_ "k8s.io/code-generator/cmd/informer-gen"
	_ "k8s.io/code-generator/cmd/lister-gen"
	_ "k8s.io/code-generator/cmd/openapi-gen"
	_ "k8s.io/code-generator/cmd/register-gen"
	_ "k8s.io/code-generator/cmd/set-gen"
)

**Comment by pixiake** [comment]
The following two methods are recommended for build

### Method 1

```shell script
git clone https://github.com/kubesphere/kubekey.git
cd kubekey
./build.sh
```

> Note:
>
> * Docker needs to be installed before building.
> * If you have problem to access `https://proxy.golang.org/`, excute `build.sh -p` instead.

### Method 2

```shell script
git clone https://github.com/kubesphere/kubekey.git
cd kubekey
make binary
```

> Note:
>
> * Docker needs to be installed before building.
