### ISSUE TITLE
How to change the port from 22 to others

### ISSUE THREAD

**Issue by fengnex** [kubesphere/kubekey#494]
如题

**Comment by LinuxSuRen** [comment]
hi @fengnex , thanks for reaching us. I encourage everyone to communicate in English here. If you prefer to use Chinese, please go to the [forum](https://kubesphere.com.cn/forum).

I'll rewrite your issue title in English. Please correct me if it's not accurate.

By the way, I don't understand which port does want to ask. Please consider providing more context and details. Thanks again.

/retitle How to change the port from 22 to others
/kind support

**Comment by fengnex** [comment]
OK， please look at the following error message and you'll find that kk always try to connect to the port 22, which is not opened in the server with ip:10.*.*.* and it actually uses 38022 instead:
ERRO[12:56:25 CST] Failed to connect to 10.*.*.*: could not establish connection to 10.*.*.*:22: dial tcp 10.*.*.*:22: connect: connection refused  node=10.*.*.*
WARN[12:56:25 CST] Task failed ...
WARN[12:56:25 CST] error: interrupted by error

What I wonder is how to specify the actual port number when executing './kk create cluster'. Thanks

**Comment by FeynmanZhou** [comment]
Are you using all-in-one or multi-node installation?

**Comment by fengnex** [comment]
I am using the all-in-one

**Comment by pixiake** [comment]
Turn off the server's firewall.
or
You can change the ssh port by means of a configuration file.

**Comment by fengnex** [comment]
> Turn off the server's firewall.
> or
> You can change the ssh port by means of a configuration file.

The test server does not use the default ssh port 22 for some security reasons, so maybe turning off its firewall is useless.
On changing the ssh port  through a configuration file, could you please provide a detailed example or some concrete tips so that we can try it right now? Thanks first.

**Comment by pixiake** [comment]
> > Turn off the server's firewall.
> > or
> > You can change the ssh port by means of a configuration file.
> 
> The test server does not use the default ssh port 22 for some security reasons, so maybe turning off its firewall is useless.
> On changing the ssh port through a configuration file, could you please provide a detailed example or some concrete tips so that we can try it right now? Thanks first.

1. ./kk create config
2. Modify the configuration file   config-sample.yaml
    https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md
3. ./kk create cluster -f config-sample.yaml

**Comment by 24sama** [comment]
I think this issue could be closed. Feel free to reopen it.

**Comment by Sdzeng** [comment]
Port 22 is the default port of SSH and you need to add the port number after the IP address if your port is different. For example:
`hosts:
  - {name: master, address: 192.168.0.2, internalAddress: 192.168.0.2, port: 8022, user: ubuntu, password: Testing123}
`
