### ISSUE TITLE
ks-installer ImagePullBackOff with ks-installer:v3.1.0

### ISSUE THREAD

**Issue by chenqi4547** [kubesphere/kubekey#507]
Failed to pull image "registry.cn-beijing.aliyuncs.com/kubesphereio/ks-installer:v3.1.0": rpc error: code = Unknown desc = Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/kubesphereio/ks-installer:v3.1.0 not found: manifest unknown: manifest unknown

**Comment by pixiake** [comment]
After the release of 3.1, the relevant images will be pushed to the AliCloud repository, now you can replace the images with `kubespheredev/ks-installer:nightly-202104xx` or `kubespheredev/ks-installer:latest`.

**Comment by LinuxSuRen** [comment]
/retitle ks-installer ImagePullBackOff with ks-installer:v3.1.0
