### ISSUE TITLE
docker daemon.json rewrited when docker first installed, this cause network conflict error

### ISSUE THREAD

**Issue by pyfs** [kubesphere/kubekey#508]
this happens when user's local network addr is "172.17.xxx.xxx" which conflict with docker0 bridge;

before installation, there's bip set in  `/etc/docker/daemon.json`，but rewrite by docker_install.sh ；

do not rewrite user's docker settings or dynmicly modify it instead of full rewrite; it will be more robustic !!!

**Comment by pixiake** [comment]
If docker was already installed on your host,  docker configuration shouldn't be overridden.

**Comment by pyfs** [comment]
> If docker was already installed on your host, docker configuration shouldn't be overridden.

can we have a key in kubekey config file to determine whether rewrite `deamon.json` or not ?

**Comment by pixiake** [comment]
If `/etc/docker/daemon.json` exists on the node, it will not be overwritten.
You can use the master branch code to build or wait for the v1.1.0 version.
