### ISSUE TITLE
There is a problem with kubekey getting the docker version

### ISSUE THREAD

**Issue by yinmin2020** [kubesphere/kubekey#521]
K8S version is 1.20, which is not installed with KK. Docker will be detected when KK is used to upgrade to 1.20.4, but docker is not supported in 1,20, the detection failed, please fix it, thank you
![image](https://user-images.githubusercontent.com/65068467/116512416-929d3a00-a8fa-11eb-9bc0-931ea3faabf5.png)

**Comment by 24sama** [comment]
Can you use the commond `which docker` on your k8s nodes? 
Normally, it will show `/usr/bin/docker`.

**Comment by 24sama** [comment]
I think this issue can be closed. Feel free to reopen it.
