### ISSUE TITLE
Segmentation fault with kk v1.1.0 on arm64

### ISSUE THREAD

**Issue by wsdflink** [kubesphere/kubekey#524]
os: CentOS 7.6 64bit with ARM
version: kubekey-v1.1.0-linux-arm64.tar.gz
i got the "Segmentation fault" when run ./kk

**Comment by LinuxSuRen** [comment]
/retitle Segmentation fault with kk v1.1.0 on arm64

**Comment by EvanYen** [comment]
same error

**Comment by lin1005q** [comment]
1.1.1 same error
1.2.0-alpha.2 same error

**Comment by pixiake** [comment]
I also encountered the same error on centos7，But it is normal on ubuntu.
I think the release action needs to be optimized.

Before this, we can build kk according to the following documents.
https://github.com/kubesphere/kubekey/blob/master/docs/developer-guide.md#build-binary-from-source-code

**Comment by lin1005q** [comment]
> 我在centos7上也遇到同样的错误，但是在ubuntu上是正常的。
> 我认为发布动作需要优化。
> 
> 在此之前，我们可以根据以下文档构建kk。
> https://github.com/kubesphere/kubekey/blob/master/docs/developer-guide.md#build-binary-from-source-code

Thanks

**Comment by lin1005q** [comment]
It's OK! 😄

**Comment by 24sama** [comment]
The latest release version has been solved this issue.
duplicate #583
