### ISSUE TITLE
Failed to download image flannel from aliyun registry

### ISSUE THREAD

**Issue by jixiaoshi-gif** [kubesphere/kubekey#541]
ERRO[15:50:41 CST] Failed to download image: registry.cn-beijing.aliyuncs.com/kubesphereio/flannel:v0.12.0: Failed to exec command: sudo env PATH=$PATH docker pull registry.cn-beijing.aliyuncs.com/kubesphereio/flannel:v0.12.0
镜像仓库是不是没有这个镜像？

**Comment by LinuxSuRen** [comment]
Thanks for reaching out to us. We sync the images with the [repo image-sync-config](https://github.com/kubesphere/image-sync-config). Welcome to help add `flannel` into it.

By the way, we encourage people to communicate with each other in English. So, I'm going to help you to rewrite the issue title.

/retitle Failed to download image flannel from aliyun registry

**Comment by lshmouse** [comment]
+1 
https://github.com/kubesphere/image-sync-config/pull/7
Please help to review the PR, thanks~

**Comment by 24sama** [comment]
I think this issue is fixed.
