### ISSUE TITLE
default containerd version is to high can cause PLEG problem， why not changed it? 

### ISSUE THREAD

**Issue by oldthreefeng** [kubesphere/kubekey#551]
for kk. install kubesphere 3.0 .
![image](https://user-images.githubusercontent.com/38313565/120662417-b59fa880-c4bb-11eb-9af6-89a46426d0d0.png)

![image](https://user-images.githubusercontent.com/38313565/120661760-22667300-c4bb-11eb-9d77-445d7c3a8787.png)

i found docker engine is 19.03.8.  but containerd version is 1.4.4. which default install docker-ce 19.03.9 recommand container 1.2.3, but this changed in kubesphere. why this changed? 

ref: 
https://github.com/containerd/containerd/issues/5261
https://github.com/opencontainers/runc/issues/2865

**Comment by pixiake** [comment]
This is docker's default dependency, and ks has not modified it here.

In order to create clusters quickly, kk provides the ability to install docker, and uses official scripts (`curl -fsSL https://get.docker.com -o get-docker.sh`) to install docker.

**Comment by oldthreefeng** [comment]
ok, may be some cri (containerd) has already installed before kk install.

**Comment by oldthreefeng** [comment]
@pixiake  can you help me find the` install docker` code in kk ?

**Comment by pixiake** [comment]
https://github.com/kubesphere/kubekey/blob/21350767cc8ba03561ae306213b334e79afd7ee7/pkg/container-engine/docker/docker.go#L97

Only one script was used to install docker.
