### ISSUE TITLE
can kubekey support lb by itself?

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubekey#571]
Internally, you can customize and enable a nginx load balancing, support private cloud and public cloud, and quickly deploy high availability clusters

/feature-request

**Comment by 24sama** [comment]
This is exactly what I'm doing recently.

**Comment by 24sama** [comment]
[v1.2.0-alpha.1](https://github.com/kubesphere/kubekey/releases/tag/v1.2.0-alpha.1) is release. Now you can experience it!
