### ISSUE TITLE
kubekey all-in-one 安装为什么不直接用脚本

### ISSUE THREAD

**Issue by yanglinan01** [kubesphere/kubekey#575]

**Comment by FeynmanZhou** [comment]
Not clear about your question, could you add more description? 

BTW, please join the [Chinese Forum](https://kubesphere.com.cn/forum) for Chinese questions.

**Comment by yanglinan01** [comment]
kk安装单击k8s环境通过下面的命令
/kk create cluster --with-kubernetes v1.19.8
实际的安装过程我稍微跟踪了一下，检测环境-->下载文件-->下载镜像-->....->kubeadm init
感觉一个脚本就搞定了，为什么单独写个工具？
问题可能太傻 \﻿ (•◡•) /\﻿ (•◡•) /

**Comment by pixiake** [comment]
This tool is used to deploy clusters. All-in-one is only one of the cases.

Of course, All-in-one can be realized by a script, but it is necessary to maintain a script and a tool. Now that the tool already exists, there is no need to maintain a separate script.
