### ISSUE TITLE
improvement suggestion

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#58]
I found the deployment of ks-installer takes significant time. It would be better to pul flashing dots like ....... as the previous installer does so users know they should wait instead suspect it's dead.
 
INFO[10:12:33 CST] Deploying KubeSphere ...
[ks-allinone 192.168.100.2] MSG:
namespace/kubesphere-system created
configmap/ks-installer created
serviceaccount/ks-installer created
clusterrole.rbac.authorization.k8s.io/ks-installer created
clusterrolebinding.rbac.authorization.k8s.io/ks-installer created
deployment.apps/ks-installer created

**Comment by pixiake** [comment]
Yes， this is waiting for the installation of kubesphere，i will add pre-download images and prompt.

**Comment by rayzhou2017** [comment]
I saw it is fixed, but why removed the final msg about the login info?
<img width="480" alt="Screen Shot 2020-06-03 at 4 44 40 PM" src="https://user-images.githubusercontent.com/28859385/83615869-ae4c7300-a5b9-11ea-9490-0cd424d1bd8f.png">

**Comment by pixiake** [comment]
Login info was not removed. 
The reason it doesn't show is that after waiting for a timeout,  the backend installation is still running and may be  the images is being downloaded.
Pre-download images  will be added.
