### ISSUE TITLE
建议将所有资源转移到gitee码云平台，github真的太卡了

### ISSUE THREAD

**Issue by LyingDragons** [kubesphere/kubekey#585]

**Comment by FeynmanZhou** [comment]
Sorry, this is not reasonable to migrate all resources to Gitee. 

KubeSphere is a global project and community. All of the code, development, and documents will be hosted in GitHub at first, but we are going to make mirrors from GitHub to Gitee.

**Comment by LyingDragons** [comment]
好的，谢谢。

**Comment by 24sama** [comment]
You can exec `export KKZONE=cn` at first. Then kk will download the dependencies through aliyun repo.
