### ISSUE TITLE
failed create cluster with v1.2.0 alpha1

### ISSUE THREAD

**Issue by bjdaijun** [kubesphere/kubekey#586]
./kk create cluster -f config-sample.yaml report error:

ERRO[13:21:42 UTC] Failed to get kube-proxy config: Failed to exec command: sudo -E /bin/sh -c "set -o pipefail && /usr/local/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf get configmap kube-proxy -n kube-system -o yaml | sed -n '/server:.*/p' "
/bin/sh: 1: set: Illegal option -o pipefail: Process exited with status 2  node=192.168.1.102
WARN[13:21:42 UTC] Task failed ...
WARN[13:21:42 UTC] error: interrupted by error
Error: Failed to install internal load balancer: interrupted by error

**Comment by 24sama** [comment]
I think there maybe a bug in kk about the default shell. I do some research, some os deafult shell is not `bash`. So the `set -o pipefail` will get Illegal option error.

/kind bug
