### ISSUE TITLE
create cluster error 

### ISSUE THREAD

**Issue by bjdaijun** [kubesphere/kubekey#589]
commitid: 531ede4adc2c1b54079071d88f2e744bc88be000
with config: internalLoadbalancer: haproxy
serviceaccount/calico-kube-controllers created
ERRO[09:47:08 UTC] Failed to deploy local-volume.yaml: Failed to exec command: sudo -E /bin/sh -c "/usr/local/bin/kubectl apply -f /etc/kubernetes/addons/local-volume.yaml"
The connection to the server lb.kubesphere.local:6443 was refused - did you specify the right host or port?: Process exited with status 1  node=192.168.1.102
WARN[09:47:08 UTC] Task failed ...
WARN[09:47:08 UTC] error: interrupted by error
Error: Failed to deploy localVolume: interrupted by error

**Comment by 24sama** [comment]
Can you paste your config file in here?

**Comment by bjdaijun** [comment]
Can not re appear after reset machine to clean state.
