### ISSUE TITLE
flannel udp can not get config form cluseter.

### ISSUE THREAD

**Issue by shake** [kubesphere/kubekey#593]
I have deploy flannel udp use kk. but I try use got the config.

./kk create config --from-cluster

network:
    plugin: flannel
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18

lack of flannel backend: udp

**Comment by pixiake** [comment]
Featching configuration from cluster has not covered `flannel.backend` so far.
