### ISSUE TITLE
how can i use containerd 

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubekey#599]
install containerd  and run kk create cluster?

about: https://github.com/kubesphere/kubekey/pull/386

**Comment by LinuxSuRen** [comment]
This is a good question. But please notice that part of the KubeSphere components may not fully support contained yet. Such as DevOps. Please see also https://github.com/kubesphere-sigs/ks-devops/issues/67

**Comment by willzhang** [comment]
kubekey support k8s 1.20.x ，is it possible to install k8s 1.20.x with containerd ,how can i do that?   maybe kubekey not need to wait kubesphere support containerd。

**Comment by pixiake** [comment]
At present, it is necessary to prepare the machine that has deployed containerd, and then specify `containerManager: containerd` in the configuration file.

```
kubernetes:
  containerManager: containerd    # containerd or crio or isula
```
