### ISSUE TITLE
flannel vxlan+Directrouting not working

### ISSUE THREAD

**Issue by shake** [kubesphere/kubekey#602]
HI 

I try to test flannel vxlan + Directrouting, 

  network:
    plugin: flannel
    flannel:
        backendMode: vxlan
        Directrouting: true

after deploy, not working. only vxlan.

 net-conf.json: |
    {
      "Network": "10.233.64.0/18",
      "Backend": {
        "Type": "vxlan"
      }
    }
---

**Comment by rayzhou2017** [comment]
@zheng1 Please also check this issue.

**Comment by pixiake** [comment]
https://github.com/kubesphere/kubekey/blob/fb0ad3ab9c613e8be318bd521c1d0ef2f48e1028/apis/kubekey/v1alpha1/network_types.go#L34

For flannel, at present, it only supports specifying `Backend`, but does not support the configuration of `Directrouting`.

**Comment by shake** [comment]
ok, good idea. let my team try it.  this is Very good opportunity to enhance our ability.
