### ISSUE TITLE
[vet] Println arg list ends with redundant newline

### ISSUE THREAD

**Issue by tagGeeY** [kubesphere/kubekey#604]
```
$ go vet ./
pkg/cluster/upgrade/precheck.go:128:4: Println arg list ends with redundant newline
make: *** [vet] Error 2
```

**Comment by LinuxSuRen** [comment]
Good catch! Please feel free to help us to fix it if you are interested in it.

**Comment by tagGeeY** [comment]
> Good catch! Please feel free to help us to fix it if you are interested in it.

Okay. ☺

**Comment by LinuxSuRen** [comment]
You can use the following command if you want to take it.

`/assign`
