### ISSUE TITLE
Provide a default all-in-one config file

### ISSUE THREAD

**Issue by tingkai-zhang** [kubesphere/kubekey#64]
Hi, can you update the link for the example all-in-one config file in the READEME.
Currently, that link does not direct to a correct place:

https://github.com/kubesphere/kubekey/docs/config-example.md

**Comment by pixiake** [comment]
OK，I will update the link.

The allinone mode is without a profile.
If you want to install a cluster by a specified profile, you can use `./kk create config` to create a profile.

**Comment by pixiake** [comment]
you can try to execute `./kk create cluster --with-kubernetes v1.18.3`
