### ISSUE TITLE
How to install Kubernetes 1.22 with KubeKey?

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubekey#644]
Can we download the [v1.2.0-alpha.3](https://github.com/kubesphere/kubekey/releases/tag/v1.2.0-alpha.3) to install Kubernetes 1.22 directly?

**Comment by pixiake** [comment]
Yes, but you may need to install the container manager first.
The next alpha version will support automatic installation of containerd.

**Comment by FeynmanZhou** [comment]
Container manager?

**Comment by 24sama** [comment]
This alpha version kk will not install CRI. So, i think @pixiake means maybe you should install the docker or others first.

**Comment by 24sama** [comment]
This is out fault we caused, it's kind of unfriendly. So i modify it.

**Comment by FeynmanZhou** [comment]
Okay, docker will be installed automatically in a new alpha release of KubeKey?

**Comment by pixiake** [comment]
The `v1.2.0-alpha.3` has been rebuilt.
The next alpha version will support automatic installation of containerd.

**Comment by FeynmanZhou** [comment]
If I just use docker as the runtime, I can download `v1.2.0-alpha.3` to install docker and K8s together, right?

**Comment by pixiake** [comment]
> If I just use docker as the runtime, I can download `v1.2.0-alpha.3` to install docker and K8s together, right?

yes

**Comment by FeynmanZhou** [comment]
👍 As K8s 1.22 was available recently, it would be great to add a blog or tutorial to introduce this scenario.

**Comment by zhuch-h** [comment]
> 👍 As K8s 1.22 was available recently, it would be great to add a blog or tutorial to introduce this scenario.

Docker as Container ? try install by arm environment

**Comment by FeynmanZhou** [comment]
Docker. I think containerd will be integrated into KubeKey soon : )

**Comment by zhuch-h** [comment]
> Docker. I think containerd will be integrated into KubeKey soon : )

okay! The install will be on the weekend.

**Comment by meilihao** [comment]
failed to  deploy k8s v1.22.1 with kubekey v1.2.0-alpha.3:
```log
...
Warning: spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
daemonset.apps/cilium created
deployment.apps/cilium-operator created
ERRO[11:44:41 CST] Failed to deploy local-volume.yaml: Failed to exec command: sudo -E /bin/sh -c "/usr/local/bin/kubectl apply -f /etc/kubernetes/addons/local-volume.yaml" storageclass.storage.k8s.io/local unchanged
serviceaccount/openebs-maya-operator unchanged
deployment.apps/openebs-localpv-provisioner unchanged
unable to recognize "/etc/kubernetes/addons/local-volume.yaml": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
unable to recognize "/etc/kubernetes/addons/local-volume.yaml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1": Process exited with status 1  node=192.168.0.43
...
```

some log from deploying k8s v1.20.6 with kubekey v1.1.1:
```log
```log
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
clusterrole.rbac.authorization.k8s.io/openebs-maya-operator created
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
clusterrolebinding.rbac.authorization.k8s.io/openebs-maya-operator created
```
```

**Comment by meilihao** [comment]
I found merged pull req in [update api version #641](https://github.com/kubesphere/kubekey/pull/641/files) to solve it.

**Comment by 24sama** [comment]
1.2.0-alpha.4 is release 😄

**Comment by FeynmanZhou** [comment]
See https://github.com/kubesphere/website/pull/1977
