### ISSUE TITLE
Not found image registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.5

### ISSUE THREAD

**Issue by liangyuanpeng** [kubesphere/kubekey#650]
### What is version of KubeKey has the issue?

v1.2.0-alpha.3

### What is your os environment?

n

### A clear and concise description of what happend.

Not found image  registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.5

**Comment by FeynmanZhou** [comment]
IMO, the images will be synced to the Chinese registry after a general release. It might need verification from @kubesphere/sig-installation .

**Comment by liangyuanpeng** [comment]
You are right, I think the really problem is shouldn't tell the user kubekey  v1.2.0-alpha.3 support k8s 1.22 and just got the error when the uesr install k8s 1.22.0 from kubekey v1.2.0-alpha.3.  

At least provide an option to allow users to use this feature If it is not possible to public container image.

**Comment by FeynmanZhou** [comment]
Yes, this is an Alpha release for quick testing.
