### ISSUE TITLE
upgrade helm release firstly, then upgrade k8s version

### ISSUE THREAD

**Issue by yuswift** [kubesphere/kubekey#653]
### What is version of KubeKey has the issue?

latest

### What is your os environment?

Ubuntu 16.04

### KubeKey config file

```yaml
none
```

### A clear and concise description of what happend.

ref https://helm.sh/docs/topics/kubernetes_apis/

**Comment by 24sama** [comment]
@yuswift 1.2.0-alpha.4 is release, please help to check if fixed this issue.

**Comment by yuswift** [comment]
/kind need-to-verify
/cc @wenxin-01 
pls help to check if it works

**Comment by 24sama** [comment]
This issue has been verified.
