### ISSUE TITLE
Use 'v1.2.0-alpha.3' install kubesphere failed

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubekey#662]
### What is version of KubeKey has the issue?

version.BuildInfo{Version:"1.2.0-alpha.3", GitCommit:"0833f28", GitTreeState:"", GoVersion:"go1.14.15"}

### What is your os environment?

CentOS 8.2 64bit

### A clear and concise description of what happend.

![image](https://user-images.githubusercontent.com/68640256/132636786-ae4d8198-a6d8-4f07-9e98-beaa0c237363.png)
![image](https://user-images.githubusercontent.com/68640256/132636857-26d63073-475c-43c3-a02b-2ddeb2d3a960.png)

**Comment by 24sama** [comment]
Please use the latest 1.2.0-alpha.3(git commint: 4f1e403) release.
