### ISSUE TITLE
Weird download binaries

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#7]
I tried the lasted build kk and create cluster. The packages seem very weird.

![Screen Shot 2020-05-14 at 4 02 52 PM](https://user-images.githubusercontent.com/28859385/81908917-75456200-95fc-11ea-8a3d-8ccc1563e503.png)

**Comment by pixiake** [comment]
https://github.com/kubesphere/kubekey/pull/12

**Comment by rayzhou2017** [comment]
verified
