### ISSUE TITLE
kk强制下载docker镜像包

### ISSUE THREAD

**Issue by quqiangsheng** [kubesphere/kubekey#745]
### What is version of KubeKey has the issue?

1.2.0

### What is your os environment?

centos7.9

### A clear and concise description of what happend.

第一步kk创建config配置文件
第二步修改后使用kk 创建集群 
./kk create cluster -f config-sample.yaml --container-manager docker --with-local-storage
第三部强制下载docker二进制文件 由于网络不好 docker一直卡着下不下来
安装机已经装了docker19.03.12
在另一台主机上是已经安装了20.10.5
都会卡到这里 导致无法进行

**Comment by 24sama** [comment]
You can use this command at first:
`export KKZONE=cn`

**Comment by chaunceyjiang** [comment]
![image](https://user-images.githubusercontent.com/17962021/146157534-b1753ac5-dd42-4b06-ae16-728c100283d6.png)

It seems that aliyun mirror network is too bad.

![image](https://user-images.githubusercontent.com/17962021/146158728-496096a0-6fa3-46fe-9713-e505ab895f77.png)

https://github.com/kubesphere/kubekey/blob/master/pkg/binaries/kubernetes.go#L65
maybe switch to tencent mirror network.
