### ISSUE TITLE
Oracle Cloud Infrastructure Installation on arm64 Instance - Namespace : kubesphere-system Name: ks-installer-6db4b9dd85-f6xbr status pending

### ISSUE THREAD

**Issue by SFARPak** [kubesphere/kubekey#746]
### What is version of KubeKey has the issue?

v1.21.5

### What is your os environment?

Ubuntu 18.04 LTS

### KubeKey config file

```yaml
Using default command to install:
./kk create cluster
```

### A clear and concise description of what happend.

Hello,

I have been successful installing on amd64 Instance on Oracle Cloud Infrastructure, however when installing on arm64 below issues happen:

Installer keeps loading...
![image](https://user-images.githubusercontent.com/89567338/140605146-c7de4294-ef3a-41c9-a446-da8a69ab0848.png)

There is no log
![image](https://user-images.githubusercontent.com/89567338/140605324-4d8e9a2e-e0e8-49ec-b07a-f27e9dc4f4a4.png)

root@master:/home/ubuntu/kubekey-build/kubekey/output# kubectl get all
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.233.0.1   <none>        443/TCP   14h

![image](https://user-images.githubusercontent.com/89567338/140605197-721fdbe4-9154-409b-bf1d-b9be61b66b2d.png)

This install is using build with reference to below guide:

https://github.com/kubesphere/kubekey/blob/master/docs/developer-guide.md#build-binary-from-source-code

I have also tried to install using standard installation for single node and multimode using arm64 parameter in the config file.

### Relevant log output

```shell
There is no output of this command:

kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f
```

**Comment by 24sama** [comment]
It looks like the `openebs` is not working. You can use `kubectl describe` like the following command to get more informations:
```
Kubectl describe po openebs-localpv-provisioner-Sbfb67894-9txkv -n kube-system

Kubectl describe ks-installer-6db4b9dd85-f6xbr -n kubesphere-system

```

**Comment by SFARPak** [comment]
Name:         openebs-localpv-provisioner-5bfb67894-9txkv
Namespace:    kube-system
Priority:     0
Node:         master/10.0.0.57
Start Time:   Sat, 06 Nov 2021 10:20:08 +0000
Labels:       name=openebs-localpv-provisioner
              openebs.io/component-name=openebs-localpv-provisioner
              openebs.io/version=2.10.1
              pod-template-hash=5bfb67894
Annotations:  cni.projectcalico.org/containerID: 3f78c7ec1c4d80eb9d1536571e445729c185ea0656c4b743a659caac4b985db4
              cni.projectcalico.org/podIP: 10.233.70.23/32
              cni.projectcalico.org/podIPs: 10.233.70.23/32
Status:       Running
IP:           10.233.70.23
IPs:
  IP:           10.233.70.23
Controlled By:  ReplicaSet/openebs-localpv-provisioner-5bfb67894
Containers:
  openebs-provisioner-hostpath:
    Container ID:   docker://8500f6c4b2cd4d70fdb0d57799e33672af08d6a644c03b6915cc743465664a4c
    Image:          openebs/provisioner-localpv:2.10.1
    Image ID:       docker-pullable://openebs/provisioner-localpv@sha256:f5dc9d1d3cedad80c63b6d6e4d7fdcca1850b46ca1fd34c9d45de18917e74138
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Sat, 06 Nov 2021 10:20:43 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       exec [sh -c test $(pgrep -c "^provisioner-loc.*") = 1] delay=30s timeout=1s period=60s #success=1 #failure=3
    Environment:
      NODE_NAME:                     (v1:spec.nodeName)
      OPENEBS_NAMESPACE:            kube-system (v1:metadata.namespace)
      OPENEBS_SERVICE_ACCOUNT:       (v1:spec.serviceAccountName)
      OPENEBS_IO_ENABLE_ANALYTICS:  true
      OPENEBS_IO_INSTALLER_TYPE:    openebs-operator-lite
      OPENEBS_IO_HELPER_IMAGE:      openebs/linux-utils:2.10.0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bn5qg (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-api-access-bn5qg:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  8m15s (x78 over 88m)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
  Normal   Pulling           5m23s                 kubelet            Pulling image "openebs/provisioner-localpv:2.10.1"
  Normal   Pulled            4m50s                 kubelet            Successfully pulled image "openebs/provisioner-localpv:2.10.1" in 33.157399112s
  Normal   Created           4m50s                 kubelet            Created container openebs-provisioner-hostpath
  Normal   Started           4m50s                 kubelet            Started container openebs-provisioner-hostpath

**Comment by SFARPak** [comment]
This is the output I tried to remove the tain but now status is :
![image](https://user-images.githubusercontent.com/89567338/140606399-a1f6474f-31c6-4b48-a326-8c97cbf78e00.png)

**Comment by pixiake** [comment]
You can check the logs and events of `CrashLoopBackOff` pods again.

Does the nodes have firewall or security group?

**Comment by SFARPak** [comment]
I had to re-create the instance and re-run the setup again with single node.

Now Only issue is with ks-installer:

![image](https://user-images.githubusercontent.com/89567338/140616837-ac60fee0-b6b0-4b77-938b-06b2618aca59.png)


Please see below the output of `kubectl describe po ks-installer-d98f7d88-c5z2m -n kubesphere-system`

Name:         ks-installer-d98f7d88-c5z2m
Namespace:    kubesphere-system
Priority:     0
Node:         master/10.0.0.214
Start Time:   Sat, 06 Nov 2021 13:35:03 +0000
Labels:       app=ks-install
              pod-template-hash=d98f7d88
              version=v3.2.0
Annotations:  cni.projectcalico.org/containerID: 1fcf80a07fc76272ad3f75df384db9386034b0923ac47f4787384b3d7a458ff7
              cni.projectcalico.org/podIP: 10.233.70.10/32
              cni.projectcalico.org/podIPs: 10.233.70.10/32
Status:       Running
IP:           10.233.70.10
IPs:
  IP:           10.233.70.10
Controlled By:  ReplicaSet/ks-installer-d98f7d88
Containers:
  installer:
    Container ID:   docker://870b119a1614b6ca29ffe4da607c13d0d4c7cfb6de2022a0bdcab2348f6373e5
    Image:          kubesphere/ks-installer:v3.2.0
    Image ID:       docker-pullable://kubesphere/ks-installer@sha256:eaece46e558156834eedad726b35963375d5a2555f4b539a74                                                                       61fd1367cee930
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 06 Nov 2021 16:28:29 +0000
      Finished:     Sat, 06 Nov 2021 16:28:29 +0000
    Ready:          False
    Restart Count:  41
    Environment:    <none>
    Mounts:
      /etc/localtime from host-time (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-nqq9t (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  host-time:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/localtime
    HostPathType:
  kube-api-access-nqq9t:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason          Age                     From     Message
  ----     ------          ----                    ----     -------
  Normal   Pulling         19m (x36 over 174m)     kubelet  Pulling image "kubesphere/ks-installer:v3.2.0"
  Warning  BackOff         9m30s (x768 over 174m)  kubelet  Back-off restarting failed container
  Normal   SandboxChanged  2m44s (x3 over 3m3s)    kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          2m42s                   kubelet  Successfully pulled image "kubesphere/ks-installer:v3.2.0"                                                                        in 1.160936928s
  Normal   Pulled          2m25s                   kubelet  Successfully pulled image "kubesphere/ks-installer:v3.2.0"                                                                        in 1.141591296s
  Normal   Pulled          116s                    kubelet  Successfully pulled image "kubesphere/ks-installer:v3.2.0"                                                                        in 1.111185317s
  Normal   Created         116s (x3 over 2m42s)    kubelet  Created container installer
  Normal   Started         116s (x3 over 2m42s)    kubelet  Started container installer
  Warning  BackOff         87s (x8 over 2m41s)     kubelet  Back-off restarting failed container
  Normal   Pulling         72s (x4 over 2m43s)     kubelet  Pulling image "kubesphere/ks-installer:v3.2.0"
  Normal   Pulled          71s                     kubelet  Successfully pulled image "kubesphere/ks-installer:v3.2.0"                                                                        in 1.118541144s

**Comment by SFARPak** [comment]
All the firewall ports mentioned here are forwarded:

https://kubesphere.io/docs/installing-on-linux/introduction/port-firewall/

**Comment by SFARPak** [comment]
![image](https://user-images.githubusercontent.com/89567338/140618619-fa922cf1-2fd3-48c4-8fb3-bf45a9716d06.png)

This is the error shown in Kubernetes dashboard.

**Comment by pixiake** [comment]
```
exec format error
```
This error is caused by arch mismatch. 

KubeSphere has not published the arm image at present. 

ks-installer can be built by yourself according to the following Dockerfile. But there may be other arm images that you need to build by yourself. 
https://github.com/kubesphere/ks-installer/blob/master/Dockerfile.complete

**Comment by SFARPak** [comment]
Hello,


Thanks for your response.

What I got from this link is that you can specify the architecture like its mentioned here:

https://kubesphere.io/docs/installing-on-linux/introduction/multioverview/

![image](https://user-images.githubusercontent.com/89567338/140794463-d05629ba-6df2-42d0-bdc3-806d3b562a15.png)

**Comment by 24sama** [comment]
@SFARPak Hello!
There are 2 tools in the KubeSphere community:
* KubeKey: it is used for install a kubernetes cluster
* ks-installer: it is used for deploy a KubeSphere

KubeKey will install a kubernetes cluster first and then use the ks-installer to deploy KubeSphere. So the field you circled in that pic means install an arm64 architecture kubernetes cluster, but is not for KubeSphere. As @pixiake said, KubeSphere has not published the arm image at present.

**Comment by SFARPak** [comment]
Hello 24sama,

Thank you for responding.

This clarifies the ambiguities.

**Comment by 24sama** [comment]
@SFARPak 
I think this issue can be closed?

**Comment by SFARPak** [comment]
Yes can be closed.

thanks

**Comment by FeynmanZhou** [comment]
> Yes can be closed.
> 
> thanks

Hi @SFARPak ,

We are going to make the ARM images of the KubeSphere Core available soon, it might be ready to download and install in one or two weeks.

**Comment by SFARPak** [comment]
Great!

good to see this, thanks for update.

appreciate that.

**Comment by gaugys** [comment]
Hello, is there any option to tell kubekey to use ks-isntall image from another repo/ private ?

**Comment by 24sama** [comment]
> Hello, is there any option to tell kubekey to use ks-isntall image from another repo/ private ?

Probably you want to offline install kubesphere? Here is a [doc](https://v2-0.docs.kubesphere.io/docs/installation/install-ks-offline/).

**Comment by 24sama** [comment]
> Yes can be closed.
> 
> thanks

This issue can be closed.
