### ISSUE TITLE
Kubekey was unable to detect installed dependencies on Debian 10

### ISSUE THREAD

**Issue by SignorMercurio** [kubesphere/kubekey#759]
### What is version of KubeKey has the issue?

1.2.0

### What is your os environment?

Debian 10

### KubeKey config file

```yaml
No config file specified.
```

### A clear and concise description of what happend.

I've **already installed** the required dependencies like `curl`, `socat`, `conntrack`, etc. I downloaded kubekey via:

```shell
$ curl -sfL https://get-kk.kubesphere.io | VERSION=v1.2.0 sh -
$ chmod +x ./kk
```

Then I tried to create a cluster:

```shell
./kk create cluster --with-kubernetes v1.21.5 --with-kubesphere v3.2.0
```

which still produced:
```
+----------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
| name     | sudo | curl | openssl | ebtables | socat | ipset | conntrack | docker | nfs client | ceph client | glusterfs client | time         |
+----------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
| instance |      |      |         |          |       |       |           |        |            |             |                  | CST 04:06:16 |
+----------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
instance: conntrack is required.
```

I ran all the commands above with root permission.

### Relevant log output

```shell
$ which conntrack
/usr/sbin/conntrack

$ which socat
/usr/bin/socat

$ conntrack
# produced normal help message for conntrack, so it's in $PATH

$ socat
# produced normal error message for socat, so it's in $PATH
```

**Comment by 24sama** [comment]
Maybe this is a bug in the Debian 10. Kubekey will use following command to check the dependencies in your enviroment:
```
sudo -E /bin/sh -c "which conntrack"
sudo -E /bin/bash -c "which conntrack"
```
And could you please use the command manuly and paste the result in the comment? It can help us to solve this bug.

**Comment by SignorMercurio** [comment]
> Maybe this is a bug in the Debian 10. Kubekey will use following command to check the dependencies in your enviroment:
> 
> ```
> sudo -E /bin/sh -c "which conntrack"
> sudo -E /bin/bash -c "which conntrack"
> ```
> 
> And could you please use the command manuly and paste the result in the comment? It can help us to solve this bug.

After running these commands, I found that the main problem is that Debian does not have `sudo` pre-installed, and I only focused on other dependencies, forgetting about `sudo`(sorry, my bad).

Therefore, I ran `apt install sudo` and the issue was solved. Here's the command output in case someone needs it:

```shell
$ sudo -E /bin/sh -c "which conntrack"
/usr/sbin/conntrack
$ sudo -E /bin/bash -c "which conntrack"
/usr/sbin/conntrack
```

Please feel free to close this issue. Thanks for helping out.

**Comment by 24sama** [comment]
@SignorMercurio Thanks for sharing!
I will close this issue.
