### ISSUE TITLE
Support external etcd service

### ISSUE THREAD

**Issue by cumirror** [kubesphere/kubekey#762]
### Describe this feature

Currently kk automatically create a built-in etcd cluster on master nodes when creating a k8s cluster. 
In some scenarios, users may have their own etcd cluster and want to use it in k8s. Can kk support such scenarios?

### Describe the solution you'd like

kk should support etcd endpoints configuration.
If there is such a configuration, kk skips the creation of etcd cluster and sets the endpoints to k8s apiserver.

**Comment by pixiake** [comment]
https://github.com/kubesphere/kubekey/issues/1122
