### ISSUE TITLE
It’s would be better to show the download progress.

### ISSUE THREAD

**Issue by xyz-li** [kubesphere/kubekey#795]
### Describe this feature

When downloading the kubectl/kubeadm/helm binary, there is no download progress, It would be better to show the download progress.

### Describe the solution you'd like

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:22 --:--:--     0

**Comment by 24sama** [comment]
Thanks for your suggestion. I think this feature can be a good-first-issue.

/good-first-issue

**Comment by chaunceyjiang** [comment]
I will handle this issue

**Comment by 24sama** [comment]
Thanks for @chaunceyjiang's contribution. This issue can be closed.
