### ISSUE TITLE
failed on ubuntu 18.04

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#8]
**The error is:**

ERRO[16:06:41 CST] Failed to install docker: Failed to exec command: sudo -E /bin/sh -c "if [ -z $(which docker) ]; then curl https://kubernetes.pek3b.qingstor.com/tools/kubekey/docker-install.sh | sh && systemctl enable docker && echo ewogICJsb2ctb3B0cyI6IHsKICAgICJtYXgtc2l6ZSI6ICI1bSIsCiAgICAibWF4LWZpbGUiOiIzIgogIH0sCiAgImV4ZWMtb3B0cyI6IFsibmF0aXZlLmNncm91cGRyaXZlcj1zeXN0ZW1kIl0KfQo= | base64 -d > /etc/docker/daemon.json && systemctl reload docker; fi": Process exited with status 100  node=192.168.100.2
WARN[16:06:41 CST] Task failed ...
WARN[16:06:41 CST] error: interrupted by error
Error: Failed to install docker: interrupted by error

**After taking the following**

E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
root@ks-allinone:/home/ubuntu# dpkg --configure -a

**It seems working.**

**Comment by pixiake** [comment]
Newly created ubuntu18.04 on the public cloud, its APT is occupied and it takes about ten minutes for it to work.
The following commands can be executed to check if the APT is occupied.
`ps -ef | grep apt`

**Comment by rayzhou2017** [comment]
verified
