### ISSUE TITLE
offline-installation-tool.sh cannot assign k8s version

### ISSUE THREAD

**Issue by shake** [kubesphere/kubekey#809]
### What is version of KubeKey has the issue?

1.2

### What is your os environment?

centos 7

### A clear and concise description of what happend.

./offline-installation-tool.sh -b 
working

./offline-installation-tool.sh -b -v v1.21.5 

not working, and show me the hlep

# ./offline-installation-tool.sh -b -v v1.22.1
Usage:

  ./offline-installation-tool.sh [-l IMAGES-LIST] [-d IMAGES-DIR] [-r PRIVATE-REGISTRY] [-v KUBERNETES-VERSION ]

Description:
  -b                     : save kubernetes' binaries.
  -d IMAGES-DIR          : the dir of files (tar.gz) which generated by `docker save`. default: /root/kube/kubesphere-images
  -l IMAGES-LIST         : text file with list of images.
  -r PRIVATE-REGISTRY    : target private registry:port.
  -s                     : save model will be applied. Pull the images in the IMAGES-LIST and save images as a tar.gz file.
  -v KUBERNETES-VERSION  : download kubernetes' binaries. default: v1.17.9
  -h                     : usage message

./offline-installation-tool.sh [-l IMAGES-LIST] [-d IMAGES-DIR] [-r PRIVATE-REGISTRY] [-v KUBERNETES-VERSION ]

Description:
  -b                     : save kubernetes' binaries.
  -d IMAGES-DIR          : the dir of files (tar.gz) which generated by `docker save`. default: /root/kube/kubesphere-images
  -l IMAGES-LIST         : text file with list of images.
  -r PRIVATE-REGISTRY    : target private registry:port.
  -s                     : save model will be applied. Pull the images in the IMAGES-LIST and save images as a tar.gz file.
  -v KUBERNETES-VERSION  : download kubernetes' binaries. default: v1.17.9
  -h                     : usage message

now the download kubernetes' binaries. default:1.21.5 not 1.17.9

**Comment by 24sama** [comment]
This is a bug, caused by the script support dowenload other decpendency binaries. We will add some examples in the script. And you can use command `export KUBERNETES_VERSION=v1.22.1; export HELM_VERSION=v3.6.3;` at first, and then use `./offline-installation-tool.sh -b`.

**Comment by 24sama** [comment]
https://github.com/kubesphere/ks-installer/pull/1835 This PR is already fix the issue.
