### ISSUE TITLE
Generate etcd certificate using code substitution script

### ISSUE THREAD

**Issue by pixiake** [kubesphere/kubekey#810]
### Your current KubeKey version

v2.0.0-alpha.1

### Describe this feature

At present, there are the following problems in using scripts to generate certificates.
1. Node needs to rely on openssl.
2. When other component certificates are generated, it is inconvenient to reuse them.

### Describe the solution you'd like

1. Generate etcd certificate using code substitution script.
2. The certificate validity period is set to 10 years by default.
3. Certificate file permissions are not higher than 600.

**Comment by 24sama** [comment]
This feature is very necessary. It can make KubeKey easy to be able to do more complecated certificate manage work.
