### ISSUE TITLE
Request to disable the default installation of docker while ContainerD container runtime set

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/kubekey#812]
### What is version of KubeKey has the issue?

latest

### What is your os environment?

CentOS 7

### A clear and concise description of what happend.

If I choose to use ContainerD container runtime to run Kubernetes, it's unnecessary to add a Docker container runtime for each node by default.

So I suggest providing an optional setting against this feature and disabling it by default.

**Comment by pixiake** [comment]
Docker is also installed when k8s uses containerd, considering that many people may be used to using docker.
I think if this is easy to cause ambiguity, docker can be disabled by default.

**Comment by LinuxSuRen** [comment]
It would be better if we provide a flag for that. For instance: `--enable-docker=true|false`

**Comment by geneliu** [comment]
I would suggest that it's awesome to support a setting like: `container-engine: docker(default) | containerd |cri-o`

**Comment by JohnNiang** [comment]
> I would suggest that it's awesome to support a setting like: `container-engine: docker(default) | containerd | cri-o`

Please see:
https://github.com/kubesphere/kubekey/blob/0cf186613f8cf8d393669a071632ea0d2243d089/apis/kubekey/v1alpha2/kubernetes_types.go#L36

**Comment by 24sama** [comment]
Fix: #1179
