### ISSUE TITLE
binary downlod lack of docker crictl

### ISSUE THREAD

**Issue by shake** [kubesphere/kubekey#818]
### What is version of KubeKey has the issue?

1.20

### What is your os environment?

centos 7.9

### A clear and concise description of what happend.

https://kubesphere.io/zh/docs/installing-on-linux/introduction/air-gapped-installation/

binary still need  download docker and crictl.

**Comment by 24sama** [comment]
I found `crictl-v1.22.0-linux-amd64.tar.gz` and `docker-20.10.8.tgz`missing in the `./kubekey/v1.21.5/amd64` dir, after i exec the `offline-installation-tool.sh` script.

For now, you can download the missing binaries(only support `crictl-v1.22.0-linux-amd64.tar.gz` and `docker-20.10.8.tgz`) and move them to `./kubekey/v1.21.5/amd64`(your real path) manually. Or, modify the `offline-installation-tool.sh` to support to download the missing binaries.

**Comment by 24sama** [comment]
I think this can be a good first issue. Would like to help us to solve this issue?

https://github.com/kubesphere/ks-installer/blob/528c292b30efb2b3bf4a05d6349a150c559e99bc/scripts/offline-installation-tool.sh#L110

/kind good-first-issue

**Comment by 24sama** [comment]
I think this can be a good first issue. Would like to help us to solve this issue?

https://github.com/kubesphere/ks-installer/blob/528c292b30efb2b3bf4a05d6349a150c559e99bc/scripts/offline-installation-tool.sh#L110

/good-first-issue

**Comment by 24sama** [comment]
Fixed by this PR https://github.com/kubesphere/ks-installer/pull/1843
