### ISSUE TITLE
offline install still need download registry.cn-beijing.aliyuncs.com/kubesphereio/ks-installer

### ISSUE THREAD

**Issue by shake** [kubesphere/kubekey#824]
### What is version of KubeKey has the issue?

1.20

### What is your os environment?

centos 7

### A clear and concise description of what happend.

I have setting private registry, and aslo down all image accroding to the image-list.

but I have setting config file use private registry.

after finish installed. I found still need to download  
registry.cn-beijing.aliyuncs.com/kubesphereio/ks-installer 
even I tag the image and push to my private hub, install again, but still need download again.

### Relevant log output

```shell
hope the image download from private hub.
```

**Comment by 24sama** [comment]
If your enviroment set the `KKZONE=cn`, please use the command `unset KKZONE`. And this bug has been fixed by this PR https://github.com/kubesphere/kubekey/pull/800

**Comment by shake** [comment]
you are right.
