### ISSUE TITLE
kk upgrade Recognition wrong of kubesphere version

### ISSUE THREAD

**Issue by shake** [kubesphere/kubekey#825]
### What is version of KubeKey has the issue?

1.20

### What is your os environment?

centos 7.9

### A clear and concise description of what happend.

./kk upgrade --with-kubernetes v1.22.1 -f config/flannel.yaml 
+-------+------+------+---------+----------+-------+-------+-----------+---------+------------+-------------+------------------+--------------+
| name  | sudo | curl | openssl | ebtables | socat | ipset | conntrack | docker  | nfs client | ceph client | glusterfs client | time         |
+-------+------+------+---------+----------+-------+-------+-----------+---------+------------+-------------+------------------+--------------+
| node2 | y    | y    | y       | y        | y     | y     | y         | 20.10.8 | y          |             |                  | CST 17:20:31 |
| node1 | y    | y    | y       | y        | y     | y     | y         | 20.10.8 | y          |             |                  | CST 17:20:31 |
+-------+------+------+---------+----------+-------+-------+-----------+---------+------------+-------------+------------------+--------------+

Cluster nodes status:
NAME    STATUS   ROLES                         AGE   VERSION
node1   Ready    control-plane,master,worker   12m   v1.20.10
node2   Ready    worker                        12m   v1.20.10

Upgrade Confirmation:
kubernetes version: v1.20.10 to v1.22.1
kubesphere version: v3.1.0 to v3.2.0

but my kubesphere is v3.2.0, not v3.1.0

**Comment by 24sama** [comment]
The kk will use the following command to check the ks version 
```
kubectl get deploy -n  kubesphere-system ks-console -o jsonpath='{.metadata.labels.version}'
```
Could you please exec the command manually and check the result?

**Comment by shake** [comment]
kubectl get deploy -n  kubesphere-system ks-console -o jsonpath='{.metadata.labels.version}'
v3.1.0

kubectl get pods -A -o=custom-columns='IMAGE:spec.contain.image' | tr ',' '\n' | sort -u

hub.bj.abc.tech:5000/coredns/coredns:1.8.0
hub.bj.abc.tech:5000/csiplugin/snapshot-controller:v4.0.0
hub.bj.abc.tech:5000/kubesphere/flannel:v0.12.0
hub.bj.abc.tech:5000/kubesphere/k8s-dns-node-cache:1.15.12
hub.bj.abc.tech:5000/kubesphere/ks-apiserver:v3.2.0
hub.bj.abc.tech:5000/kubesphere/ks-console:v3.2.0
hub.bj.abc.tech:5000/kubesphere/ks-controller-manager:v3.2.0
hub.bj.abc.tech:5000/kubesphere/ks-installer:v3.2.0
hub.bj.abc.tech:5000/kubesphere/kube-apiserver:v1.21.5
hub.bj.abc.tech:5000/kubesphere/kube-controller-manager:v1.21.5
hub.bj.abc.tech:5000/kubesphere/kubectl:v1.21.0
hub.bj.abc.tech:5000/kubesphere/kube-proxy:v1.21.5
hub.bj.abc.tech:5000/kubesphere/kube-rbac-proxy:v0.8.0
hub.bj.abc.tech:5000/kubesphere/kube-scheduler:v1.21.5
hub.bj.abc.tech:5000/kubesphere/kube-state-metrics:v1.9.7
hub.bj.abc.tech:5000/kubesphere/notification-manager-operator:v1.4.0
hub.bj.abc.tech:5000/kubesphere/notification-manager:v1.4.0
hub.bj.abc.tech:5000/kubesphere/notification-tenant-sidecar:v3.2.0
hub.bj.abc.tech:5000/kubesphere/prometheus-config-reloader:v0.43.2
hub.bj.abc.tech:5000/kubesphere/prometheus-operator:v0.43.2
hub.bj.abc.tech:5000/mirrorgooglecontainers/defaultbackend-amd64:1.4
hub.bj.abc.tech:5000/openebs/provisioner-localpv:2.10.1
hub.bj.abc.tech:5000/prom/alertmanager:v0.21.0
hub.bj.abc.tech:5000/prom/node-exporter:v0.18.1
hub.bj.abc.tech:5000/prom/prometheus:v2.26.0

**Comment by shake** [comment]
# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by 24sama** [comment]
I found ks-console didn't support `.metadata.labels.version` this field anymore. KK will modify the check kubesphere version command later.
For now, you could be used kk to upgrade k8s cluster only.

**Comment by shake** [comment]
I try to upgrade
./kk upgrade --with-kubernetes v1.20.10

seem no problem, but use outside docker registry.

so  I use config file

./kk upgrade --with-kubernetes v1.20.10 -f config/flannel.yaml 
+-------+------+------+---------+----------+-------+-------+-----------+---------+------------+-------------+------------------+--------------+
| name  | sudo | curl | openssl | ebtables | socat | ipset | conntrack | docker  | nfs client | ceph client | glusterfs client | time         |
+-------+------+------+---------+----------+-------+-------+-----------+---------+------------+-------------+------------------+--------------+
| node2 | y    | y    | y       | y        | y     | y     | y         | 20.10.8 | y          |             |                  | CST 12:40:12 |
| node1 | y    | y    | y       | y        | y     | y     | y         | 20.10.8 | y          |             |                  | CST 12:40:12 |
+-------+------+------+---------+----------+-------+-------+-----------+---------+------------+-------------+------------------+--------------+

Cluster nodes status:
NAME    STATUS   ROLES                         AGE     VERSION
node1   Ready    control-plane,master,worker   9m43s   v1.20.4
node2   Ready    worker                        9m13s   v1.20.4

Upgrade Confirmation:
kubernetes version: v1.20.4 to v1.20.10
kubesphere version: v3.1.0 to v3.2.0

Continue upgrading cluster? [yes/no]: 

working , but show the wrong version kbuesphere 

# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:06:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:00:37Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by shake** [comment]
I try to upgrade k8s, working as expect.

1.20.4 upgrade 1.20.10
1.20.10 updade 1.22.1,  would first uprade to 1.21.5, then upgrade to 1.22.1, working.

**Comment by 24sama** [comment]
> I try to upgrade ./kk upgrade --with-kubernetes v1.20.10
> 
> seem no problem, but use outside docker registry.
> 
> so I use config file
> 
> ./kk upgrade --with-kubernetes v1.20.10 -f config/flannel.yaml +-------+------+------+---------+----------+-------+-------+-----------+---------+------------+-------------+------------------+--------------+ | name | sudo | curl | openssl | ebtables | socat | ipset | conntrack | docker | nfs client | ceph client | glusterfs client | time | +-------+------+------+---------+----------+-------+-------+-----------+---------+------------+-------------+------------------+--------------+ | node2 | y | y | y | y | y | y | y | 20.10.8 | y | | | CST 12:40:12 | | node1 | y | y | y | y | y | y | y | 20.10.8 | y | | | CST 12:40:12 | +-------+------+------+---------+----------+-------+-------+-----------+---------+------------+-------------+------------------+--------------+
> 
> Cluster nodes status: NAME STATUS ROLES AGE VERSION node1 Ready control-plane,master,worker 9m43s v1.20.4 node2 Ready worker 9m13s v1.20.4
> 
> Upgrade Confirmation: kubernetes version: v1.20.4 to v1.20.10 kubesphere version: v3.1.0 to v3.2.0
> 
> Continue upgrading cluster? [yes/no]:
> 
> working , but show the wrong version kbuesphere
> 
> # kubectl version
> Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:06:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:00:37Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

Yes, the flag `-f config.yaml` is also needed.
