### ISSUE TITLE
allinone installed failed because of sc missing

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#83]
`./kk create cluster --with-kubernetes v1.18.3`  install failed. The error msg shows as below. But I think allinone should have localVolume as default.

TASK [preinstall : Stop if defaultStorageClass was not found] ******************
fatal: [localhost]: FAILED! => {
    "assertion": "\"(default)\" in default_storage_class_check.stdout",
    "changed": false,
    "evaluated_to": false,
    "msg": "Default StorageClass was not found !"
}

**Comment by pixiake** [comment]
`./kk create cluster --with-kubernetes v1.18.3`  
This command only used to deploy a kubernetes without storage plugin.
