### ISSUE TITLE
kubelet etcd apiserver 的安装部署 为什么不基于docker 方式么？

### ISSUE THREAD

**Issue by tanguofu** [kubesphere/kubekey#839]
### Describe this feature

kubelet etcd apiserver 的安装部署 可以类似于rke 基于docker 的方式么？ 方便私有化的部署安装和更新，也方便二进制分发

### Describe the solution you'd like

kubelet etcd apiserver 的安装部署 可以类似于rke 基于docker 的方式么？ 方便私有化的部署安装和更新，也方便二进制分发

**Comment by 24sama** [comment]
Hi @tanguofu 
It's a good question. if kk install an etcd cluster by using a container is very simple and fast. But the k8s deprecated Docker as a container runtime after v1.20, and finally removed it in v1.22. As an install tool, we need to follow the k8s community. Besides, installing by using binaries can also make kk not dependent on one certainly container runtime.

Perhaps, we can also support this install option. The old version kk install an etcd cluster by using the container, but kk v2.0.0 doesn't migrate the old code. I think it can be a `good-first-issue`.

/kind good-first-issue
/kind feature-request
