### ISSUE TITLE
install msg refine

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#84]
`./kk create cluster` is to create a Kubernetes cluster only, but it shows "kubesphere" has been added to your repositories. This will confuse user.
![Screen Shot 2020-06-19 at 3 16 45 PM](https://user-images.githubusercontent.com/28859385/85107066-e43b5980-b23f-11ea-87d4-edc0460ae3d4.png)

**Comment by pixiake** [comment]
ok，we‘ll refine it.
