### ISSUE TITLE
如何将socat 和 conntrack-tools的安装整合到 kubekey 安装过程中

### ISSUE THREAD

**Issue by tanguofu** [kubesphere/kubekey#854]
### Your current KubeKey version

1.2.0

### Describe this feature

我们使用kubesphere搭建私有云场景的下容器平台，在集成测试的时候需要自动化的完成 集群部署安装， 但是现在socat 和 conntrack -tools 需要单独安装， 这里可以整合到 kubekey 里面？

### Describe the solution you'd like

比如我们可以配置一个私有的 yum repo, kubekey 可以增加下自定义的机器初始化命令 我们可以配置yum install -y ？

**Comment by pixiake** [comment]
The kk v2.0.0 will add the installation of these basic dependent software to the process.

**Comment by tanguofu** [comment]
> The kk v2.0.0 will add the installation of these basic dependent software to the process.

awesome!
