### ISSUE TITLE
Support Kubernetes 1.23

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubekey#864]
### Your current KubeKey version

1.2.0

### Describe this feature

As [Kubernetes 1.23 was released](https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/) this week, I hope KubeKey could support the installation of Kubernetes 1.23. It would be better to support ARM 64bit and x86 64bit.

### Describe the solution you'd like

None

### Additional information

None

**Comment by 24sama** [comment]
Yes, KubeKey can quickly support this. And I think this can be a `good-first-issue`.

/good-first-issue

**Comment by chaunceyjiang** [comment]
Hi,i want to fix this issue
but i don't know how to push the `kube-apiserver:v1.23.0` container image  to kubesphere repo


https://github.com/kubesphere/kubekey/blob/master/pkg/images/tasks.go#L91-L94

https://github.com/kubesphere/kubekey/blob/master/pkg/images/images.go#L89

**Comment by pixiake** [comment]
> Hi,i want to fix this issue but i don't know how to push the `kube-apiserver:v1.23.0` container image to kubesphere repo
> 
> https://github.com/kubesphere/kubekey/blob/master/pkg/images/tasks.go#L91-L94
> 
> https://github.com/kubesphere/kubekey/blob/master/pkg/images/images.go#L89

That's Great !

I have sorted out the related binary files, and the images have been pushed to kubesphere's repo.  
```
    {
      "amd64": "kubeadm v1.23.0: e21269a058d4ad421cf5818d4c7825991b8ba51cd06286932a33b21293b071b0",
      "arm64": "kubeadm v1.23.0: 989d117128dcaa923b2c7a917a03f4836c1b023fe1ee723541e0e39b068b93a6"
    },
    {
      "amd64": "kubelet v1.23.0: 4756ff345dd80704b749d87efb8eb294a143a1f4a251ec586197d26ad20ea518",
      "arm64": "kubelet v1.23.0: a546fb7ccce69c4163e4a0b19a31f30ea039b4e4560c23fd6e3016e2b2dfd0d9"
    },
    {
      "amd64": "kubectl v1.23.0: 2d0f5ba6faa787878b642c151ccb2c3390ce4c1e6c8e2b59568b3869ba407c4f",
      "arm64": "kubectl v1.23.0: 1d77d6027fc8dfed772609ad9bd68f611b7e4ce73afa949f27084ad3a92b15fe"
    }
```

```
kubesphere/kube-apiserver:v1.23.0
kubesphere/kube-controller-manager:v1.23.0
kubesphere/kube-scheduler:v1.23.0
```

**Comment by chaunceyjiang** [comment]
> > Hi,i want to fix this issue but i don't know how to push the `kube-apiserver:v1.23.0` container image to kubesphere repo
> > https://github.com/kubesphere/kubekey/blob/master/pkg/images/tasks.go#L91-L94
> > https://github.com/kubesphere/kubekey/blob/master/pkg/images/images.go#L89
> 
> That's Great !
> 
> I have sorted out the related binary files, and the images have been pushed to kubesphere's repo.
> 
> ```
>     {
>       "amd64": "kubeadm v1.23.0: e21269a058d4ad421cf5818d4c7825991b8ba51cd06286932a33b21293b071b0",
>       "arm64": "kubeadm v1.23.0: 989d117128dcaa923b2c7a917a03f4836c1b023fe1ee723541e0e39b068b93a6"
>     },
>     {
>       "amd64": "kubelet v1.23.0: 4756ff345dd80704b749d87efb8eb294a143a1f4a251ec586197d26ad20ea518",
>       "arm64": "kubelet v1.23.0: a546fb7ccce69c4163e4a0b19a31f30ea039b4e4560c23fd6e3016e2b2dfd0d9"
>     },
>     {
>       "amd64": "kubectl v1.23.0: 2d0f5ba6faa787878b642c151ccb2c3390ce4c1e6c8e2b59568b3869ba407c4f",
>       "arm64": "kubectl v1.23.0: 1d77d6027fc8dfed772609ad9bd68f611b7e4ce73afa949f27084ad3a92b15fe"
>     }
> ```
> 
> ```
> kubesphere/kube-apiserver:v1.23.0
> kubesphere/kube-controller-manager:v1.23.0
> kubesphere/kube-scheduler:v1.23.0
> ```


Hi, `pause:3.6`  is also required ! 

```
 [ERROR ImagePull]: failed to pull image kubesphere/pause:3.6: output: Error response from daemon: manifest for kubesphere/pause:3.6 not found: manifest unknown: manifest unknown
, error: exit status 1
```

``` shell
# kubeadm version                                                                                                                                                                   4 ↵
kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:15:11Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

# kubeadm config images list                                                                                                                                                      130 ↵
k8s.gcr.io/kube-apiserver:v1.23.0
k8s.gcr.io/kube-controller-manager:v1.23.0
k8s.gcr.io/kube-scheduler:v1.23.0
k8s.gcr.io/kube-proxy:v1.23.0
k8s.gcr.io/pause:3.6
k8s.gcr.io/etcd:3.5.1-0
k8s.gcr.io/coredns/coredns:v1.8.6

```

**Comment by pixiake** [comment]
`pause:3.6`  Done！

We will add images synchronization to github action as soon as possible.
