### ISSUE TITLE
kk create config fail with default kubesphere version 

### ISSUE THREAD

**Issue by iddunk** [kubesphere/kubekey#924]
### What is version of KubeKey has the issue?

1.2.1

### What is your os environment?

centos 7.6

### A clear and concise description of what happend.

![image](https://user-images.githubusercontent.com/46773769/147343271-80581c08-ce9f-4958-b0ab-b2084e00a2ad.png)
help docs show that the kubesphere default vesersion is v3.1.0, however a [Unsupported version] error reported

**Comment by 24sama** [comment]
This is a bug in version v1.2.1, and it has been fixed in version v2.0.0.

**Comment by 24sama** [comment]
I think this issue can be closed. Feel free to reopen it.
