### ISSUE TITLE
install timeout

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#93]
Is it network problem?

![Screen Shot 2020-06-24 at 1 39 48 PM](https://user-images.githubusercontent.com/28859385/85505168-4de0ac80-b620-11ea-8bb7-5226a1395cc7.png)

**Comment by pixiake** [comment]
Yes, if the task takes longer than half an hour it will time out.

It is recommended to configure a mirror (accelerator)  for docker. But the latest image may not  be download.
https://docs.docker.com/registry/recipes/mirror/#configure-the-docker-daemon
