### ISSUE TITLE
Request to release v2.0.x alpha

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubekey#931]
Hi team, as I see there are a lot of news features and bug fixes in [v2.0.1](https://github.com/kubesphere/kubekey/releases/tag/untagged-e1ef97dda93cc9c7a1f3), is there a target date to release v2.0.1 alpha? I would like to help to test and promote it in the community.

**Comment by 24sama** [comment]
Yes, of course. We will release `v2.0.0-alpha.3` soon.

**Comment by 24sama** [comment]
KubeKey [v2.0.0-alpha.3](https://github.com/kubesphere/kubekey/releases/tag/v2.0.0-alpha.3) is already release.🎉🎉

**Comment by FeynmanZhou** [comment]
Nice work! Let me close this issue and test it from my side.
