### ISSUE TITLE
Script for adding member cluster needed

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubekey#96]
Please help @zryfish write a script to accomplish the following task so that users only need to execute the script to add a member cluster to host cluster. The doc is at https://github.com/kubesphere/community/tree/master/sig-multicluster/how-to-setup-multicluster-on-kubesphere
<img width="1087" alt="Screen Shot 2020-06-27 at 9 42 54 PM" src="https://user-images.githubusercontent.com/28859385/85923640-5c98bf00-b8bf-11ea-8e62-48e8974c062b.png">

**Comment by pixiake** [comment]
@zryfish Can the configuration of multicluster be saved individually to a configmap using key-value type?
